### ISSUE TITLE
D1X: cheats.enabled check fails

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#111] opened 2015-06-28 17:46 UTC
In FinalCheats() there is a check to prevent the activiation of cheats for D1X in case cheats.\*gotcha != cheats.enabled. However this check does not seem to work properly in the if condition (printfing "cheats.\*gotcha != cheats.enabled" however returns 0 as it should). You can use any cheat (ASTRAL, RACERX, etc) and they will trigger properly in D1X without giving GABBAGABBAHEY prior.

**Comment by vLKp** [comment] 2015-06-28 20:02
Confirmed.  It looks like this would be broken in 0.58.1 D1X as well.  Although the current version uses a pointer-to-member, the basic logic looks like it has not changed since c1e4e9c3d7a4c0b5b126f5b9a62645f3c4cce56c.

**Comment by vLKp** [comment] 2015-06-28 20:06
Fixed in eeb644ad6f3f7e618cbc03f988376490a7faa074.

**Closed by vLKp** 2015-06-28 20:06 UTC

**Comment by zicodxx** [comment] 2015-06-29 11:45
Phew I didn't know it was broken for so long. Thanks for fixing it. :)
