### ISSUE TITLE
Build failure: -Werror=maybe-uninitialized

### ISSUE THREAD

**Issue by rezso** [dxx-rebirth/dxx-rebirth#632] opened 2022-04-15 12:57 UTC
Version: 20220322, gcc 10.2.0

similar/main/gamesave.cpp: In function ‘load_level.constprop’:
similar/main/switch.cpp:708:21: error: ‘trig29.time’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  708 |  trig.time = trig29.time;

**Comment by vLKp** [comment] 2022-04-16 19:41
There is no such version tag `20220322`.  The current code builds clean in x86_64-pc-linux-gnu-gcc-10.3.1.  However, on inspection, that member is unnecessary.  I pushed [Remove write-only legacy trigger field `time`](/dxx-rebirth/dxx-rebirth/commit/06a0de1c901c6b9333d84ed91b59927bc28f7162) to fix this.  Closing as fixed.

**Closed by vLKp** 2022-04-16 19:41 UTC
Labels: build-failure

**Comment by rezso** [comment] 2022-04-16 20:20
Yes, 20220322 not exists as version tag, but exists an dxx-rebirth_20220322-src.tar.xz on the download page of the website. Anyway, your commit fixes the issue, thanks.

**Comment by rezso** [comment] 2022-07-11 00:52
New error:

similar/main/laser.cpp: In function ‘Laser_create_new’:
similar/main/laser.cpp:463:81: error: ‘MEM <const int[16]> [(value_type &)&perturb_array][0]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  463 |   const auto temp_pos = vm_vec_scale_add(blob_pos, perturb_vec, perturb_array[i]);

**Comment by vLKp** [comment] 2022-07-17 15:01
If you need attention, please reopen or file a new issue.  Closed issues are checked rarely.

I cannot reproduce the error shown using x86_64-pc-linux-gnu-g++-10.3.1.  Additionally, my line number mismatches yours, so you are not building the latest code.  When reporting a compilation error, please also report what code you attempted to use, what compiler you used, and any relevant build options.  I tested with master, which is currently [Fix gl.h include location for macOS](/dxx-rebirth/dxx-rebirth/commit/1c8ff1ac0f137aef68a50611c6714cd1cdf0a043).

After reviewing the code, I do not see how this is valid.  If the blob is near, the entire array is initialized to zero.  If the blob is not near, then the array is initialized over the subrange of 0 .. num_omega_blobs, which is the same range that is later iterated.

**Comment by rezso** [comment] 2022-07-17 15:25
I tried to compile the dxx-rebirth_20220622-src.tar.xz tarball, from https://www.dxx-rebirth.com/download/dxx/rebirth/, with gcc 10.2.0. Build options:

scons \
	sharepath=/usr/share/games/d2x \
	prefix=/usr \
	lto=1 \
	sdl2=1 \
	sdlmixer=1 \
	ipv6=1 \
	opengl=1 \
	use_tracker=1 \
	screenshot=png \
	builddir=build/main/ \
	d2x=1.

I can compile d1x without any problems, but d2x fails.
