### ISSUE TITLE
Dying with hostages says "0 hostages lost"

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#186] opened 2016-03-08 16:13 UTC
Tested in co-op. In level 1 when 2 hostages are picked up, if you then die you get the message "0 hostages lost" instead of "2 hostages lost".

**Comment by vLKp** [comment] 2016-03-09 02:15
This is probably caused by [Simplify hostage lost message](/dxx-rebirth/dxx-rebirth/commit/c0ca1248fda78a372c556b2c8aa497d86350a1c6).

**Comment by zicodxx** [comment] 2016-03-14 11:19
I can confirm this to be fixed. Closing. :)

**Closed by zicodxx** 2016-03-14 11:19 UTC
Labels: bug
