### ISSUE TITLE
D1 and D2 crash after selecting random songs on jukebox

### ISSUE THREAD

**Issue by DescentMax** [dxx-rebirth/dxx-rebirth#358] opened 2017-11-13 00:15 UTC
When selecting a song within the game to listen to (ALT SHIFT F11 and F12) The game crashes after a few skips on the songs. 
![d1x-rebirth](https://user-images.githubusercontent.com/33588668/32705080-7bb69444-c7d5-11e7-962d-ef7eb8a917d7.jpg)

**Comment by DescentMax** [comment] 2017-11-13 00:19
Edit, Same issue occures on D2 as well. 

![d2x-rebirth song crash](https://user-images.githubusercontent.com/33588668/32705126-f1655c16-c7d5-11e7-9b66-ba1a15aea5c4.jpg)

**Comment by DescentMax** [comment] 2017-11-13 00:23
Here is the log code from D1x

Rebirth exception printed context
Format UUID: dfd09b9c-8caa-428c-a294-7d12cbd6cd89
Context UUID: 6ab57ee6-8307-4121-9ef7-841b20820694
Rebirth version: x86 D1X-Rebirth v0.59.100 0.59.100-743-g425b78b8a63b
Rebirth built: Nov  8 2017 19:04:57
Rebirth PID: 7696
Report date-time: 2017-11-13-00-09-13
Exception message: "std::bad_alloc"
SP: 02e9f530

02e9f530:   01 00 00 00  6c f5 e9 02  00 00 00 00  13 2a 0d 6d     ....l........*.m
02e9f540:   01 00 00 00  2c f6 e9 02  20 97 11 07  f0 91 e5 6f     ....,... ......o
02e9f550:   6c f5 e9 02  fc ff ff ff  20 97 11 07  e1 e3 f1 6f     l....... ......o
02e9f560:   7c f5 e9 02  00 00 00 00  d6 a7 4e 00  2c f6 e9 02     |.........N.,...
02e9f570:   01 00 00 00  a8 df 89 05  a8 df 89 05  2c f6 e9 02     ............,...
02e9f580:   01 00 00 00  f0 f8 f1 6f  f4 11 f2 6f  a0 f5 e9 02     .......o...o....
02e9f590:   f5 91 e5 6f  50 f5 e9 02  c0 11 f2 6f  b0 f5 e9 02     ...oP......o....
02e9f5a0:   53 e4 f1 6f  60 f5 e9 02  00 00 00 00  00 63 f1 6f     S..o`........c.o
02e9f5b0:   40 19 41 00  70 f5 e9 02  00 00 00 00  ec de f1 6f     @.A.p..........o
02e9f5c0:   20 97 11 07  c0 ec 89 05  fc ff ff ff  22 eb f1 6f      ..........."..o
02e9f5d0:   20 97 11 07  90 f5 e9 02  fc ff ff ff  a5 5c f8 74      ............\.t
02e9f5e0:   9f 72 f9 74  fc ff ff ff  fc ff ff ff  ba db f1 6f     .r.t...........o
02e9f5f0:   40 97 11 07  cc e8 f2 6f  50 ee f0 6f  20 00 00 00     @......oP..o ...
02e9f600:   00 00 00 00  c0 c4 2f bc  48 ec 89 05  08 db f1 6f     ....../.H......o
02e9f610:   fc ff ff ff  ee 13 16 77  00 00 00 00  00 00 00 00     .......w........
02e9f620:   20 00 00 00  c0 ec 89 05  48 f6 e9 02  4c f9 e9 02      .......H...L...
02e9f630:   01 00 00 00  00 00 00 00  20 00 00 00  fc ff ff ff     ........ .......
02e9f640:   20 00 00 00  f0 f8 f1 6f  60 12 f2 6f  60 f6 e9 02      ......o`..o`...
02e9f650:   21 db f1 6f  10 f6 e9 02  d0 fb 66 76  3c 1f a9 c8     !..o......fv<...
02e9f660:   fe ff ff ff  78 f6 e9 02  00 00 00 00  58 3e 14 66     ....x.......X>.f
02e9f670:   fc ff ff ff  00 00 00 00  68 38 13 07  5e 95 33 68     ........h8..^.3h
02e9f680:   0c 07 00 00  ff ff ff ff  cc ff e9 02  f8 1a 0d 07     ................
02e9f690:   fc ff ff ff  fc ff ff ff  68 38 13 07  e1 48 14 66     ........h8...H.f
02e9f6a0:   fc ff ff ff  0c 00 00 00  f8 1a 0d 07  05 43 14 66     .............C.f
02e9f6b0:   20 00 00 00  24 00 00 00  35 39 8f 9d  ec 79 f1 40      ...$...59...y.@

**Comment by DescentMax** [comment] 2017-11-13 00:23
Here is the Log data for D2x:

Rebirth exception printed context
Format UUID: dfd09b9c-8caa-428c-a294-7d12cbd6cd89
Context UUID: 188e0f7d-6610-469d-ab7a-82646e687553
Rebirth version: x86 D2X-Rebirth v0.59.100 0.59.100-743-g425b78b8a63b
Rebirth built: Nov  8 2017 19:05:51
Rebirth PID: 6108
Report date-time: 2017-11-13-00-17-48
Exception message: "std::bad_alloc"
SP: 0331f520

0331f520:   01 00 00 00  5c f5 31 03  00 00 00 00  13 2a 0d 6d     ....\.1......*.m
0331f530:   01 00 00 00  1c f6 31 03  c0 df 3f 05  f0 91 e5 6f     ......1...?....o
0331f540:   5c f5 31 03  fc ff ff ff  c0 df 3f 05  e1 e3 f1 6f     \.1.......?....o
0331f550:   6c f5 31 03  00 00 00 00  ce 88 51 00  1c f6 31 03     l.1.......Q...1.
0331f560:   01 00 00 00  d8 28 4a 07  d8 28 4a 07  1c f6 31 03     .....(J..(J...1.
0331f570:   01 00 00 00  f0 f8 f1 6f  f4 11 f2 6f  90 f5 31 03     .......o...o..1.
0331f580:   f5 91 e5 6f  40 f5 31 03  c0 11 f2 6f  a0 f5 31 03     ...o@.1....o..1.
0331f590:   53 e4 f1 6f  50 f5 31 03  00 00 00 00  00 63 f1 6f     S..oP.1......c.o
0331f5a0:   40 19 41 00  60 f5 31 03  00 00 00 00  ec de f1 6f     @.A.`.1........o
0331f5b0:   c0 df 3f 05  d0 34 1c 10  fc ff ff ff  22 eb f1 6f     ..?..4......"..o
0331f5c0:   c0 df 3f 05  80 f5 31 03  fc ff ff ff  a5 5c f8 74     ..?...1......\.t
0331f5d0:   9f 72 f9 74  fc ff ff ff  fc ff ff ff  ba db f1 6f     .r.t...........o
0331f5e0:   e0 df 3f 05  cc e8 f2 6f  50 ee f0 6f  20 00 00 00     ..?....oP..o ...
0331f5f0:   00 00 00 00  b3 e2 8d ff  30 34 1c 10  08 db f1 6f     ........04.....o
0331f600:   fc ff ff ff  ee 13 16 77  00 00 00 00  00 00 00 00     .......w........
0331f610:   20 00 00 00  d0 34 1c 10  38 f6 31 03  3c f9 31 03      ....4..8.1.<.1.
0331f620:   01 00 00 00  00 00 00 00  20 00 00 00  fc ff ff ff     ........ .......
0331f630:   20 00 00 00  f0 f8 f1 6f  60 12 f2 6f  50 f6 31 03      ......o`..oP.1.
0331f640:   21 db f1 6f  00 f6 31 03  d0 fb 66 76  7f 39 d3 8a     !..o..1...fv.9..
0331f650:   fe ff ff ff  68 f6 31 03  00 00 00 00  58 3e 14 66     ....h.1.....X>.f
0331f660:   fc ff ff ff  00 00 00 00  b8 20 52 07  5e 95 33 68     ......... R.^.3h
0331f670:   24 07 00 00  ff ff ff ff  cc ff 31 03  e8 33 4a 07     $.........1..3J.
0331f680:   fc ff ff ff  fc ff ff ff  b8 20 52 07  e1 48 14 66     ......... R..H.f
0331f690:   fc ff ff ff  0c 00 00 00  e8 33 4a 07  05 43 14 66     .........3J..C.f
0331f6a0:   20 00 00 00  24 00 00 00  35 39 8f 9d  ec 79 f1 40      ...$...59...y.@

**Comment by vLKp** [comment] 2017-11-15 05:25
I edited your comments to wrap the file contents in preformat markers.  Please use those markers when pasting file output, so that whitespace is preserved.

Your report reveals a minor bug in the dump generation code that causes it to generate less output than it should; unfortunately, that reduction causes it not to show enough of a call stack to indicate what function performed the bad allocation.  I will fix that when next I work on the code.  I cannot reproduce the failure with the information provided.  Please provide the minidump of the crash or instructions to reproduce.

**Comment by DescentMax** [comment] 2017-11-18 03:09
To duplicate the issue, tell the jukebox to skip songs in the level either forward or backward 3 or 4 times and it will crash. (ALT SHIFT F11 or F12) Here is my computer specs
Windows 10 Pro 64-Bit
12GB DDR3
AMD FX 6300 3.5GHz 4.1GHz Turbo
240GB SSD
NVIDIA 650TI 2GB GDDR5
Realtek HD Audio
D1x and D2x 0.59.100-743-G425B78B8A63B ( latest November Nightly build)

**Comment by vLKp** [comment] 2017-11-18 03:26
Yes, I tried that.  It worked fine.  It may depend on jukebox configuration.  Please post your jukebox configuration or a minidump.

**Comment by vLKp** [comment] 2017-12-23 21:27
No follow-up from reporter after one month.  Reporter indicated suspicion that the issue was external to Rebirth.  Closing.

OP: please reopen if you can reproduce this and provide the information requested in my previous comment.

**Closed by vLKp** 2017-12-23 21:27 UTC
Labels: needinfo
