### ISSUE TITLE
Runtime bug: non linear turn movement with xbox360 controller

### ISSUE THREAD

**Issue by d-lareg** [dxx-rebirth/dxx-rebirth#624] opened 2022-02-23 20:05 UTC
OS: RetroPie 4.7
Used commit: 15bd145d
Hardware: Pi 4b

Expected behavior
--------------------
When turning the ship the turn speed (yaw) should be constant even if I also rotate it around the pitch axes.

Observed behavior
---------------------
Turning works fine if I only rotate the vessel around the yaw axes. But the yaw rotation gets faster if I also rotate it around the pitch axes.

This behavior was introduced with commit [c621a97 - Reset kconfig counters once, before the event loop](https://github.com/dxx-rebirth/dxx-rebirth/commit/c621a970c6ac31e5eed8270a84b1d43e36990fc7)

As the commit message suggests, the counter should be reset once before...  

https://github.com/dxx-rebirth/dxx-rebirth/blob/7258b7fd5966fc38e53f4d8192b0c810829ada02/similar/main/kconfig.cpp#L1099

... gets called. But this is not always the case. If I move the reset code ...

https://github.com/dxx-rebirth/dxx-rebirth/blob/7258b7fd5966fc38e53f4d8192b0c810829ada02/similar/main/kconfig.cpp#L103

... back to _kconfig_read_controls_ everything is fine. I implemented a few std::cout line to record this behavior. 
The first here:
https://github.com/dxx-rebirth/dxx-rebirth/blob/7258b7fd5966fc38e53f4d8192b0c810829ada02/common/arch/sdl/event.cpp#L63

the second here:
https://github.com/dxx-rebirth/dxx-rebirth/blob/7258b7fd5966fc38e53f4d8192b0c810829ada02/similar/main/kconfig.cpp#L1101

The third here:
https://github.com/dxx-rebirth/dxx-rebirth/blob/7258b7fd5966fc38e53f4d8192b0c810829ada02/similar/main/kconfig.cpp#L1409

If everything would be fine the result should look like this:

```
event_notify_begin_loop()
kconfig_read_controls():in
kconfig_read_controls():out
event_notify_begin_loop()
kconfig_read_controls():in
kconfig_read_controls():out
... 
```

But it looks like this:

```
event_notify_begin_loop()
kconfig_read_controls():in
kconfig_read_controls():out
kconfig_read_controls():in
kconfig_read_controls():out
event_notify_begin_loop()
kconfig_read_controls():in
kconfig_read_controls():out
kconfig_read_controls():in
kconfig_read_controls():out
kconfig_read_controls():in
kconfig_read_controls():out
kconfig_read_controls():in
kconfig_read_controls():out
event_notify_begin_loop()
kconfig_read_controls():in
kconfig_read_controls():out
kconfig_read_controls():in
kconfig_read_controls():out
kconfig_read_controls():in
kconfig_read_controls():out
event_notify_begin_loop()
kconfig_read_controls():in
kconfig_read_controls():out
kconfig_read_controls():in
kconfig_read_controls():out
kconfig_read_controls():in
kconfig_read_controls():out
...
```

- Engines affected (D1X-Rebirth, D2X-Rebirth): Both

**Comment by vLKp** [comment] 2022-02-26 03:52
If I recall correctly, the cited commit was done so that a user who moved both the mouse and the joystick at the same time would get the benefit of both.  Do I understand correctly from your comment that, although the bug causes the ship to turn faster than without the bug, you still do not exceed the turning speed cap?

**Comment by AlumiuN** [comment] 2022-02-26 04:10
Actually, that commit was to fix the control difference in issue #474, where only the last input event of a given frame was being applied. My memory on how the system works is a little hazy, but I suspect what's now happening is that applying movement on two axes is generating an event for each axis, but any movement on the first axis isn't being cleared after being handled (i.e. before handling the movement for the second axis), effectively multiplying the effect of input on that axis by the number of axes subsequently handled, and it didn't apply to the mouse input because any mouse delta event provides a value for all of its axes rather than a single one.

**Comment by AlumiuN** [comment] 2022-02-26 04:37
For what it's worth @d-lareg: multiple calls to kconfig_read_controls() is actually correct otherwise, if a slight misnomer of a function name, as it's called for each event, of which there can (and often will) be multiple per frame. The previous issue was that having the `Controls.pitch_time = Controls.vertical_thrust_time = Controls.heading_time = Controls.sideways_thrust_time = Controls.bank_time = Controls.forward_thrust_time = 0;` line at the start of that function would result in only the last mouse movement event in a given frame actually being used (and under SDL2 it was extremely common for there to be multiple events per frame, even at 200FPS).

**Comment by vLKp** [comment] 2022-02-26 18:02
That too, but I would expect that without the fix, the "last input event of a given frame" problem would apply equally whether it is two mouse inputs (as you reported in #474) or a mouse input and a joystick input.  I had forgotten that issue and how the multiple-events-per-frame was triggering it even on a single input device.  That would be a much more common way for people to hit the problem.

Yes, based on reading the code, I think your analysis is correct.  `raw_joy_axis` is used to memorize the last known position of each joystick axis, since (if I recall correctly) the game only receives JOYSTICK_MOVED events when the user actually moves the joystick.  If the user pushes the joystick all the way forward and holds it there for 10 seconds, the expected behavior is to keep pitching for all 10 seconds, but the input layer stops sending events when the joystick hits its physical stop.  The game must remember that the joystick has not been returned to neutral, and continue to apply the last known state until told otherwise.  The application of that state unfortunately happens in `kconfig_read_controls`, so receiving extra events during the frame will amplify the effect of the remembered joystick position.

https://github.com/dxx-rebirth/dxx-rebirth/blob/7258b7fd5966fc38e53f4d8192b0c810829ada02/similar/main/kconfig.cpp#L1270-L1284

https://github.com/dxx-rebirth/dxx-rebirth/blob/7258b7fd5966fc38e53f4d8192b0c810829ada02/similar/main/kconfig.cpp#L1019-L1028

I think the correct fix will be to introduce and use an EVENT_LOOP_END notifier, and move the `adjust_axis_field` calls into there, so that they are guaranteed to run exactly once per frame, rather than running once per event.  EVENT_IDLE is close to this purpose, but it is only sent if no events were handled.

**Comment by vLKp** [comment] 2022-03-06 22:18
I pushed a fix to compute the joystick results once, at the end of the event loop.  I think this will address the reported problem.  Please reopen if you still see incorrect ship movement.

**Closed by vLKp** 2022-03-06 22:18 UTC
Labels: bug
