### ISSUE TITLE
Losing all hostages when returning from secret level

### ISSUE THREAD

**Issue by teratorn** [dxx-rebirth/dxx-rebirth#495] opened 2020-01-30 05:03 UTC
#### Operating System Environment

  * [x] Ubuntu 19.04 (Disco Dingo)

#### CPU environment

* [x] x86\_64 (64-bit Intel/AMD)

#### Game environment

`descent2.hog` is `7595079` bytes.

### Description

I'm playing a custom Descent 2 mission called `Galaxy Asteroids all` [gstroids.tar.gz](https://github.com/dxx-rebirth/dxx-rebirth/files/4132144/gstroids.tar.gz) - on level 5 there there are 3 hostages. I collect all 3 hostages. There is a secret level. I go to the secret level, which also has 3 additional hostages. I collect those and complete the secret level, which returns me to level 5. This is where the problem happens. There are two problems, which may be unrelated.

The first problem is that upon return from the secret level to level 5, the ship appears in a very "weird" location in the map, and is banged violently against a wall causing a lot of damage and very likely destroying your pyro. Possibly this is due to "bugs" in the level itself - I don't know.

The second problem is that you lose the 6 hostages you had on board, even if you survive the "banging". That is, `player_info.mission.hostages_on_board` is reset to `0`. I know because I'm running a patched version that has a custom "gauge" that displays the number of hostages on board on my HUD, and also because if I survive the banging, and complete level 5 and exit the mine without ever dying, I get told that the hostages were lost. And also because if the banging causes me to die, I do not get the message about hostages being lost like you usually do if you die while hostages are on board. My custom patches have nothing to do with this issue, as they touch unrelated code, and I've also tested with the latest unmodified master as of today 03b6e604ebf7780db8d827f23612f7787a51f6aa and still get the same issues.

I'm attaching a savegame where you are on level 5, with 3 hostages on board, right in front of the entrance to the secret level, if someone would like a headstart debugging this. 
[teratorn.sg4.tar.gz](https://github.com/dxx-rebirth/dxx-rebirth/files/4132173/teratorn.sg4.tar.gz) the Pilot name I'm using is `teratorn` as you can see from the file `teratorn.sg4` inside that tarball.

#### Regression status

N/A

### Steps to Reproduce

* Add the mission to your missions directory. If you extract the tarball I attached, it should have the right directory structure that the savegame expects. i.e. the `.HOG` and `.MN2` files go in a `monsters/gstroids` subdir within your missions directory.
* Copy the savegame `teratorn.sg4` to the right place. On my system it is `~/.d2x-rebirth/`
* Start `d2x-rebirth` and load the savegame
* Enter the secret level ahead of you. Collect the hostages (it's unusual for a secret level to have hostages, I know). Use a cheat to get the red key, or go to the bottom of the secret level and collect all the items, and when you come back up a secret door will open, and you'll be able to go in there and shoot a switch, which allows access to the room that has the red key. Get it. Then go through the red-key door and finding the teleporter back to level 5 should not be difficult. It's not a very large or particularly complex secret level.
* After returning to level 5 you should experience the violent banging against a wall.
* And also you should no longer have any hostages on board

* Engines affected:
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player

Let me know if I can provide additional info, or help in debugging or fixing this. I understand if the violent banging behavior can't be fixed if it's a problem with the level (I don't know).

But I think for sure you shouldn't be losing any hostages. I care about my hosties!!! :-(

Thanks a lot! DXX-REBIRTH RULES!!!

**Comment by vLKp** [comment] 2020-01-30 05:36
Secret levels play weird tricks using the savegame code.  It's a bit odd that your hostage count resets to 0.  I would have expected a bug here to reset you to what you had before entering the secret level.  It could be interesting to have a write access watchpoint on the hostage counter, to see exactly which statement(s) are changing it.  I can try this when I work on the problem, or you can try it if you want to work on this first.

---

The slamming into the wall is probably because the secret-return-segment is incorrect.  This could be a level bug, since that is defined in the level, or it could be a Rebirth bug that is not using the level's requested return correctly.  I'll know more once I try out the level.

**Comment by vLKp** [comment] 2020-02-01 22:41
For future reference, this is easy to test using `Descent 2: Counterstrike` level 3 `Wenl Mine`, which has a secret exit in segment 109.  The associated secret level can be ended quickly by making a U turn from its start, shooting out a wall panel to unlock the adjacent door, and entering that room to get to a secret level teleporter that will return to the base level.  Instead of locating and rescuing hostages, the player's ship can be seeded with the debugger statement:
```
set var d2x::LevelUniqueObjectState.Objects._M_elems[0].ctype.player_info.mission.hostages_on_board = 5
```

---

Secret level handling is a mess.  See below for how the hostage counter is repeatedly rewritten.  The above commit is an ugly fix for this, based on copying the `hostages_on_board` counter out and back at appropriate times.

---

```
(gdb) watch -l d2x::LevelUniqueObjectState.Objects._M_elems[0].ctype.player_info.mission.hostages_on_board
```
Overwritten with placeholder value:
```
Thread 1 "d2x-rebirth-edi" hit Hardware watchpoint 1: -location d2x::LevelUniqueObjectState.Objects._M_elems[0].ctype.player_info.mission.hostages_on_board

Old value = 5 '\005'
New value = 253 '\375'

#2  DXX_POISON_MEMORY<unsigned char*, int> (v=<optimized out>, l=448, b=0x555555881830 <d2x::LevelUniqueObjectState+848> '\375' <repeats 199 times>, <incomplete sequence \375>...) at common/include/compiler-poison.h:104
#3  d2x::read_object (version=32, f=0x5555572c5530, obj=...) at similar/main/gamesave.cpp:363
#4  d2x::load_game_data (vmobjptridx=..., vmsegptridx=..., LoadFile=<optimized out>, LevelSharedDestructibleLightState=...) at similar/main/gamesave.cpp:955
#5  d2x::load_level (LevelSharedDestructibleLightState=..., filename_passed=filename_passed@entry=0x555556aa530a "d2leva-3.rl2") at similar/main/gamesave.cpp:1448
#6  d2x::LoadLevel (level_num=3, page_in_textures=1)
#7  d2x::StartNewLevelSub (level_num=level_num@entry=3, page_in_textures=page_in_textures@entry=1, secret_flag=secret_flag@entry=d2x::secret_restore::survived) at similar/main/gameseq.cpp:1874
```
Restored to correct value:
```
Thread 1 "d2x-rebirth-edi" hit Hardware watchpoint 1: -location d2x::LevelUniqueObjectState.Objects._M_elems[0].ctype.player_info.mission.hostages_on_board

Old value = 253 '\375'
New value = 5 '\005'

#0  (anonymous namespace)::preserve_player_object_info::restore (vmobjptr=..., this=0x7ffffffc57a0) at similar/main/gameseq.cpp:162
#1  d2x::LoadLevel (level_num=<optimized out>, page_in_textures=<optimized out>) at similar/main/gameseq.cpp:1045
#2  d2x::StartNewLevelSub (level_num=level_num@entry=3, page_in_textures=page_in_textures@entry=1, secret_flag=secret_flag@entry=d2x::secret_restore::survived) at similar/main/gameseq.cpp:1874
#3  d2x::state_restore_all_sub (LevelSharedDestructibleLightState=..., secret=d2x::secret_restore::survived, filename=<optimized out>) at similar/main/state.cpp:1670
#4  d2x::state_restore_all (in_game=in_game@entry=1, secret=secret@entry=d2x::secret_restore::survived, filename_override=<optimized out>, blind=blind@entry=dcx::blind_save::no) at similar/main/state.cpp:1490
```
Reset to 0:
```
Thread 1 "d2x-rebirth-edi" hit Hardware watchpoint 1: -location d2x::LevelUniqueObjectState.Objects._M_elems[0].ctype.player_info.mission.hostages_on_board

Old value = 5 '\005'
New value = 0 '\000'

#0  d2x::init_player_stats_ship (GameTime64=<optimized out>, plrobj=...) at similar/main/gameseq.cpp:613
#1  d2x::init_player_stats_level (secret_flag=d2x::secret_restore::survived, plrobj=..., plr=...) at similar/main/gameseq.cpp:615
#2  d2x::StartNewLevelSub (level_num=level_num@entry=3, page_in_textures=page_in_textures@entry=1, secret_flag=secret_flag@entry=d2x::secret_restore::survived) at similar/main/gameseq.cpp:1901
#3  d2x::state_restore_all_sub (LevelSharedDestructibleLightState=..., secret=d2x::secret_restore::survived, filename=<optimized out>) at similar/main/state.cpp:1670
#4  d2x::state_restore_all (in_game=in_game@entry=1, secret=secret@entry=d2x::secret_restore::survived, filename_override=<optimized out>, blind=blind@entry=dcx::blind_save::no) at similar/main/state.cpp:1490
#5  d2x::ExitSecretLevel ()
```
Overwritten with placeholder value (again):
```

Thread 1 "d2x-rebirth-edi" hit Hardware watchpoint 1: -location d2x::LevelUniqueObjectState.Objects._M_elems[0].ctype.player_info.mission.hostages_on_board

Old value = 0 '\000'
New value = 253 '\375'

#2  DXX_POISON_MEMORY<unsigned char*, unsigned char> (v=<synthetic pointer>: 253 '\375', l=448, b=0x555555881830 <d2x::LevelUniqueObjectState+848> '\375' <repeats 199 times>, <incomplete sequence \375>...) at common/include/compiler-poison.h:104
#3  DXX_POISON_VAR<d2x::object> (v=253 '\375', b=...) at common/include/compiler-poison.h:125
#4  d2x::state_object_rw_to_object (obj=..., obj_rw=0x7ffffffc6a90) at similar/main/state.cpp:330
#5  d2x::state_restore_all_sub (LevelSharedDestructibleLightState=..., secret=d2x::secret_restore::survived, filename=<optimized out>) at similar/main/state.cpp:1763
#6  d2x::state_restore_all (in_game=in_game@entry=1, secret=secret@entry=d2x::secret_restore::survived, filename_override=<optimized out>, blind=blind@entry=dcx::blind_save::no) at similar/main/state.cpp:1490
#7  d2x::ExitSecretLevel ()
```
Reset to 0 (again):
```
Thread 1 "d2x-rebirth-edi" hit Hardware watchpoint 1: -location d2x::LevelUniqueObjectState.Objects._M_elems[0].ctype.player_info.mission.hostages_on_board

Old value = 253 '\375'
New value = 0 '\000'

#0  d2x::state_restore_all_sub (LevelSharedDestructibleLightState=..., secret=d2x::secret_restore::survived, filename=<optimized out>) at similar/main/state.cpp:1798
#1  d2x::state_restore_all (in_game=in_game@entry=1, secret=secret@entry=d2x::secret_restore::survived, filename_override=<optimized out>, blind=blind@entry=dcx::blind_save::no) at similar/main/state.cpp:1490
#2  d2x::ExitSecretLevel ()
```
Main level reappears.

---

**Comment by vLKp** [comment] 2020-04-25 20:05
I confirm the extreme damage (from 200 shields -> 5 shields) on returning.  Based on the graphic anomalies, the completely broken automap, and that it all recovers when turning the ship, my guess is that the return location data is bogus and puts the ship partly in a wall.

The title of this issue is about hostage loss, and that is fixed by the above commit from February.  From that, I think this issue should be closed.  Please reopen if you believe the loss of hostages is not solved.

If you think the broken return is a regression relative to 0.58.1, please open a new issue for further investigation.

**Closed by vLKp** 2020-04-25 20:05 UTC
Labels: bug
