### ISSUE TITLE
Random crash mid-game

### ISSUE THREAD

**Issue by Hijongpark** [dxx-rebirth/dxx-rebirth#661] opened 2022-09-01 08:08 UTC
I use windows 10 and playing descent 2 campaign.

I'm having a problem where the game suddenly crashes mid-game and lose all my progress after saving.

It is especially frustrating when crash is not happening persistently but just random. Sometimes it doesn't happen until I beat a level and otherwise happens mid-point.

**Comment by vLKp** [comment] 2022-09-01 16:43
Based on the information provided, there is nothing I can do for you.  I don't know what build you are playing, so I cannot comment on any known bugs in that build.  I don't know under what circumstances the game crashes, so I cannot offer advice on how to avoid the crash, nor can I investigate possible causes.  What do you want to achieve with this issue?

**Comment by agibson2** [comment] 2022-09-01 18:54
Is there a way for him to get a crash dump on windows to load into the debugger?  Most apps can produce crash dumps that can be used to help debug crashes.  I am not sure if that is created with descent or not.

**Comment by vLKp** [comment] 2022-09-01 21:13
Yes.  If the game is built with minidump support, it will automatically try to generate a crash dump if a C++ exception occurs.  If the game is crashing due to an OS exception, like STATUS_ACCESS_VIOLATION, then that is not handled by the game, because the process may be in too broken a state to do that.  At that point, the crash needs to be collected by the operating system's crash handler, since that runs out of process and can produce a clean capture.  Without knowing how it is crashing, it is hard to say whether the game can collect this one.  The Windows Event Log _might_ tell something useful.

**Comment by Hijongpark** [comment] 2022-09-02 00:00
I have enabled -verdose and -safelog, the game just crashed while i was looking at automap and the log now shows some new logs

08:03:46.313 Failed to open movie <pre_i.mve>: not found
08:03:46.314 Rebirth: movie subtitles are disabled
08:03:57.248 PHYSFS: failed to unmap canonical directory "C:\Users\phj98\Downloads\dxx-rebirth_20220823-win\D2X-Rebirth\descent.hog" (relative name "descent.hog"): "not mounted"
08:03:57.258 similar/main/gameseg.cpp:1529: segment #128 side #4 has invalid tmap 910 (NumTextures=910).  Please report this to the level author, not to the Rebirth maintainers.


08:16:50.600 similar/main/gameseg.cpp:1529: segment #26 side #5 has invalid tmap 910 (NumTextures=910).  Please report this to the level author, not to the Rebirth maintainers.
08:16:50.600 similar/main/gameseg.cpp:1529: segment #28 side #5 has invalid tmap 910 (NumTextures=910).  Please report this to the level author, not to the Rebirth maintainers.
08:16:50.601 similar/main/gameseg.cpp:1529: segment #60 side #5 has invalid tmap 910 (NumTextures=910).  Please report this to the level author, not to the Rebirth maintainers.
08:16:50.601 similar/main/gameseg.cpp:1529: segment #63 side #5 has invalid tmap 910 (NumTextures=910).  Please report this to the level author, not to the Rebirth maintainers.
08:16:50.603 similar/main/gameseg.cpp:1529: segment #161 side #4 has invalid tmap 910 (NumTextures=910).  Please report this to the level author, not to the Rebirth maintainers.
08:16:50.606 similar/main/gameseg.cpp:1529: segment #305 side #4 has invalid tmap 910 (NumTextures=910).  Please report this to the level author, not to the Rebirth maintainers.
08:16:50.609 similar/main/gameseg.cpp:1529: segment #427 side #4 has invalid tmap 910 (NumTextures=910).  Please report this to the level author, not to the Rebirth maintainers.
08:16:50.611 similar/main/gameseg.cpp:1529: segment #533 side #5 has invalid tmap 910 (NumTextures=910).  Please report this to the level author, not to the Rebirth maintainers.
08:16:50.611 similar/main/gameseg.cpp:1529: segment #536 side #4 has invalid tmap 910 (NumTextures=910).  Please report this to the level author, not to the Rebirth maintainers.
08:16:50.613 similar/main/gameseg.cpp:1529: segment #647 side #4 has invalid tmap 910 (NumTextures=910).  Please report this to the level author, not to the Rebirth maintainers.
08:16:50.613 similar/main/gameseg.cpp:1529: segment #648 side #5 has invalid tmap 910 (NumTextures=910).  Please report this to the level author, not to the Rebirth maintainers.


08:26:30.602 BUG: buddy is object 178, but that object is type 255.

**Comment by Hijongpark** [comment] 2022-09-02 23:57
> Check windows Application eventlog using EventViewer. It is possible the OS has created crash dumps.

D2x rebirth just crashed now. how to check it in eventviewer ?

**Comment by Hijongpark** [comment] 2022-09-02 23:59
d2x just crashed now and this is the log from eventviewer.

로그 이름:         Application
원본:            Application Hang
날짜:            9/3/2022 8:49:34 AM
이벤트 ID:        1002
작업 범주:         (101)
수준:            오류
키워드:           클래식
사용자:           해당 없음
컴퓨터:           DESKTOP-7GELGL2
설명:
프로그램 d2x-rebirth.exe 버전 0.0.0.0에서 Windows와의 상호 작용을 중지했으며 해당 프로그램이 종료되었습니다. 문제에 대한 자세한 정보가 있는지 알아보려면 보안 및 유지 관리 제어판에서 문제 기록을 확인하십시오. 
 프로세스 ID: 3934
 시작 시간: 01d8bf22c6fe3384
 종료 시간: 2
 응용 프로그램 경로: C:\Users\phj98\Downloads\dxx-rebirth_20220823-win\D2X-Rebirth\d2x-rebirth.exe
 보고서 ID: 95d6d8b9-1a8e-462e-b1c5-42a305983c0f
 오류 있는 패키지 전체 이름: 
 오류 패키지 패키지에 상대적인 응용 프로그램 ID: 
 중단 유형: Cross-thread

이벤트 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" />
    <EventID Qualifiers="0">1002</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>101</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-09-02T23:49:34.0988989Z" />
    <EventRecordID>3700</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-7GELGL2</Computer>
    <Security />
  </System>
  <EventData>
    <Data>d2x-rebirth.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>3934</Data>
    <Data>01d8bf22c6fe3384</Data>
    <Data>2</Data>
    <Data>C:\Users\phj98\Downloads\dxx-rebirth_20220823-win\D2X-Rebirth\d2x-rebirth.exe</Data>
    <Data>95d6d8b9-1a8e-462e-b1c5-42a305983c0f</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>Cross-thread</Data>
    <Binary>430072006F00730073002D00740068007200650061006400000044006500610064006C006F0063006B0000000000</Binary>
  </EventData>
</Event>

**Comment by Hijongpark** [comment] 2022-09-03 00:01
원본
d2x-rebirth.exe

요약
Stopped responding and was closed

날짜
‎9/‎3/‎2022 8:49 AM

상태
보고하지 않음

설명
A problem caused this program to stop interacting with Windows.
오류 있는 응용 프로그램 경로:	C:\Users\phj98\Downloads\dxx-rebirth_20220823-win\D2X-Rebirth\d2x-rebirth.exe

문제 서명
문제 이벤트 이름:	AppHangB1
Application Name:	d2x-rebirth.exe
Application Version:	0.0.0.0
Application Timestamp:	630487db
Hang Signature:	b113
Hang Type:	134218242
OS 버전:	10.0.19043.2.0.0.256.48
로캘 ID:	1033
Additional Hang Signature 1:	b1135a79cfd9b5dbda75e39a183bc130
Additional Hang Signature 2:	9901
Additional Hang Signature 3:	99010be69eb4c8d05134dd34b1f85b92
Additional Hang Signature 4:	7c1f
Additional Hang Signature 5:	7c1f91a06eab10e43c1bb64cee8e992f
Additional Hang Signature 6:	e166
Additional Hang Signature 7:	e166ce813490e0e468f27c0d5c93414b

**Comment by agibson2** [comment] 2022-09-03 00:26
You need to find the directory where the crash dumps are stored.

C:\Users\YourProfileDirectory\AppData\Local\CrashDumps\
(replacing YourProfileDirectory with your user profile name)

I would  check there for the crash dump.  I have some in that directory.  Otherwise you will need to search the Net for the locations that it could be.  There can be a few.

**Comment by agibson2** [comment] 2022-09-03 00:29
Also look in this directory...
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\

**Comment by Hijongpark** [comment] 2022-09-03 01:12
> Also look in this directory... C:\ProgramData\Microsoft\Windows\WER\ReportArchive\

The archives there aren't accessible, and google provided viewing crashdumps through system and security/ action center.

My second comment is what action center showed about d2x rebirth.exe crash.

**Comment by vLKp** [comment] 2022-09-03 17:00
I see nothing in the posted data that leads me to believe that this is a problem in Rebirth itself, versus in some system library.  I am not aware of any bugs which would manifest as Application Hang.  If you can provide steps by which I can reproduce this on my machine, or a memory address implicating code in the Rebirth executable, I can look at this further.  Otherwise, there is nothing to do here.  The requested Windows minidump would provide such an address, but it is not clear to me that the system has even created such a minidump.

**Comment by agibson2** [comment] 2022-09-03 17:06
This Microsoft article explains how to enable full crash dumps...
https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

**Comment by Hijongpark** [comment] 2022-09-03 23:57
for some reason my computer dont have LocalDumps folder at HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting.

maybe Im just cursed not to play descent out of dosbox.

**Comment by agibson2** [comment] 2022-09-04 00:27
You will likely need to create it.  I have attached a reg file that you can import to create one specific to d2x-rebirth.exe so that it only affects programs named d2x-rebirth.exe.

It sets it to the following for d2x-rebirth.exe...
Max count of 3 dumps stored
Folder C:\DumpFolder
Dump type 3 (full memory dump)

You must create the   C:\DumpFolder    ahead of time.

After you import that, the game should store the crash dump in that folder.
[d2x-rebirth-crashdump-fulldump.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/9483588/d2x-rebirth-crashdump-fulldump.zip)

**Comment by Hijongpark** [comment] 2022-09-04 08:06
![bandicam 2022-09-04 16-54-18-019](https://user-images.githubusercontent.com/95468878/188303620-d82fd795-8e3d-4af1-aa11-dea7bd0240fa.jpg)

I have imported the rag file you imported and played d2x rebirth until another crash.

I can see that a new folder is now created with the crashdumps there.

How to open those 3 files with notepad ? I can't find any possible ways, is it the Binary Data you want to see ?

**Comment by Hijongpark** [comment] 2022-09-04 08:16
[d2xrebirth crashdump.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/9484283/d2xrebirth.crashdump.zip)

I figured out that those reg files can be exported in registry editor. will these 3 reg files be helpful ?

**Comment by agibson2** [comment] 2022-09-04 15:48
The registry just tells the OS how to configure crash dumps.  The crashes don't get stored in the registry.  The crashes will get stored on your hard drive under C:\CrashDumps\ 
You must create the CrashDumps file folder on your C: drive using Windows Explorer.  Create a new folder called CrashDumps under C: drive.
Then make the crash happen again and zip up any files in C:\CrashDumps

**Comment by Hijongpark** [comment] 2022-09-05 03:35
I have created CrashDumps and got yet another crash, but nothing was created in  C:\CrashDumps\...

I just gave up.

**Comment by agibson2** [comment] 2022-09-06 01:25
I can't test it as I can't get it to crash.  My reg file had 2 problems though so I updated it.  The value for DumpFolder should have been REG_EXPAND_SZ instead of REG_SZ.  The dump type should have been 2 instead of 3 for a full dump also.

I changed the directory to the default also (%LOCALAPPDATA%\CrashDumps) which will end up being...
C:\Users\YourUserProfileName\AppData\Local\CrashDumps\.  This will make sure you have permission to it.
(You might not be able to see the AppData directory as it is a hidden directory.  If you type it in though into Windows Explorer, it will take you there.  Just change YourUserProfileName to whatever your profile directory name is under C:\Users\

I corrected it in the new v2 zip file that I created above.  Import it again and see if that works.  If it doesn't, then I really don't know why Windows Error Reporting wouldn't use the settings.

**Comment by vLKp** [comment] 2022-09-11 17:14
@Hijongpark wrote:

> I just gave up.

By this, do you mean that you abandoned attempting to collect a crash dump?  If so, there is nothing more I can do in this issue.  The issue has no steps to reproduce the problem.  The issue specifically describes the problem as "random", suggesting that blind attempts to reproduce it are unlikely to succeed.  The issue has no information that leads me to believe this is a bug in the game's code.  From the information that is available ("Application Hang"), I suspect that this is not a crash, but some other type of failure.  Rebirth does not explicitly use threads during gameplay, so the line `중단 유형: Cross-thread` is strange.

Additionally, @agibson2 also cannot reproduce the issue.  From these points, I am inclined to close the issue as cannot-reproduce.  If you disagree, please reopen and provide information I can use to pursue this problem.

**Closed by vLKp** 2022-09-11 17:14 UTC
