### ISSUE TITLE
No Music

### ISSUE THREAD

**Issue by krux02** [dxx-rebirth/dxx-rebirth#447] opened 2019-08-25 08:20 UTC
I just bought descent II on GOG, built the game from source on Linux and moved the required files from the gog release into the required folder. I had to rename them all because Linux is case sensitive. Then the game still didn't start. I had to add the argument ``-hogdir ./Data`` explicitly, but that is also reported [here](https://github.com/dxx-rebirth/dxx-rebirth/issues/403). Then I could finally start the game, but with no music at all. I could not find a tutorial that explains how to enable the original music. So I decided to convert the original music from the gog version cd image into wav files and put them in a music folder and play them via the jukebox option. No idea if the correct music is played, I never played Descent II, I don't know what music is supposed to be correct and what isn't. And I still have no music at all in the main menu. 

It would be nice if the friction to finally play the game would be lower. Also some documentation on how to enable the original CD audo music would be nice. Anyway, thank you for keeping this old game alive.

### Environment

 * build from source
 * 4504f3602a4df16836736a87ebfb15fc19500f90
 * Manjaro Linux
 * x86\_64 Intel
 * D2X-Rebirth

**Comment by vLKp** [comment] 2019-08-25 17:10
Issue #403 is specifically about Mac OS X.  Your problem is that the instructions were incorrect.  The instructions tell you to use a directory named `Data`.  The code looks for a directory named `data`.  Due to the case mismatch, following the instructions gives you a non-working configuration.  This appears to be a regression introduced in [Add 'Data' subdir as a searchpath, so D2X will find descent.pig and to simplify a lot of file opening/checking/closing code](/dxx-rebirth/dxx-rebirth/commit/e6169f17f9e3705f6b0f43454eab013873b016d0).  The lines removed in that commit used `Data`.  The search added in that commit used `data`.

I will fix the instructions, since existing users may be relying on the current path of `data`.

I never play with the CD music.  I prefer to be able to hear enemies sneaking up on me.  If you (or anyone reading this later) find or write documentation on doing the CD music, I'll include it.

**Comment by vLKp** [comment] 2019-08-25 17:16
For your main report: do you now have music in-game via the jukebox, but no main menu music?  Or do you still have no music anywhere?  How _exactly_ did you set up the music files that you expect to work?  Please describe it in enough detail that I can set up the same music on my system.

**Comment by krux02** [comment] 2019-08-26 00:13
Sorry for misinformation about the Music. I configured descent to use music via jukebox and I set the folder for the music to be `./music` (could also be `./MUSIC`, the descent font is case indistinguishable), and I put my music files into the `./music` folder in wav format. But I don't actually have any music. Setting up the music didn't work at all. When I wrote this issue I just assumed it would not be an issue ingame when I set the music to jukebox, but apparently it is.

It is not like I can't put a music player in the background of my computer. But that is not the point. The point is, there is probably a reason why this game has this type of music. And I would really like to hear the levels with the soundtracks that were intended for them to be played.

**Comment by krux02** [comment] 2019-08-26 21:23
I would like to update my status. I was able to get music into descent 2. I did it with this link [here](https://www.dxx-rebirth.com/addons/). I got this link from [this video instruction](https://www.youtube.com/watch?v=yTsBZ82MZKc). Even though I do now have music. I don't have the music playing from the CD image that I bought from GOG. And I could not find this information from the start of the homepage.

**Comment by krux02** [comment] 2019-08-27 08:51
> Issue #403 is specifically about Mac OS X. Your problem is that the instructions were incorrect. The instructions tell you to use a directory named Data. The code looks for a directory named data. Due to the case mismatch, following the instructions gives you a non-working configuration. This appears to be a regression introduced in Add 'Data' subdir as a searchpath, so D2X will find descent.pig and to simplify a lot of file opening/checking/closing code. The lines removed in that commit used Data. The search added in that commit used data.

If that is correct I should be able to rename ``Data`` to ``data`` and be good with it, but that doesn't solve the problem, because then the other resource files can't be found. Then I thought then maybe some files are search in ``Data`` and other are searched in ``data`` and created a folder symlink from ``Data`` to ``data``, so that both paths ``data`` and ``Data`` are correct. But also no luck with it. Starting Descent without specifying hogdir didn't work.

**Comment by zicodxx** [comment] 2019-08-27 22:17
I have never written a tutorial on how to play the CD Music via Rebirth because so far it's always been easiest to just use the CD or make a CD image, mount that and Rebirth would usually get that just fine. However considering SDL2 drops Redbook support, I should maybe supplement a file on how to set it up via the Jukebox. I would - like the rest of the instructions - like to keep that within the packages itself. 

The Addon you got from the site (by the way, you find those in a submenu under Downloads), @krux02 are a conversion of the MIDI soundtrack - not the CD Audio. Those differ quite heavily. Your CD rip idea should actually work, but I don't think it's gonna do WAV. Although the list of supported formats eventually depends on how SDL_mixer is compiled on your system, OGG, FLAC or MP3 are usually a safer bet. Especially OGG since that is the format the Addons come in and those apparently work on your system.

If apart from CD-Audio instructions you'd like to see something else elaborated in more detail, let me know. I'll gladly rework some of the documentation, but I need to know what needs to be elaborated, which is a bit hard to tell for me since I've done all imaginable steps countless times already.

**Comment by vLKp** [comment] 2019-08-29 04:14
Renaming `Data` to `data` was sufficient to let me drop `-hogdir` from my startup script.  If it doesn't work for you, I need more information than "other resource files".  What _exactly_ was not found, and where was it stored?

**Comment by vLKp** [comment] 2020-03-28 18:29
No response from reporter.  General documentation improvements, while useful, are out of scope for this ticket.  Closing.

@krux02 : please reopen if you would like to continue work on this.

**Closed by vLKp** 2020-03-28 18:29 UTC
Labels: bug

**Comment by krux02** [comment] 2020-03-28 19:44
Yea sorry. I don't play this game anymore.

**Comment by rebb** [comment] 2021-06-08 15:43
I can't get CD Music to work unfortunately, even when mounting the GoG CD Image file ( it is mounted to X: in my case ).
Does it need to be a specific drive letter to mount, so that Rebirth uses it for the CD Music ?

**Comment by vLKp** [comment] 2021-07-02 02:08
@rebb: No specific drive letter is required.  As I read the Rebirth code for this, when you choose CD Music, Rebirth will have SDL check each CD drive for a CD that provides Redbook audio.  Are you sure that SDL even recognized your virtual CD mount as a CD drive?  Rebirth should print some basic status messages to its console when it tries to initialize redbook audio mode.

Also, please note that commenting on a long dead issue is not a good way to get help.  Closed issues are not routinely checked for new comments.

**Comment by rebb** [comment] 2021-09-19 12:48
Coming back to this, i think it was/is an issue with the Mounting software i used.
WinCDEmu apparently does not support Audio Tracks on CDs, which i wasn't aware of for the longest time.
Music works fine when using Daemon Tools though :)

Sorry for the confusion.

**Comment by krux02** [comment] 2021-09-19 15:06
I was trying get music on Linux, Daemon Tools was therefore not an option.
