### ISSUE TITLE
Build failure: Windows x86_64 build using MinGW 64

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#658] opened 2022-08-21 00:16 UTC
### Environment

Attempting to compile 25688635bb42d0de4289311acc5234bd7c925022 for Windows.
Environment is MinGW 64 on a Windows 10 OS.
Build is compiled simply using "scons -j6". No additional arguments.

#### Operating System Environment

* [ ] Microsoft Windows (32-bit)
* [X] Microsoft Windows (64-bit)
* [ ] Mac OS X

* Debian
  * [ ] Debian Stretch
  * [ ] Debian Buster
  * [ ] Debian Bullseye
  * [ ] Debian Sid
* Fedora
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Fedora 31
  * [ ] Fedora 32
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)
  * [ ] Ubuntu 19.10 (Eoan Ermine)
  * [ ] Ubuntu 20.04 LTS (Focal Fossa)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

Build fails to compile with the following error: 
```
CXX d1x build/ similar/main/ai.cpp
CXX d1x build/ similar/main/aipath.cpp
CXX d1x build/ similar/main/automap.cpp
In file included from common/include/physfsx.h:39,
                 from common/include/hmp.h:17,
                 from common/misc/hmp.cpp:19:
common/include/u_mem.h: In instantiation of 'void dcx::d_free(T*&) [with T = midihdr_tag]':
common/misc/hmp.cpp:136:9:   required from here
common/include/u_mem.h:107:49: error: static assertion failed: d_free cannot free non-integral
  107 |     static_assert((std::is_same<T, void>::value || std::is_integral<T>::value), "d_free cannot free non-integral");
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common/include/u_mem.h:107:49: note: '(((bool)std::integral_constant<bool, false>::value) || ((bool)std::integral_constant<bool, false>::value))' evaluates to false
CXX d1x build/ similar/main/bm.cpp
scons: *** [build/common/misc/hmp.o] Error 1
scons: building terminated because of errors.
Failed target count: total=1; targets with enable_build_failure_summary=1: 1
Failed node list:
        build/common/misc/hmp.o
Failed command list:
 g++ -c -g -O2 -ftabstop=4 -Wall -Werror=extra -Werror=format=2 -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -funsigned-char -std=gnu++20 -Werror=unused -Werror=useless-cast -Wimplicit-fallthrough=5 -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wsuggest-attribute=noreturn -Wlogical-op -Wold-style-cast -Wredundant-decls -Wno-sign-compare -D_WIN32 -DWIN32_LEAN_AND_MEAN -DPHYSFS_DEPRECATED= -DNDEBUG -DRELEASE -D_WIN32_WINNT=1536 -Icommon/include -Icommon/main -I. -Ibuild -ID:/dev/msys64/mingw64/include/libpng16 -ID:/dev/msys64/mingw64/include -ID:/dev/msys64/mingw64/include/SDL "common/misc/hmp.cpp" -o "build/common/misc/hmp.o"
```

#### Regression status

The latest known commit I was able to build is d1ed53ebd9cb9bad753c5e25331a184461338d9e. There may be others in between, but my build environment recently updated gcc from 10.0 to 12.2 which makes older builds fail as well which makes bisecting this issue a bit tricky

**Comment by vLKp** [comment] 2022-08-21 13:01
That showed up as a secondary break reported in the thread where Github Actions support was added (though the Github Actions were not the cause - that was just the first time someone tried to build for Windows after the break happened).  I have a fix queued locally, but have not pushed it.  I will try to get it out soon.

**Comment by zicodxx** [comment] 2022-08-22 13:35
Thank you so much. :)
And no worries about the time - not a matter of life and death.

**Comment by vLKp** [comment] 2022-08-23 02:30
This should be fixed now.  I changed the hmp code not to use the d_alloc / d_free functions, and instead store the required data inline.

Please reopen if you still see problems.

**Closed by vLKp** 2022-08-23 02:30 UTC
Labels: build-failure
