### ISSUE TITLE
(D2) Bomblets accelerate too slowly

### ISSUE THREAD

**Issue by ryusei117** [dxx-rebirth/dxx-rebirth#204] opened 2016-08-12 08:40 UTC
Tested versions with this bug: D2X-Rebirth commit 4cb3d46148740ad44d4dba7298a4ebca27e39e42
Tested versions without this bug: D1X-Rebirth and D2X-Rebirth 0.58.1, D1X-Rebirth commit 4cb3d46148740ad44d4dba7298a4ebca27e39e42

Bomblets from Smart Missiles, Smart Mines, and Earthshaker Missiles accelerate less quickly than in the original MS-DOS D2 engine. The acceleration rates don't seem to vary with the frame rate, though. Here are some demos comparing the original engine and the D2X-Rebirth development code:

[bomblets_d2x_rebirth.zip](https://dl.dropboxusercontent.com/u/26944122/dxx_rebirth_issues/bomblets/bomblets_d2x_rebirth.zip)

[D2X Retro has a similar bug](https://github.com/CDarrow/DXX-Retro/issues/78), but it's actually frame rate-dependent. I wonder if the two bugs are related ... maybe something to do with the homing code fixes from Retro?

**Comment by vLKp** [comment] 2016-08-13 15:19
To clarify, commit [Move `<type_traits>` test to Cxx11RequiredFeature](/dxx-rebirth/dxx-rebirth/commit/4cb3d46148740ad44d4dba7298a4ebca27e39e42) is the commit you built and tested to observe the problem, but is not the earliest known bad commit, correct?  That commit should not affect the build product at all, so the regression was likely introduced earlier.  It might be helpful to know the first bad commit, but if you do not know it, we can approach this ticket in some other way.

Although Smart Mines and Earthshakers are D2-specific, Smart Missiles appear in both games.  Do I understand correctly from your description that Smart Missile bomblets work correctly when fired using D1, but incorrectly when fired under the same circumstances using D2?  I interpret your mention of D**X**X-Rebirth 0.58.1 on the *without the bug* line to mean that both games worked correctly in 0.58.1, but only D**1**X-Rebirth works correctly with the identified commit.

**Comment by ryusei117** [comment] 2016-08-14 01:26
Yep, that's all correct. I was trying to make my usual bug report header more concise and orderly, but I guess it also became a bit ambiguous. I should change it to say "**Tested** versions with the bug", since I'm listing all of the versions I tested, and omitting the versions I didn't test. I'll also split "DXX-Rebirth" into D1 and D2 so it's clear I didn't make a typo like that one time. :-P

So yeah, unfortunately that means I don't know the earliest bad commit. I'll test some old commits near the homing fixes later and see if I can narrow it down.

**Comment by zicodxx** [comment] 2016-08-15 09:46
Yeah, this is pretty easy to see, thank you. But if I may ask: How did you lock down the original D2 to 30 and 200 FPS? I mostly ask to make it easier for me to test myself. I know there are a few DOSBox builds that support VSync and Framecap options, but those usually only limit the actual frame output - not how fast the game actually runs.

**Comment by ryusei117** [comment] 2016-08-16 03:19
Oh yes, limiting the frame rate was "fun". :-P I used the FRAMETIME cheat and messed with the DOSBox CPU cycle rate until I got about 30 FPS in the exact spot I was planning to fire the Smart Missile. And then I fired the missile ... and watched the frame rate drop to 20 FPS. >:-( After some trial and error, I found the cycle rate that resulted in 30 FPS while the bomblets were actually in the air.

200 FPS required a pretty high cycle rate, even at 320 x 200 res. The game started to go slow motion as DOSBox exceeded my real CPU's speed - but aside from the slowness, it looked as if DOSBox was successfully emulating the game at 200 FPS, super-high ship bobbing and everything.

**Comment by zicodxx** [comment] 2016-08-17 12:37
I think I can safely conclude that the bug doesn't exist in 0.58.1. Frankly, the more I look at recorded demos of different versions, the harder it's to spot the difference but jumping from one frame to the next in a demo it seems that in the original game, smart blobs move ~ 1x their own size per frame while in newer builds it seems to be ~ 0.5 their size. @ryusei117 if you think you could confirm that my observation is correct (about the observed movement speed and that it doesn't seem to appear in 0.58.1), that would be very helpful for me to find the issue. 
The new homing code doesn't seem to be responsible for this, luckily.

**Comment by zicodxx** [comment] 2016-08-20 11:28
Update: I tracked down the issue and lo and behold the bomblets become slower as I introduced the FPS-cap for homers as Retro uses (bbaa3c21f34283b8783522de5d722d07d8aed750). Sadly, this is not the source of the issue as the previous approach was wrong because track_track_goal was finding a valid target much more often as intended causing speed for the homing projectiles ramping up much faster. 
track_track_goal is also still not in it's original shape and I am now in the process of restoring this code part to it's 'historically accurate' version (based on the original Descent 2 source release), eliminating all mixups between D1 and D2 homing codes that occurred over the years (but retaining a 30 FPS cap for the homing projectiles of course).

**Comment by ryusei117** [comment] 2016-08-22 07:22
Oh my, I was suspecting some easy-to-fix oversight in the Retro homing code, but it sounds as if this is one of those complicated "fixing one bug exposed a different bug" situations! Thanks for looking into this.

Both of those things are correct: the bug doesn't seem to exist in 0.58.1, and the Smart blob movement speeds you posted seem accurate. Actually, since the blobs accelerate as they track, those speeds change over time. In 0.58.1, I saw the blobs move about 1.25x their own size per demo frame as they neared their target. But yeah, it seems that the bugged blobs are somewhere around half as fast.

Whoops, I completely forgot that original engines run too fast at high frame rates ... DOSBox running slow prevented me from noticing. :-P Well, at least now we know that the bomblets run too fast along with everything else instead of slowing down ...

**Comment by zicodxx** [comment] 2016-08-22 12:13
If have just committed 89a2df0e1884d48293dc288360800a7f61520d08 which should fix the bug. 
Actually it contains 3 fixes:

1) Restoration of object_is_trackable
An extra condition was introduced between D1 and D2 which however got lost somewhere between 0.58.1 and Unification. Have not checked when or why this was removed but it may just have been me trying to unify the source more towards D1 then keeping the unique behaviors of both games. 

2) Restoration of track_track_goal
D2 introduced slightly different timings in which homing projectiles would switch between staying on target or looking for new ones. I knew about this problem before this issue was posted and I was actually about to commit that fix but then I saw your initial bug report @ryusei117. 

3) Scaling of homing_missile_turn_towards_velocity
After turning the homing missiles towards where their target, at the end the model is rotated accordingly. However this scale is done via FrameTime and since this turn is now capped to 30 times per second, FrameTime would not turn the model enough. I fixed the scaling.

Points 1 and 2 (1 in particular) are the main culprits of this bug. 

Instead of working with older versions of Rebirth, I have - before and while addressing this bug - used the original Descent 1 and Descent 2 source releases to recreate the original behaviors of the homing projectiles and I believe that they now represent the original games accurately. 

I will keep this report open in hope that you can confirm my fixes, @ryusei117 and maybe also compare the normal homing missiles in both D2X and the original game if that's not too much to ask. :)

**Comment by vLKp** [comment] 2016-08-23 01:22
According to `git log github/unification/master ^0.58.1-d{1,2}x -L1026,1058:similar/main/laser.cpp`, there were 16 commits that modified this function after 0.58.1 was released and before the commit zico referenced above.  The most likely candidate, based on the changes in zico's commit today, is [Cleaned code for homing projectiles a bit and reverted to state of Descent 1 source release; Added ticks to rule target aquisition and adjusted turn rate scaling accordingly](/dxx-rebirth/dxx-rebirth/commit/2b632008b2ecc242ef8380e99a757c61bb1ffb19#diff-f2484459df96d79f4fe06a06cfe2806aL899):
```diff
diff --git a/d2x-rebirth/main/laser.c b/d2x-rebirth/main/laser.c
index db89f23..a6ac735 100644
--- a/d2x-rebirth/main/laser.c
+++ b/d2x-rebirth/main/laser.c
@@ -896,12 +895,7 @@ int object_is_trackable(int track_goal, object *tracker, fix *dot)
    vm_vec_normalize_quick(&vector_to_goal);
    *dot = vm_vec_dot(&vector_to_goal, &tracker->orient.fvec);
 
-   if ((*dot < Min_trackable_dot) && (*dot > F1_0*9/10)) {
-       vm_vec_normalize(&vector_to_goal);
-       *dot = vm_vec_dot(&vector_to_goal, &tracker->orient.fvec);
-   }
-
-   if (*dot >= Min_trackable_dot) {
+   if (*dot >= HOMING_MIN_TRACKABLE_DOT) {
        int rval;
        //  dot is in legal range, now see if object is visible
        rval =  object_to_object_visibility(tracker, objp, FQ_TRANSWALL);
```

**Comment by zicodxx** [comment] 2016-08-23 01:36
Yeah, so my memory wasn't wrong, I DID cause this on a copy/paste spree. But I have absolutely no idea anymore why I did it like that. Probably I thought or someone told me that the D1 homers were better (which they aren't). In any regard, I think both games should have their respective behaviors back now.

**Comment by ryusei117** [comment] 2016-10-06 06:23
So ... apparently it took me over a month to find some time to test this ... So sorry. :-[ I tested commit ba2b8c05ba03161f5aa219a53de7fa39acc4d92e, and the Smart Missile bomblets do seem to accelerate correctly now. Also, the D1 Homing Missiles are dang near perfect. Both in the original engine at 30 FPS and Rebirth, I can just barely dodge them with horizontal sliding alone. Restoring those parts of the original code worked really well!

Strangely, though, the D2 Homing Missiles are now much easier to dodge in Rebirth than in the original engine. D2 Homing Missiles normally require pixel-perfect trichording, but in Rebirth, I can dodge them effortlessly with horizontal sliding alone. Here's a comparison (my frame rate in the original engine was stable between 28 and 32 FPS):

[homing_d2x_rebirth.zip](https://dl.dropboxusercontent.com/u/26944122/dxx_rebirth_issues/bomblets/homing_d2x_rebirth.zip)

I wonder why this is happening ... If I remember correctly, Retro applied the D1 homing behavior to D2 to avoid the weirdness of D2's original tracking cone - but Rebirth should be emulating D2 at 30 FPS now, right?

**Comment by zicodxx** [comment] 2016-10-10 00:59
I will check the D2 homers once again and see if I can find what's behind this. Thanks for supplying me with your demo. Maybe with that I can simulate a test case to bisect where it went wrong.

To be technical, the D1 tracking could be considered wrong. In D2, Parallax tried to fix those issues which would have resulted in the missiles becoming even harder to dodge which in turn was why the tracking cones were adjusted. In any regard, Rebirth *should* accurately simulate the original behavior of both games individually at 30 FPS. 

In practice (and trivially spoken), the D1 homing missiles turn sharper but you shake the lock easier while the D2 homers are easier to dodge but they re-acquire their locks easier - at least that is how they should behave according to the source and how I remember it. 

I can't imagine what I may have overseen here. But then again, I will need to find out and test for myself. Will report back when I find something.

**Comment by zicodxx** [comment] 2016-10-10 12:27
Question @ryusei117: In which difficulty mode were these demos recorded? The demo system itself doesn't record that.

**Comment by zicodxx** [comment] 2016-10-10 13:47
ALRIGHT! This was actually embarrassingly easy but I got a bit blind over time here. I pushed 407805be429fe7d3caeee4ba9b3246cfee951304 which will fix the issue.

So the thing is that the tracking cone for discovering new 'victims' was intended to be scaled according to which FPS setting the game runs to. This scaling was extremely crude isn't didn't scale well... at all. When I added the fixed homers, I took the scaling result for 30 FPS and made it fixed, too. However I took this result from Descent 1 and after I added it as a definition, I completely forgot about it.

What I did is not only restore the result for Descent 2 but I also added a function that re-creates this original scaling. For our fixed homers (i.e. NEWHOMER) this result will always be the same so it won't matter which FPS you run at.

But if you would compile without NEWHOMER or change the HOMING_TURN_TIME (i.e. 'homers as on XX FPS') this function will properly return the intended scaling result.

Of course my game speed differed slightly from yours, @ryusei117. As soon as you hit 32 FPS, the scaling result changes. Which is most likely why I could not see this issue so easy when comparing Rebirth to the original engine.

**Comment by ryusei117** [comment] 2016-10-11 22:02
Awesome, this sounds great! I'll have to test the latest changes soon - and this time I'll try to ensure my frame rate never hits 32 FPS in original D2. All of the demos I've posted are on Insane, by the way.

**Comment by ryusei117** [comment] 2016-10-21 09:22
Confirmed fixed: the D2 Homers now feel as spot-on as the D1 Homers. Thanks a bunch! And yeah, the change in the tracking cone at 32 FPS seemed pretty subtle - one of those things I wouldn't have noticed without knowing to watch for it.

**Comment by zicodxx** [comment] 2016-10-21 16:41
Thanks for the confirmation. Yes, I definitely wanted to mention it since it was on my CPU rather easy to hit the 32 FPS limit and while D1 never changes the tracking cone anymore above 16 FPS, D2 introduced another limit at this point. So I thought for your tests this may have cleared some unexplainable details. 

But I'm happy the homers work as intended now (at least from how the original code worked). Closing the issue for now. If something comes up again, feel free to open another issue, please. I think I am pretty much done now and the code is historically accurate but then again, this is not the first time I think that. :)

**Closed by zicodxx** 2016-10-21 16:41 UTC
