### ISSUE TITLE
Mouse disabled at start of level

### ISSUE THREAD

**Issue by goodtimefamilyband** [dxx-rebirth/dxx-rebirth#627] opened 2022-03-09 02:57 UTC
Downloaded today's release (0.61? 20220222?).  When starting a level, mouse control is disabled.  It can be re-enabled via the in-game options menu, but it becomes disabled again every time a new level is loaded, even if it is enabled in the game's main menu.

**Comment by vLKp** [comment] 2022-03-10 23:27
> even if it is enabled in the game's main menu

Do you mean that you enable the mouse, enter a new level, find the mouse does not work, open the menu, and find that the mouse is marked as enabled in the menu, contrary to it not actually working?  Or is the game clearing the `USE MOUSE` checkbox on its own?  The most likely explanation for the latter problem is that the game is unable to write its preferences file, so your changes are not saved.  Check to see if the user's home directory is mounted read-only, or otherwise unwritable.

Are _any_ player preferences saved across game restarts?

**Comment by vLKp** [comment] 2022-03-19 23:48
I cannot reproduce this here.  If you need support, please provide steps to reproduce.  Preferably, this would include filling out the issue reporting template that Github presents when filing a new issue.

**Comment by vLKp** [comment] 2022-04-12 03:08
No response from original reporter.  Not reproducible here.  Closing.  Please reopen and answer the questions above if this is still a problem for you.

**Closed by vLKp** 2022-04-12 03:08 UTC
