### ISSUE TITLE
Runtime bug: multiplayer co-op loads garbage values for 2nd player when loading save

### ISSUE THREAD

**Issue by jcotton42** [dxx-rebirth/dxx-rebirth#647] opened 2022-07-28 06:34 UTC
### Environment

DXX-Rebirth commit: cf51ac4ee03286618097229af911674e736116b3, date: 2022/05/22, downloaded from https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20220522-win.zip

#### Operating System Environment

Windows 11, version 22000.795

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Observed in both D1X-Rebirth in Descent: First Strike, and D2X-Rebirth in Descent 2: Counterstrike

Assets are from versions 1.5 and 1.2 of Descent and Descent II respectively
Descent.hog size: 6,856,701 bytes
Descent2.hog size: 7,595,079 bytes

### Description

Start a co-op game with primary, secondary, and accessory duplication set to `2`, and at least one other player. Load into the game, play for a bit, collect some powerups and weapons, and save. Load that save, and observe that the second player (i.e. not the host) has garbage values for things like laser level and missile counts.
![image](https://user-images.githubusercontent.com/5257450/181436366-d17a4655-69d8-4dd0-9aad-03385aca40e4.png)

Notice the illegal level of `80` for the laser and bombs. The count of 32 homing missiles is legal, but is not what Vaartok (the second player) had when we saved.
My weapons, as the host, save and restore fine.

Also, while not present in the screenshot, we have also observed nonsensical death counts, like `-130`, but again only for the second player, Vaartok (clipped to Vaart in the screenshot, perhaps their name is too long? entirely speculation on my part)

#### Regression status

This is the only build I've done co-op on, so I have no idea if this is a regression.

### Steps to Reproduce

See the description.

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [x] Multiplayer cooperative

* Players affected by issue:
  * [ ] Game host
  * [x] Game guests

**Comment by jcotton42** [comment] 2022-07-28 16:44
I neglected to attach the save file. I'll do that when I get home from work.

**Comment by vLKp** [comment] 2022-07-28 22:37
> clipped to Vaart in the screenshot, perhaps their name is too long?

Yes, there is some logic to clip names.  It is not particularly necessary on modern screens, but it dates back to the earliest code I can trace, so it was likely put in when 640x480 was considered "High Resolution".

As for the rest, I will need to examine it, and probably need to reproduce it locally.

**Comment by jcotton42** [comment] 2022-07-29 00:45
Here's the multiplayer save. Had to zip it so GitHub would let me attach it.
[save.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/9215085/save.zip)

**Comment by vLKp** [comment] 2022-07-29 14:28
Save games are saved on all systems, and are loaded back independently.  Since josh is the host and the guest is the problem, I need the other savegame - but before you collect it, I will try to reproduce here.

**Comment by raptor** [comment] 2022-07-30 20:00
I ran into this bug, too, and found it goes away if you do a 2nd reload. Seems to happen with any saved game. Our case kept giving the user LVL 139 laser.

Attached are the host saved game files (raptor) and one of the clients to which this happened. 

[host_client_pilot_files.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/9227487/host_client_pilot_files.zip)

**Comment by vLKp** [comment] 2022-08-02 21:57
That suggests data fields are restored in the wrong order, and that by rerunning the restore, the data from the first reload allows the second reload to succeed.

**Comment by jcotton42** [comment] 2022-09-09 23:53
> I ran into this bug, too, and found it goes away if you do a 2nd reload. Seems to happen with any saved game. Our case kept giving the user LVL 139 laser.

@raptor do you mean just loading the save twice? As in, start a multiplayer game, load the save, load it again?

Also, @vLKp, any update on this? Or anything I can do to help?

**Comment by raptor** [comment] 2022-09-10 02:02
@jcotton42 Yes. Reload the same game twice (and hope no one drops...)

**Comment by vLKp** [comment] 2022-09-10 03:38
No update.  I have been busy with other projects and have not had a block of time in which I can set up to reproduce this.  If you want to try to help, knowing specifically which variables are loaded in the wrong order would be useful - but you will need a debugger and the ability to step through the load process to test that.  Also, using a debugger in multiplayer tends to cause timeouts and drops, which makes debugging more difficult.  A modified build with very loose timeouts can help with that.

**Comment by vLKp** [comment] 2022-09-11 17:23
I reproduced the issue locally.  In poison-enabled builds, the effect was easy to see.  [Fix guest loading of multiplayer saved games](/dxx-rebirth/dxx-rebirth/commit/45362ac37b7313656df40a04e7cf741c2d13e245) resolved the problem for me.

Steps to reproduce:
- Start a cooperative game on `Descent 2: Counterstrike`, level 1.  Guest joins before entering the mine.  Host starts the game.  Once both the host and guest are in game, save.
- Exit that game.
- Start a new cooperative game on `Descent 2: Counterstrike`, level 10.  (Level 10 is not special.  Any level other than 1 should suffice, if the internal object numbers differ.)
- Once both host and guest are in game, load the saved game.
- In good builds, everything is fine.  In bad builds, various bad player data is observed.  When poison was enabled, the bad data consistently included an impossibly high level superlaser, as well as an invalid `Deaths` count.

The issue seems to have been caused by [Reuse pre-defined player objects when loading coop savestate to revent messup when player amount or orders change in a certain way](/dxx-rebirth/dxx-rebirth/commit/8cc22d8343efd9821518dcc4b2820a5fe08e641d), which forced the guest's object number to be reused even when the load moved from one level to another.  In the example above, the guest is object 16 on level 1, but object 29 on level 10.  The offending commit caused the guest to continue to be object 29 on the restored level 1, even though most of the guest's data was written to object 16.  Object 29 on level 1 is the PEST in the first lava hallway; the bad builds replaced that PEST with the guest's object, but retained some of the PEST's data, which was then interpreted as an impossible laser level.

Please sync and retest.  Since this was a fix on the load side, rather than the save side, I think existing savegames should load properly with the corrected build.

**Comment by jcotton42** [comment] 2022-09-11 18:55
Oh sweet.

@vLKp will you be uploading a binary release for this or should I build it locally to test?

**Comment by vLKp** [comment] 2022-09-11 19:08
I never upload prebuilt binaries.  Zico builds those for Windows.  The work in #652 added configuration files to make Github Actions build binaries for Windows/Linux/Mac, but it doesn't seem to work.  Github acts as if that work was never submitted, and so far, I have not found any logs explaining why it is ignored, nor any troubleshooting instructions that have led to any insights.

Building locally would be the simplest path.

**Comment by jcotton42** [comment] 2022-09-11 20:08
> Github acts as if that work was never submitted, and so far, I have not found any logs explaining why it is ignored, nor any troubleshooting instructions that have led to any insights.

It does see the workflows to some extent, at least what I can see from the Actions tab as a non-contributor
![image](https://user-images.githubusercontent.com/5257450/189546883-6010b0ae-8642-4637-8b98-267c45c0bb2f.png)

However, in all three workflow files the only trigger present is `workflow_dispatch`, which means someone with the necessary rights to the repo just needs to manually run the workflow from the Actions tab in the web UI. It looks like someone intended for this to be done automatically, based on the build/push to master triggers also being present, but those are commented out in the workflow definitions.

```yml
on:
  #push:
  #  branches: [ master ]

  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:
```

**Comment by vLKp** [comment] 2022-09-11 21:50
The yml files were entirely written by outside contributors, who seemed to understand Github Actions better than I do.  I reviewed them for any obvious errors (spelling, security, etc.), but trusted that they would work as intended.

On re-reading the original pull request now, I notice a line that agrees with your analysis.

https://github.com/dxx-rebirth/dxx-rebirth/pull/649#issue-1324641849 wrote:

> I set the packages to be manually triggered by a workflow run.

I likely read that text during my very first review, but failed to fully appreciate its implication.  Based on my limited understanding of Github Actions from attempting to read the documentation, I thought that the Actions would run automatically once merged, and that this line was about how the packaging would happen as a side effect of the workflow running.

---

Your explanation ties nicely with my original complaint about Github Actions: the files have too much magic for my taste, and the documentation is hard to read.  The name `workflow_dispatch` does not convey to me that this requires manual intervention.

Unfortunately, even if I try to trigger it manually, it doesn't work.  It creates a box with a spinner that spins forever, and nothing else happens.  No errors appear.  No workflow runs.

**Comment by jcotton42** [comment] 2022-09-11 22:21
I'll take a look at the actions workflows in a fork. I set them up for another repo of mine, so I'm decently comfortable with it.

If I find an issue I'll PR it.

**Comment by jcotton42** [comment] 2022-09-12 19:44
I forked the repo and ran the workflows. All 3 produced artifacts that appear to work (though the macOS artifact is x64-only, i.e. not native on Apple Silicon).
Though, something I've noticed, the Windows build from the wokflow has graphics and sound that are "crunchier", and the resolution screen is different? Is this just something's that changed since the binary release I'm using, or could it maybe be a result of the workflow using SDL2 instead of SDL1?
Workflow build
![image](https://user-images.githubusercontent.com/5257450/189736012-90e82ea3-c9bc-4e81-a57b-357339b0fe1f.png)
Binary build from site
![image](https://user-images.githubusercontent.com/5257450/189736077-d4e499cf-c820-4d94-8819-3aa62e25c5aa.png)

Actually, I tweaked the workflow to use SDL1, and while the original resolution menu returns, the menu graphics are still "jagged".

**Comment by jcotton42** [comment] 2022-09-12 20:49
Should note, when I said "work" I meant they started and loaded Lunar Outpost. I haven't had the opportunity to try the multiplayer fix, I will tonight.

**Comment by vLKp** [comment] 2022-09-12 22:59
>  the Windows build from the wokflow has graphics and sound that are "crunchier"

The sound may be issue #474.  There is a pending pull request (#651) that may make this better.  The author has not responded to my code review comments, so I will probably make the required fix-ups on that pull request myself.  I don't know why the graphics would differ.

The resolution screen is definitely an SDL1 vs SDL2 difference.

**Comment by vLKp** [comment] 2022-09-24 18:03
@jcotton42, were you able to test this in your environment?  Did it work correctly for you?

**Comment by jcotton42** [comment] 2022-09-24 19:25
@vLKp Sorry about the delay. I'll see if they have time tonight, and if not I'll just fire up two instances on the same or separate machines and test that way.

Both with the latest build on the site, and the one made by GitHub Actions.

**Comment by jcotton42** [comment] 2022-09-24 21:30
Did a quick local test with two instances. The fix appears to work.

Until a new binary build comes out, it also seems to work if you just make sure to start the co-op game on the level you saved at.

**Comment by vLKp** [comment] 2022-10-02 19:59
That is good to see.  Based on that feedback, I am closing this issue for now.  If you still see problems in the next binary build, please reopen or file a new issue so that they can be investigated.

**Closed by vLKp** 2022-10-02 19:59 UTC
Labels: bug
