### ISSUE TITLE
Stuck unable to move after spawning D1 Coop

### ISSUE THREAD

**Issue by DescentMax** [dxx-rebirth/dxx-rebirth#425] opened 2019-05-25 05:04 UTC
* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

Description: After death or moving on to the next level, Host randomly gets stuck at beginning of level. Can only rotate on the axis. Cant move forward backward left or right. 

Steps to Reproduce: Issue happens at random. Spawns fine after multiple deaths and randomly gets stuck when spawning again in D1 coop. Have to exit the game and reload. Suicide doesnt fix issue either

* Engines affected:
  * [X] D1X-Rebirth
  * [ ] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [X] Multiplayer cooperative

* Players affected by issue:
  * [X] Game host
  * [ ] Game guests
[gamelog.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/3219136/gamelog.txt)

**Comment by vLKp** [comment] 2019-05-25 19:05
This sounds familiar, but I think I fixed the prior cause of this.  If you save the game and reload, does the problem persist?  If so, could you post a savegame of the problem, so that I can review the internal state of the game?

**Comment by DescentMax** [comment] 2019-05-25 19:51
If we save the game, back out and reload the game, it goes back to normal, but it it happens at random. Whether you die from a bot killing you or if you spawn on the next level it happens at random. Whether the game is saved or not. We tested it with a saved game, and also without saving, still does the same. Sometimes we will go through a whole level without issues, but then starts acting up again.

**Comment by vLKp** [comment] 2019-05-25 22:26
Without steps to reproduce, or some view of the game's state, such as a savegame that reproduces the failure on load, I can't tell how it gets into this state or what to do to fix it.

**Comment by Johnsondr80** [comment] 2019-07-15 13:52
Gonna go on a limb here and state I've seen this before, it was a controller driver issue. Something to do with keybindings I suppose.
But the game just drops recognizing the buttons on the gamepad.
When this happens go to options and go to gamepad button assignments and try to reset them.
You will either reset them and move along, or you'll try and you'll press buttons but the game will not detect it.

**Comment by vLKp** [comment] 2019-07-28 20:52
Unable to reproduce.  Per comment from Johnsondr80, this _might_ be user error.  Closing.

Please reopen if you can reproduce this in a way I can work on it.

**Closed by vLKp** 2019-07-28 20:52 UTC
Labels: cannot-reproduce
