### ISSUE TITLE
Commit 487fed2fbd9646818b37e38b972b3930f165de4e changes keyboard behavior

### ISSUE THREAD

**Issue by wm4** [dxx-rebirth/dxx-rebirth#4] opened 2014-06-27 16:42 UTC
I've been on v0.55.1 for years, because the later versions (including 0.58.1) changed the keyboard behavior: they make the rotational acceleration too high (e.g. when turning). I can't play this way.

I know later versions add explicitly configurable keyboard sensitivity, but I haven't managed to tune back the old behavior.

Is it possible to get the old behavior back?

**Comment by zicodxx** [comment] 2015-08-29 13:52
Okay, I finally got around to take care about that. The issue is fixed in b5ac86c4f074e03c5d367531ba5e3419e955ba52. 

As stated before, the original game had a variable sensitivity which depends on the Framerate. I have adjusted the highest setting of the keyboard pitch and heading sensitivity to match 133.33 ms (give or take a few milliseconds) which should match the original game (and previous DXX-Rebirth versions) running at 60 FPS while the setting below matches a 30 FPS behavior.

**Closed by zicodxx** 2015-08-29 13:52 UTC
Labels: question

**Comment by wm4** [comment] 2015-08-29 17:16
I just tried it. You're saying the highest setting should match the behavior with 60 fps display fps in older versions? It doesn't feel this way. It's too fast.

(Also, loading is still much slower than older versions. When starting the program it shows the intro screen at least 4 seconds for no reason.)

**Comment by zicodxx** [comment] 2015-08-30 09:51
I did run checks against versions of Rebirth before this commit to check if it's matching up and Gameplay-wise I cannot really feel the difference - before nor after my commit. So I solved the issue with math. PH_SCALE - which was removed in the commit you mentioned, delays the input so it takes 8 frames for the ship to accelerate when rotating. So far 60 FPS, this should be 133.33ms (1000/(60/8)). The highest keyboard sensitivity setting now takes between 133-135ms (depending on the game timing) to speed up. 
The next lower sensitivity setting should definitely feel slower to you as you're used to as it speeds the ship in ~266-270ms which matches more a 30FPS behavior of older game versions. 
Since as I can - as mentioned before - not really feel the difference between the versions too well, I triple checked to make sure the values are correct. 
So if you still feel a difference, it may be related to your older versions do not run at exactly 60 FPS or the issue lies somewhere else. 

As for the intros: In Descent 1, the PARALLAX, INTERPLAY and Descent logo screes are shown 3 seconds, unless you skip them with any key. That is (as I tested) and should be the same in the current code base as well as older versions like 0.55.1.

**Comment by wm4** [comment] 2015-08-30 11:14
I'm very certain that at least the angular acceleration is still different. A single key tap changes the angle at least twice of what it did in older dxx versions. I couldn't test the angular velocity - newer dxx versions capture the mouse cursor, so I can't get the clock to show up.

>As for the intros: In Descent 1, the PARALLAX, INTERPLAY and Descent logo screes are shown 3 seconds, unless you skip them with any key. That is (as I tested) and should be the same in the current code base as well as older versions like 0.55.1.

OK, a hitting a key makes the menu show up immediately. But loading a level is still slower. Instant vs. takes at least 2 seconds.

**Comment by zicodxx** [comment] 2015-08-30 11:23
You can toggle the mouse capture off by disabling "Keep Mouse/Keyboard Focus" in the Controls menu. The focus will also be released automatically soon as you open a menu.

As for the loading screens, I added an artificial pause of one second for the "PREPARE FOR DESCENT" screen to keep the iconic message visible. This is just a change I added for nostalgic reasons as nowadays the game would load so fast, that you would not see it at all. If you compile the game using the debug argument, this pause will be disabled.

**Comment by wm4** [comment] 2015-08-30 11:40
OK, the angular velocity is exactly the same. If I keep pressing one arrow key, I can make 10 revolutions in 26 seconds, in both the old dxx version and dxx git.

So only the angular acceleration (plus maybe some delay?) is different.

>As for the loading screens, I added an artificial pause of one second for the "PREPARE FOR DESCENT" screen to keep the iconic message visible.

You could make it interruptible with a key, or cut it down to 1 second.

**Comment by zicodxx** [comment] 2015-12-14 14:39
I investigated further into the issue and there indeed still was a slight difference in how the keyboard ramp worked. I adjusted this and pushed another commit which should restore the original behavior as accurately as possible. Considering the fact that the original game sped up from 0 to 100 in a matter of 8 frames, this should result in a ramp of ~125ms to ~150ms for 60 FPS which should be reflected by the full sensitivity setting now. On 30FPS, results in a speedup of ~300ms which is now reflected by the middle sensitivity setting.

**Comment by wm4** [comment] 2015-12-25 14:51
Yes, that seems much better.

There still feels something wrong with it. Is it possible that the acceleration sliding is still lower? Not sure about forward/backwards movements. I have all keyboard sensitivity settings on maximum.

**Comment by Mako88** [comment] 2015-12-25 21:27
I've been busy visiting with family, but I'll be around basically all day
Monday-Thursday CST for testing and such :)

**Comment by wm4** [comment] 2017-12-03 05:38
Trying git master again, I still think sliding is slower. The sliding speed seems to be correct, but the acceleration (i.e. until you reach full speed) is faster on 0.55.1. Not sure about the rest. The angular acceleration is probably fine.

**Comment by vLKp** [comment] 2017-12-05 03:43
Could you quantify the difference?  At what FPS is each version run?  How many frames does it take for the ship to achieve full speed in each version?  Is the acceleration linear or uneven across that transition?

**Comment by wm4** [comment] 2017-12-05 03:49
Both run at 60 fps. Rest unknown and I don't know how to determine or measure it.

**Comment by vLKp** [comment] 2017-12-06 05:23
Both zicodxx and Matt1360 are on extended hiatus.  I started with Rebirth in the 0.57.2 timeframe, after the change you dislike.  I don't have any archived builds of v0.55.1.  The changes zico made 2 years ago seem, based on Matt's explanation, like the right solution.  If that is not sufficient for you, I need more details about what you think needs to be changed.  Quantifying the difference will likely require using builds instrumented to log ship movement during the acceleration.  Unfortunately, it's very likely you'll need to write the instrumentation twice, because the relevant code has almost certainly been changed in the ~8.7 years since the commit cited.

**Comment by wm4** [comment] 2017-12-06 05:37
If it helps, here's a repo with 0.55.1 made build able again: https://github.com/wm4/dxx-rebirth

**Comment by vLKp** [comment] 2017-12-08 05:15
That will probably be easier for you than using `gdb` to extract the required information, yes. :wink:  I don't understand from the comments posted so far exactly what needs to change.  I understand in a general sense that you object to the acceleration path of the player ship in one or more dimensions.  I think your objection is only to acceleration, but not maximum speed.  I can't measure the problem if I don't understand it.  The easiest way to fix this is for you to answer the [questions I posed above](#issuecomment-349186154).  You probably need instrumentation in the user input processing code to report before/after values from `Controls` for the fields relevant to ship acceleration.  Different fields are used for each of x/y/z motion.

**Comment by wm4** [comment] 2017-12-08 05:21
Yes, it's something about acceleration. I tested the maximum speed by flying across a long level with both versions, and in both it takes about the same time, which means there's probably no significant difference in speed.

But I really don't know how to "quantify" the acceleration. I can only "feel" how it behaves, and the maximum speed is reached too quickly as that I could actually test it manually.

**Comment by vLKp** [comment] 2017-12-12 05:28
Quantify it by giving me specific numbers.  For each version, state:

- FPS (stated above, but should be stated for the run where the quantified times are collected, which could differ from your comment above)
- Direction(s) flown: forward, backward, slide left, slide right, slide up, slide down; method of input producing flight (likely "keyboard"; if not keyboard, then report intensity of the input)
- Ship position each frame during flight
- Contents of `object::mtype.phys_info` for the ship for each frame during flight.  Omitting fields that never change is fine.

If you can't collect this, provide sufficiently detailed instructions that someone else can.  So far, you have not told me in what direction(s) you fly, on what level you did the test, or how far you flew.  I can easily envision several different test procedures that all conform to the vague information you have given, but at least some of them likely differ from what you intend.
