### ISSUE TITLE
D1 bosses in D2 escape from single walled-off cube before it opens

### ISSUE THREAD

**Issue by ef314159** [dxx-rebirth/dxx-rebirth#348] opened 2017-10-05 04:00 UTC
First off I really appreciate implementing the D1 boss AI in D2! Very helpful :)

As discovered in [this thread](http://www.descentbb.net/viewtopic.php?f=22&t=24044), any boss with the "Boss 1" AI will escape from a Red-Fatty-esque cube if it starts the game trapped in that cube, without the wall opening or the player doing anything to wake it up. I've also tested this in D1X-Rebirth and it definitely does not occur - the boss stays trapped in its cube.

I put a bunch of demos in that thread but the relevant demo/test mission is [here](https://mega.nz/#!INVUib6T!uxjQxqLUCePPgCEOzufUkQwC1BLzEf6NcK8xLe3RDbI). A Boss 1 is trapped behind a grate which is opaque on both sides - in the demo, it pops out, attacks, then happens to teleport back in (at which point I open up the wall).

You'll also see some rapid one-frame teleporting and firing. I'm told this is supposed to happen for D1's final boss but I've never witnessed it in Rebirth, and certainly not for Boss 1, so this is potentially a bug as well.

This all happens consistently both with the 0.60 BETA 1 from the [downloads page](http://www.dxx-rebirth.com/download-dxx-rebirth/) and the latest nightly.

**Comment by vLKp** [comment] 2017-10-06 02:12
Thank you for reporting this.  I do not read descentbb.net, as I had been led to believe there was no activity there.  The full explanation is in the commit message, but the summary version is:

- Descent 1 bosses always teleport, even when you're not present.  Since you're not present, you wouldn't see this and wouldn't know about it.  You can verify this with a breakpoint on `d1x::teleport_boss`.
- Descent 2 bosses only teleport when you're visible or they've been recently shot.  This prevents Red Fatty from escaping his cube early, since he can't see you or get shot until you open the cube.
- Descent 1 bosses only teleport into segments reachable from their starting segment.
- Descent 2 bosses follow that rule, unless there is only one segment reachable under that rule.  In that case, they add in everything reachable from the first segment beyond their starting segment.  This is why Red Fatty is able to teleport around his arena.
- When running D1X-Rebirth, Descent 1 bosses obey purely Descent 1 rules.
- When running D2X-Rebirth, Descent 1 bosses obey the Descent 1 rule for when to teleport, but the Descent 2 rule for where to teleport.  This allows them to start teleporting immediately, but also to break out of their starting segment when they teleport.  This is what caused the reported result.  I elected to fix this by switching Descent 1 bosses in both engines to the Descent 2 rule for when to teleport.  It could also have been fixed by restricting the Descent 2 rule for where to teleport not to expand the search when the boss is a Descent 1 boss.  I chose not to do that because I see no value in letting the boss teleport when the player is not present.  If you (or anyone else reading) disagree with this solution, I welcome an argument for why Descent 1 bosses should retain the always-teleport rule.

[Fix D2 emulation of D1 boss teleport handling](/dxx-rebirth/dxx-rebirth/commit/8291391b7f9f54f711e5d6b3df43c94732e35ba2) should resolve this.

**Comment by ef314159** [comment] 2017-10-06 03:54
Does this change the rapid-teleporting as well? I tried to compile using [these instructions](https://forum.dxx-rebirth.com/showthread.php?tid=857&pid=9850) and scons.py throws a syntax error so I can't test it myself.

That change sounds good! The main thing I can think of is if you're in a complex boss arena and far enough away that the boss doesn't see you, it couldn't teleport _to_ you and take you by surprise - whereas it potentially could in D1. But this seems like a small loss if it gives us the Red Fatty behavior.

I'm surprised that D1 bosses were permanently confined to a walled-off cube even after it opens. In that case, changing D1X-Rebirth's rules as well could break D1 maps that relied on that behavior - though I can't think of any that do. (My first thought was the final level of Vignettes but I just checked and that boss has a few cubes to move around in)

**Comment by vLKp** [comment] 2017-10-06 04:18
What is the syntax error?  The build works fine for me with SCons 2.4.1 and Python 2.7.12.

As for visibility, this is programmatic visibility, not rendered visibility.  Depending on the size and shape of the segments, and some details of the vector intersection logic, you might have a level where an object too far away to be rendered (or at least, too far away for the user to be able to perceive it as rendered) is still considered "visible" if there is an unobstructed straight line of sight to it.

Descent 1 bosses were confined because the game computes the list of allowed destinations when the boss is first initialized, not when the teleport happens.  Changes in level topology by opening/closing doors/walls do not trigger a rebuild of the list.  Descent 2 had a special case that, if the boss would be confined to a single cube, then the game would immediately rebuild the list, but pretend that cube had an open side.  This is clearly meant to make Red Fatty work despite starting in an enclosed area.  Descent 2 still does not recompute the allowed destination list when the topology changes.

I agree that it could change semantics Descent 1 maps that used a sealed starting area, but I expect such maps would not be used because it seems very limiting to have a boss confined to a single start cube and unable ever to teleport elsewhere.

Overall, this feels like an area where the level definition language needs to give the level author some flexibility to define the desired results (rebuild list on topology change or static?; allow reachable areas that the boss could not fly to?; teleport even when the player is hidden or only if seen?; etc.), rather than forcing one set of heuristics on all levels.  No such control is provided for rdl/rl2 files though.

**Comment by ef314159** [comment] 2017-10-06 04:45
Indeed, letting map authors tweak game rules would be very useful - possibly via a text file like "mapname.cfg" (or whatever extension might be appropriate) to go alongside the .pogs and .hxms. Personally I'd love an option to restore a D1-like homing rate as well. But setting all that up would probably be a fairly large undertaking, I'm certainly not requesting it :)

There was a syntax error in dxx-rebirth\SConstruct on like line 15 or so, but I was using SCons 3.0.0 (with Python 2.7.12). I found/installed 2.4.1 and now I get this:

>Shivanhunter@Neumann MINGW64 ~/dxx-rebirth (master)
$ scons.py
scons: Reading SConscript files ...
===== D1X-Rebirth v0.59.100 0.59.100-699-g8291391b7f9f =====
===== D2X-Rebirth v0.59.100 0.59.100-699-g8291391b7f9f =====
AttributeError: 'module' object has no attribute 'uname':
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 4684:
    main(register_program)
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 4657:
    ''.join(['%s:\n%s' % (d.program_message_prefix, d.init(substenv)) for d in dxx])
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 4315:
    DXXProgram.static_archive_construction[user_settings.builddir] = archive = DXXArchive(user_settings)
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 3989:
    self.prepare_environment()
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 3725:
    env = self.env
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 2546:
    d[name] = r = self.method(instance)
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 3840:
    platform_settings = self.platform_settings
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 2546:
    d[name] = r = self.method(instance)
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 3829:
    message(self, "compiling on %r/%r for %r into %s%s" % (sys.platform, os.uname()[4], platform_name, self.user_settings.builddir or '.',

>Shivanhunter@Neumann MINGW64 ~/dxx-rebirth (master)
$

**Comment by vLKp** [comment] 2017-10-07 00:58
> Does this change the rapid-teleporting as well?

Not specifically.  I modified the Descent 1 boss handler to act much more like the Descent 2 boss handler.  This restricts Descent 1 bosses in both engines to teleport only when the the player is visible or the boss is attacked.  It might change the rapid-teleport behavior if that was a bug in Descent 1 that was fixed in Descent 2.  The Descent 2 handler, but not the Descent 1 handler, had what what I believe to be workarounds to timing bugs (caused by not tracking timing data properly, then trying to correct for it later).  I modified the Descent 1 handler to include those same workarounds, as this is not the first time I have seen code present in Descent 2 that looks like it should have been backported to Descent 1.

> I'm surprised that D1 bosses were permanently confined to a walled-off cube even after it opens. In that case, changing D1X-Rebirth's rules as well could break D1 maps that relied on that behavior - though I can't think of any that do.

D1X-Rebirth still follows the Descent 1 rule for choosing boss teleport destinations.  D2X-Rebirth still follows the Descent 2 rule.  Both games set their list at boss initialization time and do not update it for topology changes.  Descent 2 had the the special case to make Red Fatty work despite this lack of update.  My change only changes when Descent 1 bosses will teleport, not where they go.

> Personally I'd love an option to restore a D1-like homing rate as well.

I think this is the single most common change request.  Nobody can agree on when it's right, so everyone always wants it changed.

> There was a syntax error in dxx-rebirth\SConstruct on like line 15 or so, but I was using SCons 3.0.0 (with Python 2.7.12).

Could it have been line 17?  Line 15 is blank.

https://github.com/dxx-rebirth/dxx-rebirth/blob/master/SConstruct#L15-L17

That line would break if the interpreter tried to use Python 3 print_function rules instead of Python 2 print keyword rules.  If so, that is easy to fix.

> now I get this:
> ```
> AttributeError: 'module' object has no attribute 'uname':
>    message(self, "compiling on %r/%r for %r into %s%s" % (sys.platform, os.uname()[4], platform_name, self.user_settings.builddir or '.',
> ```

Although I build for Windows as part of my testing, I never use Windows as my host platform.  `os.uname` works on POSIX systems and is absent on Windows.  I thought it would available on Windows, but on rereading the documentation, I see that the documentation says `os.uname` is available for `recent flavors of Unix`.  It is easy to fix, since this is only used for an informational message, but it is a bit disappointing.  I added that line in early June and you are the first person to report it, which suggests nobody has tried to use Windows as a build host since then.

Please sync and retry.  I pushed two commits to address the build script errors you described.

**Comment by ef314159** [comment] 2017-10-07 01:38
lol indeed, I've read about all the headaches re: homing rate. Tbh the biggest issue for me is actually the ability to hold doors open with markers - would be great to turn that off in a D2 map.

It was probably line 17.

I'm getting a different error now:

> $ scons.py
scons: Reading SConscript files ...
===== D1X-Rebirth v0.59.100 0.59.100-701-gd0f709381dbc =====
===== D2X-Rebirth v0.59.100 0.59.100-701-gd0f709381dbc =====
DXX-Archive.3: compiling on 'win32'/None for 'win32' into .
DXX-Archive.3: checking version of C++ compiler 'g++' ... 'g++ (MinGW.org GCC-6.3.0-1) 6.3.0'
DXX-Archive.3: checking path to assembler ... 'c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/as.exe'
DXX-Archive.3: checking version of assembler 'c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/as.exe' ... 'GNU assembler (GNU Binutils) 2.28'
DXX-Archive.3: checking path to linker ... 'c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe'
DXX-Archive.3: checking version of linker 'c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe' ... 'GNU ld (GNU Binutils) 2.28'
DXX-Archive.3:  CXX: 'g++'
DXX-Archive.3:  CPPDEFINES: ['_WIN32', 'WIN32_LEAN_AND_MEAN']
DXX-Archive.3:  CPPPATH: ['common/include', 'common/main', '.', '']
DXX-Archive.3:  CPPFLAGS: ['-Wno-sign-compare']
DXX-Archive.3:  CXXFLAGS: ['-g', '-O2', '-ftabstop=4', '-Wall', '-Wshadow', '-Werror=extra', '-Werror=format=2', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=redundant-decls', '-Werror=vla', '-funsigned-char']
DXX-Archive.3:  LIBS: None
DXX-Archive.3:  LINKFLAGS: ['-mwindows']
DXX-Archive.3:  RCFLAGS: []
DXX-Archive.3:  $CCACHE_PREFIX: None
DXX-Archive.3:  $DISTCC_HOSTS: None
DXX-Archive.3: checking whether C++ compiler and linker work...yes
DXX-Archive.3: checking whether C++ compiler accepts -std=gnu++14...yes
DXX-Archive.3: checking endian to use...little
DXX-Archive.3: checking whether to enable word alignment fixups...no
DXX-Archive.3: building with OpenGL
DXX-Archive.3: checking whether to enable release options...yes
DXX-Archive.3: checking whether to enable memory allocation tracking...no
DXX-Archive.3: checking whether to enable level editor...no
DXX-Archive.3: checking whether to enable IPv6 support...no
DXX-Archive.3: checking whether to enable multiplayer over UDP...yes
DXX-Archive.3: checking whether to enable UDP game tracker...yes
DXX-Archive.3: checking whether to define _WIN32_WINNT...yes, define _WIN32_WINNT=0x600
DXX-Archive.3: checking whether to enable minidump on exception...yes
DXX-Archive.3: checking for usable header dbghelp.h...no
DXX-Archive.3: checking for parseable header dbghelp.h...no
scons: *** Header dbghelp.h is missing or unusable.  Upgrade the Windows API header package or disable minidump support.  See sconf.log for details.  Stop.

[Here](https://github.com/dxx-rebirth/dxx-rebirth/files/1364201/sconf.log)'s the log which says the file doesn't exist. I'm not familiar with MinGW/SCons/any of this workflow but this seems like a problem in MinGW. Can I get dbghelp.h from somewhere?

**Comment by vLKp** [comment] 2017-10-07 23:47
I edited your latest comment to apply block formatting (similar to an older one above).  This issue is now veering substantially off the topic of boss problems.

Your build error is because your build environment lacks a usable `dbghelp.h`.  Yes, this is a problem in MinGW.  This header is normally provided by the MinGW runtime, which is variously packaged as `w32api` or `mingw-runtime`.  I see it present in both the 3.0.0 and 5.0.0 release lines from http://mingw-w64.sourceforge.net/ mingw64-runtime.  If you do not need minidump support, you can disable it to skip that test.  Set `windows_minidump=0` on the SCons command line.

**Comment by ef314159** [comment] 2017-10-08 01:36
I'm now getting "SDL pkg-config failed". I'd ask about this in the Rebirth forum thread if they'd sent me an activation email a week and a half ago.

Never mind anyway, I'll just wait for the next build to come out. It'll be a while before I want to actually work with this. I'll just assume the rapid teleporting is fixed since none of the D2 bosses do it - if the D1 bosses are now using D2 rules I don't see why it would still happen.

**Comment by vLKp** [comment] 2017-10-08 17:23
Due to some historical organizational quirks, I am the primary administrator for the Github site of the project, but have no administrative involvement in the Rebirth forums.  Conversely, the administrators for the forums have no administrative flags here.  We all get along, but changing that situation has never mattered.

You can get support here or there, but I would prefer not to conflate bug report threads (as this one started) with threads about specific build environments (as this has now become).   Ideally, I would move your environment-support posts (and my responses to them) into a separate issue, but as far as I can tell, Github does not support splitting existing threads.  If I am wrong on this point, a link to their instructions would be appreciated.

@Mako88: can you investigate his problem with the Rebirth forum?

@ef314159: if you want to pursue help here, please open a separate issue.  If you want to pursue the forum, please indicate the account name you requested there.  I see 4 not-yet-activated accounts, but none are obviously yours.  Taking your "week and a half ago" fairly literally as ~10 days, that would suggest you registered on September 27 or September 28; the only forum account for those days is [ShivanHunter](https://forum.dxx-rebirth.com/member.php?action=profile&uid=623).

I know @Mako88 regularly builds *for* Windows, so it should be possible (although we also now know that nobody regularly builds *from* Windows, since that had been broken for several months and never reported).

**Comment by ef314159** [comment] 2017-10-09 03:43
I never intended to derail the topic - I originally just mentioned I couldn't test the new behavior. I'll start a new issue for the Windows build problems since I assume other people will have some of the same issues if they're following the forum instructions.

Yes, Shivanhunter is me (and one of the others also said on DBB that he was having problems with the Rebirth forum's activation email).

**Comment by vLKp** [comment] 2017-10-10 01:52
> I never intended to derail the topic

I understand.  My concern is that your failure to build is not only not caused by the changes here, but is likely a local environment issue.  As such, future readers who want to follow this issue, particularly if they disagree in how it was handled, would likely prefer to skip over the comments dealing with your environment issue.

> one of the others also said on DBB that he was having problems with the Rebirth forum's activation email

Interesting.  Perhaps it broke when it was migrated from zico's server to its current home.  Back when I registered, the mail arrived almost immediately.  Even one day's delay seems wrong to me.

**Comment by vLKp** [comment] 2017-10-26 04:18
The original issue reported here was fixed.  Related issue #349 is also fixed.  Closing.  Please reopen if you observe incorrect teleporting from bosses.

**Closed by vLKp** 2017-10-26 04:18 UTC
