### ISSUE TITLE
Co-Op Missile View is always enabled

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#124] opened 2015-09-21 03:39 UTC
In Co-Op in D2 if anyone fires a missile, it appears in everyone's missile view box.

**Comment by vLKp** [comment] 2015-09-22 01:34
This is a feature, not a bug.  If your own missile view fails to override the missile borrowed from someone else, *that* would be a bug.  This was added in [Watch missiles when available](/dxx-rebirth/dxx-rebirth/commit/32b9202e1f5443a32b59ac3a8808f5555d14600f).

**Comment by zicodxx** [comment] 2015-09-22 11:13
I am not sure but I think it would be easy enough for this to be either a player- or even host-decided option. 
[_] Allow team/coop missile views
I'm jus tnot sure if this should be player decided or rather be set globally by host.

**Comment by Mako88** [comment] 2015-09-22 13:37
I think this makes sense to be a player-set option, since it only affects team games, so therefore there's no advantage given to the player (so the host doesn't have to set it).

**Comment by vLKp** [comment] 2015-09-26 22:01
@zicodxx made this configurable in [Made missile views from friendly players optional (off by default)](https://github.com/dxx-rebirth/dxx-rebirth/commit/69353631f07aa1d2ebf2b0bc7ec87371c2eb5e7c), then I converted it into a radio button and folded the preference storage in [Store FriendMissileView inside MissileViewEnabled](https://github.com/dxx-rebirth/dxx-rebirth/commit/230bc630ed0ca8c08c91931630c82f1c71400c16).

**Comment by zicodxx** [comment] 2015-09-27 08:56
That definitely makes more sense. Thanks. Closing.

**Closed by zicodxx** 2015-09-27 08:56 UTC
Labels: enhancement
