### ISSUE TITLE
Warnings During Compile

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#116] opened 2015-08-18 20:40 UTC
First of all...hello, I'm back! At the very least I'll be updating the installer and the beta builds. I may or may not be able to do any actual coding, but we'll see how things go :)

While compiling I'm getting the following warning on almost every file:

`warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘std::size_t {aka unsigned int}’`

**Comment by vLKp** [comment] 2015-08-19 02:44
Confirmed, but only for mingw32 target.  Most platforms use `typedef unsigned long size_t;` or equivalent.

I build with `-Werror`, so if a warning appears in published code, it is in a target that I did not test.  Please always indicate what target you built and include the warning message as printed.  Your report hid the file+line number, so I had to find an affected target to see where the warning was generated.

Fixed in [Cast valptridx size_t to unsigned long for Windows](/dxx-rebirth/dxx-rebirth/commit/fcfd3d7e54d2838f2906dadeaa3b827faa57fa1f).

**Closed by vLKp** 2015-08-19 02:44 UTC

**Comment by MaddTheSane** [comment] 2016-08-20 14:35
It looks like there's a printf format specifier known as `%zu`. It's available on gcc, Clang, and under Visual Studio 2015 for Windows. It should be available for Windows using mingw, as it uses gcc.

**Comment by vLKp** [comment] 2016-08-20 16:00
You know this ticket has been closed for just over a year, right? ;)

I am aware of that specifier, but avoided it because, as I understand it, it is **not** available for Windows.  `z` is part of C99, which Microsoft long resisted supporting fully.  They may finally support it in the latest iteration of their compiler, but historically mingw linked to an older version of the Microsoft CRT that does not have it.  I do not know if mingw now uses a CRT new enough to understand `z`, but I doubt it, since the reason for avoiding the newer ones was related to Microsoft licensing problems.  If you have a specific citation for the minimum mingw version that uses a Microsoft CRT that understands `z`, I would appreciate it.  As far as I know, it is not possible even with the latest version to use mingw's preferred Microsoft CRT and get support for this specifier.

If you look at the latest code, you will see that I have a different approach to handling `size_t` now, driven mainly by the weird interactions of mingw's format string checking with the limited capabilities of the old Microsoft CRT.  I have an SConf test that probes for format specifiers that the compiler will accept without error for `size_t`, picking the first of `z`, `l`, `I64`, and none.  The addition of `-Wuseless-cast` required cleaning up format string usage, which was overall a nice improvement.  I am a bit surprised that the successor of the change I made for this ticket did not trigger a useless cast warning.

**Comment by MaddTheSane** [comment] 2016-08-20 17:30
Ah, I just remember the topic of size_t coming up recently. Probably on an older ticket.
On Aug 20, 2016, at 10:00 AM, vLKp <notifications@github.com<mailto:notifications@github.com>> wrote:


You know this ticket has been closed for just over a year, right? ;)

I am aware of that specifier, but avoided it because, as I understand it, it is not available for Windows. z is part of C99, which Microsoft long resisted supporting fully. They may finally support it in the latest iteration of their compiler, but historically mingw linked to an older version of the Microsoft CRT that does not have it. I do not know if mingw now uses a CRT new enough to understand z, but I doubt it, since the reason for avoiding the newer ones was related to Microsoft licensing problems. If you have a specific citation for the minimum mingw version that uses a Microsoft CRT that understands z, I would appreciate it. As far as I know, it is not possible even with the latest version to use mingw's preferred Microsoft CRT and get support for this specifier.

If you look at the latest code, you will see that I have a different approach to handling size_t now, driven mainly by the weird interactions of mingw's format string checking with the limited capabilities of the old Microsoft CRT. I have an SConf test that probes for format specifiers that the compiler will accept without error for size_t, picking the first of z, l, I64, and none. The addition of -Wuseless-cast required cleaning up format string usage, which was overall a nice improvement. I am a bit surprised that the successor of the change I made for this ticket did not trigger a useless cast warning.
