### ISSUE TITLE
Windows build guesses unusable path for pkg-config

### ISSUE THREAD

**Issue by ef314159** [dxx-rebirth/dxx-rebirth#349] opened 2017-10-09 04:14 UTC
(Continued from discussion [here](https://github.com/dxx-rebirth/dxx-rebirth/issues/348))

The build instructions from [This thread](https://forum.dxx-rebirth.com/showthread.php?tid=857&page=3) seem to be outdated - at least, Scons needs to be version 2.4.1 rather than the current production version (3.0.0).

There was another error about a lack of "dbghelp.h" which is supposed to exist in the w32api package (which I seem to have - "mingw32-w32api" is checked in my installation manager, version 5.0.1). 

If I disable minidump support by using windows_minidump=0, I get this error:

```
$ scons.py windows_minidump=0
scons: Reading SConscript files ...
===== D1X-Rebirth v0.59.100 0.59.100-701-gd0f709381dbc =====
===== D2X-Rebirth v0.59.100 0.59.100-701-gd0f709381dbc =====
DXX-Archive.3: compiling on 'win32'/None for 'win32' into .
DXX-Archive.3: checking version of C++ compiler 'g++' ... 'g++ (MinGW.org GCC-6.3.0-1) 6.3.0'
DXX-Archive.3: checking path to assembler ... 'c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/as.exe'
DXX-Archive.3: checking version of assembler 'c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/as.exe' ... 'GNU assembler (GNU Binutils) 2.28'
DXX-Archive.3: checking path to linker ... 'c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe'
DXX-Archive.3: checking version of linker 'c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe' ... 'GNU ld (GNU Binutils) 2.28'
DXX-Archive.3:  CXX: 'g++'
DXX-Archive.3:  CPPDEFINES: ['_WIN32', 'WIN32_LEAN_AND_MEAN']
DXX-Archive.3:  CPPPATH: ['common/include', 'common/main', '.', '']
DXX-Archive.3:  CPPFLAGS: ['-Wno-sign-compare']
DXX-Archive.3:  CXXFLAGS: ['-g', '-O2', '-ftabstop=4', '-Wall', '-Wshadow', '-Werror=extra', '-Werror=format=2', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=redundant-decls', '-Werror=vla', '-funsigned-char']
DXX-Archive.3:  LIBS: None
DXX-Archive.3:  LINKFLAGS: ['-mwindows']
DXX-Archive.3:  RCFLAGS: []
DXX-Archive.3:  $CCACHE_PREFIX: None
DXX-Archive.3:  $DISTCC_HOSTS: None
DXX-Archive.3: checking whether C++ compiler and linker work...yes
DXX-Archive.3: checking whether C++ compiler accepts -std=gnu++14...yes
DXX-Archive.3: checking endian to use...little
DXX-Archive.3: checking whether to enable word alignment fixups...no
DXX-Archive.3: building with OpenGL
DXX-Archive.3: checking whether to enable release options...yes
DXX-Archive.3: checking whether to enable memory allocation tracking...no
DXX-Archive.3: checking whether to enable level editor...no
DXX-Archive.3: checking whether to enable IPv6 support...no
DXX-Archive.3: checking whether to enable multiplayer over UDP...yes
DXX-Archive.3: checking whether to enable UDP game tracker...yes
DXX-Archive.3: checking whether to define _WIN32_WINNT...yes, define _WIN32_WINNT=0x600
DXX-Archive.3: checking whether to enable minidump on exception...no
DXX-Archive.3: checking for usable library physfs...yes
DXX-Archive.3: checking SDL pkg-config sdl
DXX-Archive.3: using pkg-config at discovered path C:\MinGw\bin\pkg-config.exe
DXX-Archive.3: reading SDL settings from `C:\MinGw\bin\pkg-config.exe --cflags --libs sdl`
DXX-Archive.3: SDL settings: {'LIBS': ['mingw32', 'SDLmain', 'SDL'], 'LINKFLAGS': ['-mwindows'], 'CPPDEFINES': [['_GNU_SOURCE', '1'], ['main', 'SDL_main']], 'CPPPATH': ['C:/Git/mingw64/include/SDL'], 'LIBPATH': ['C:/Git/mingw64/lib']}
DXX-Archive.3: reading sdl version from `C:\MinGw\bin\pkg-config.exe --modversion sdl`
DXX-Archive.3: SDL pkg-config failed; using default flags for `C:\MinGw\bin\pkg-config.exe --cflags --libs sdl`: {'LIBS': ['SDL']}
DXX-Archive.3: checking whether to enable joystick support...yes
DXX-Archive.3: checking for usable library SDL with OpenGL...no
DXX-Archive.3: checking for usable header SDL.h...no
DXX-Archive.3: checking for parseable header SDL.h...no
DXX-Archive.3: checking for parseable header SDL.h...no
DXX-Archive.3: checking for usable library SDL without OpenGL...no
DXX-Archive.3: checking for usable header SDL.h...no
DXX-Archive.3: checking for parseable header SDL.h...no
DXX-Archive.3: checking for parseable header SDL.h...no
scons: *** Header SDL.h is missing or unusable.  See sconf.log for details.  Stop.
```

[Here](https://github.com/dxx-rebirth/dxx-rebirth/files/1367476/sconf.log)'s the sconf.log. I should mention that "C:/Git/mingw64/include/SDL/SDL.h" does indeed exist, as does everything I copied in steps 16 and 17. I have pkg-config.exe in D:\MinGW\bin and 
[sdl.pc](https://github.com/dxx-rebirth/dxx-rebirth/files/1367485/sdl.txt) (.txt here since GitHub doesn't recognize the .pc extension) in C:\Git\mingw64\lib\pkgconfig.

**Comment by vLKp** [comment] 2017-10-10 01:52
SCons 2.4.1 was current when those instructions were written.  For me, SCons 2.x still is current (although 3.x is available, it isn't needed by anything I use, so I haven't taken that upgrade yet).  Rereading those instructions reminds me just how thankful I am that distribution packagers handle prerequisites for me.  I got started with Rebirth by asking the package manager to install its dependencies and it handled fetching/unpacking/installing everything in the right places.  Windows users have it rough.  Getting back on topic...

I don't know what installation manager you used, nor where it gets its headers.  I can tell you that `w32api` from www.mingw.org seems not to have it, but that the `mingw64-runtime` package from the mingw64 project does have it for both the x86_64-w64 and i686-w64 targets.  As I understand it, mingw64 forked off to work on x86_64 support, but also maintains an x86 support package parallel to the mingw32 project.  I have seen some claims that the mingw64 project is more active and more useful.  I have not evaluated those claims.

Your specific error is interesting.  `pkg-config --cflags --libs sdl` works and gets useful results, but then `pkg-config --modversion sdl` fails.  That latter failure raises an exception that then skips over using the results from the former call, so SCons then tries to use only the guessed defaults for SDL.  This is probably not a good way to handle it, but this is the first time I've heard of an environment where the flags are acquired successfully and modversion fails.  In every other case, either both fail because of a serious installation problem (missing SDL or missing pkg-config), or both succeed.  I'll look at rearranging this.

This marks the second time that an informational-only step has failed for you.  Does running `C:\MinGw\bin\pkg-config.exe --modversion sdl` from the command line work?  It should respond with a single line containing the version number of your installed SDL and should have an exit code of success.  If it works from the command line, what is different about when SCons runs it?  You may need to use the Windows equivalent of `strace` to check this.  Alternately, you could apply the below patch and re-run.  It will fail, but should fail in a more informative manner.  When it fails, post the console output here.

```diff
diff --git a/SConstruct b/SConstruct
index e8689dd34..43280e3ee 100644
--- a/SConstruct
+++ b/SConstruct
@@ -346,6 +346,7 @@ class ConfigureTests(_ConfigureTests):
 				except OSError as o:
 					Display("%s: %s pkg-config failed; using default flags for `%s`: %r\n" % (message, display_name, cmd, guess_flags))
 					flags = guess_flags
+					raise
 				_cache[cmd] = flags
 				return flags
 
```

@Mako88: ef314159 has some amendments to your install instructions.  Once we sort out his environment issues, the instructions thread may need an update.

**Comment by ef314159** [comment] 2017-10-10 07:23
Alright, I dunno where to get the right MinGW but it doesn't matter now - but that should probably be added to the build instructions as well as the old Scons version.

About the sdl thing: I ran `C:\MinGw\bin\pkg-config.exe --modversion sdl` in cmd and got an error about PKG_CONFIG_PATH. So I added that variable, set to `C:\Git\mingw64\lib\pkgconfig`, and now when I run `C:\MinGw\bin\pkg-config.exe --modversion sdl`, I get "1.2.15".

But it still fails in Git Bash.

Here's the error with your diff:
```
$ scons.py windows_minidump=0
scons: Reading SConscript files ...
===== D1X-Rebirth v0.59.100 0.59.100-701-gd0f709381dbc* =====
===== D2X-Rebirth v0.59.100 0.59.100-701-gd0f709381dbc* =====
DXX-Archive.3: compiling on 'win32'/None for 'win32' into .
DXX-Archive.3: checking version of C++ compiler 'g++' ... 'g++ (MinGW.org GCC-6.3.0-1) 6.3.0'
DXX-Archive.3: checking path to assembler ... 'c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/as.exe'
DXX-Archive.3: checking version of assembler 'c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/as.exe' ... 'GNU assembler (GNU Binutils) 2.28'
DXX-Archive.3: checking path to linker ... 'c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe'
DXX-Archive.3: checking version of linker 'c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe' ... 'GNU ld (GNU Binutils) 2.28'
DXX-Archive.3:  CXX: 'g++'
DXX-Archive.3:  CPPDEFINES: ['_WIN32', 'WIN32_LEAN_AND_MEAN']
DXX-Archive.3:  CPPPATH: ['common/include', 'common/main', '.', '']
DXX-Archive.3:  CPPFLAGS: ['-Wno-sign-compare']
DXX-Archive.3:  CXXFLAGS: ['-g', '-O2', '-ftabstop=4', '-Wall', '-Wshadow', '-Werror=extra', '-Werror=format=2', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=redundant-decls', '-Werror=vla', '-funsigned-char']
DXX-Archive.3:  LIBS: None
DXX-Archive.3:  LINKFLAGS: ['-mwindows']
DXX-Archive.3:  RCFLAGS: []
DXX-Archive.3:  $CCACHE_PREFIX: None
DXX-Archive.3:  $DISTCC_HOSTS: None
DXX-Archive.3: checking whether C++ compiler and linker work...yes
DXX-Archive.3: checking whether C++ compiler accepts -std=gnu++14...yes
DXX-Archive.3: checking endian to use...little
DXX-Archive.3: checking whether to enable word alignment fixups...no
DXX-Archive.3: building with OpenGL
DXX-Archive.3: checking whether to enable release options...yes
DXX-Archive.3: checking whether to enable memory allocation tracking...no
DXX-Archive.3: checking whether to enable level editor...no
DXX-Archive.3: checking whether to enable IPv6 support...no
DXX-Archive.3: checking whether to enable multiplayer over UDP...yes
DXX-Archive.3: checking whether to enable UDP game tracker...yes
DXX-Archive.3: checking whether to define _WIN32_WINNT...yes, define _WIN32_WINNT=0x600
DXX-Archive.3: checking whether to enable minidump on exception...no
DXX-Archive.3: checking for usable library physfs...yes
DXX-Archive.3: checking SDL pkg-config sdl
DXX-Archive.3: using pkg-config at discovered path C:\MinGw\bin\pkg-config.exe
DXX-Archive.3: reading SDL settings from `C:\MinGw\bin\pkg-config.exe --cflags --libs sdl`
DXX-Archive.3: SDL settings: {'LIBS': ['mingw32', 'SDLmain', 'SDL'], 'LINKFLAGS': ['-mwindows'], 'CPPDEFINES': [['_GNU_SOURCE', '1'], ['main', 'SDL_main']], 'CPPPATH': ['C:/Git/mingw64/include/SDL'], 'LIBPATH': ['C:/Git/mingw64/lib']}
DXX-Archive.3: reading sdl version from `C:\MinGw\bin\pkg-config.exe --modversion sdl`
DXX-Archive.3: SDL pkg-config failed; using default flags for `C:\MinGw\bin\pkg-config.exe --cflags --libs sdl`: {'LIBS': ['SDL']}
WindowsError: [Error 2] The system cannot find the file specified:
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 4689:
    main(register_program)
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 4662:
    ''.join(['%s:\n%s' % (d.program_message_prefix, d.init(substenv)) for d in dxx])
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 4320:
    DXXProgram.static_archive_construction[user_settings.builddir] = archive = DXXArchive(user_settings)
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 3996:
    self.configure_environment()
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 4023:
    getattr(conf, k.name)()
  File "C:\Python27\Lib\site-packages\scons-2.4.1\SCons\SConf.py", line 669:
    ret = self.test(context, *args, **kw)
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 1124:
    check_libSDL(context)
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 1130:
    self._check_libSDL(context, '', _guess_flags)
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 1138:
    successflags = self.pkgconfig.merge(context, self.msgprefix, user_settings, 'sdl%s' % sdl2, 'SDL%s' % sdl2, guess_flags).copy()
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 343:
    v = StaticSubprocess.qcall(v)
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 69:
    return _pcall(_shlex_split(args),stderr)
  File "C:\Users\Shivanhunter\dxx-rebirth\SConstruct", line 64:
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=stderr)
  File "C:\Python27\lib\subprocess.py", line 711:
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959:
    startupinfo)
```

and [here](https://github.com/dxx-rebirth/dxx-rebirth/files/1370888/sconf.log)'s the new sconf.log in case anything's changed.

**Comment by vLKp** [comment] 2017-10-11 01:59
> that should probably be added to the build instructions as well as the old Scons version.

Is an old SCons version still necessary?  I previously pushed a speculative change for the one issue you reported with the new version.

> About the sdl thing: I ran `C:\MinGw\bin\pkg-config.exe --modversion sdl` in cmd and got an error about PKG_CONFIG_PATH. So I added that variable, set to `C:\Git\mingw64\lib\pkgconfig`, and now when I run `C:\MinGw\bin\pkg-config.exe --modversion sdl`, I get "1.2.15".
> 
> But it still fails in Git Bash.

This is interesting, but also ambiguous.  What kind of error did you get?  Where did you add the variable?  Why do you have both a `C:\MinGw\` and a `C:\Git\mingw64\lib`?  In what directory is `sdl.pc` found?

What do you mean "it still fails in Git Bash"?  What still fails?  Is the `pkg-config --modversion` command functional when run from cmd.exe, but not when run from Git Bash or do you mean only that `scons.py` reports failure when run from Git Bash?  If the latter, did you check that the variable is actually set properly in the Git Bash?

After some experiments, it looks like the `--modversion` call is done with `shell` unset (and so safely defaulted to `False`), but when I delegate the `--cflags --libs` call to SCons, it runs the child process with `shell=True`.  This may explain why one works and the other fails.  I have seen problems on Windows before where Python cannot execute subprocesses directly, but must instead route them through the shell.  Linux systems also have this `shell=False` / `shell=True` split, but have no problem finding the target program in both cases.  I have not yet tested on Windows to see if this is universally broken (rather than broken only on your system) and, if so, why it only impacts Windows.

**Comment by ef314159** [comment] 2017-10-11 02:30
PKG_CONFIG_PATH is a Windows environment variable - running `C:\MinGw\bin\pkg-config.exe --modversion sdl` from the command line reported that it couldn't find the config file for sdl, and I could use that variable. So I added it, and set it to `C:\Git\mingw64\lib\pkgconfig` (which I mentioned earlier, is the location of sdl.pc).

In Git Bash, even with the PKG_CONFIG_PATH, I still get the same error I was getting before - the one I quoted in my last post (along with the new output from `raise`).

Yes, when I run `C:\MinGw\bin\pkg-config.exe --modversion sdl` from the command line, I now get "1.2.15", but when trying to build in Git Bash, I get the same error as before.

The [build instructions](https://forum.dxx-rebirth.com/showthread.php?tid=857&pid=9850) reference both a C:\MinGW\ and a C:\Git\mingw64\. I'm not sure why Git needs its own mingw64 stuff - I've never worked closely with either Git or MinGW - but it does seem to be correct.

---

One further note, I was screwing around in Git Bash with environment variables - normally, it does seem to be reading my environment variables correctly (along with some additions of its own to places like C:\Git\mingw64). I screwed one of them up, and got an error that included this snippet:

```

**Comment by ef314159** [comment] 2017-10-11 02:36
PKG_CONFIG_PATH is a Windows environment variable - running `C:\MinGw\bin\pkg-config.exe --modversion sdl` from the command line reported that it couldn't find the config file for sdl, and I could use that variable. So I added it, and set it to `C:\Git\mingw64\lib\pkgconfig` (which I mentioned earlier, is the location of sdl.pc). This allowed `C:\MinGw\bin\pkg-config.exe --modversion sdl` to work on the command line.

In Git Bash, even with the PKG_CONFIG_PATH, I still get the same error I was getting before - the one I quoted in my last post (along with the new output from `raise`).

Yes, when I run `C:\MinGw\bin\pkg-config.exe --modversion sdl` from the command line, I now get "1.2.15", but when trying to build in Git Bash, I get the same error as before.

The [build instructions](https://forum.dxx-rebirth.com/showthread.php?tid=857&pid=9850) reference both a C:\MinGW\ and a C:\Git\mingw64\. I'm not sure why Git needs its own mingw64 stuff - I've never worked closely with either Git or MinGW - but it does seem to be correct.

---

One further note, I was screwing around in Git Bash with environment variables - normally, it does seem to be reading my environment variables correctly (along with some additions of its own to places like C:\Git\mingw64). I screwed one of them up, and got an error that included this snippet:

```
DXX-Archive.3: using pkg-config at discovered path C:\MinGw\bin\pkg-config.exe
DXX-Archive.3: reading SDL settings from `C:\MinGw\bin\pkg-config.exe --cflags --libs sdl`
Package sdl was not found in the pkg-config search path.
Perhaps you should add the directory containing `sdl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sdl' found
DXX-Archive.3: SDL pkg-config failed; using default flags for `C:\MinGw\bin\pkg-config.exe --cflags --libs sdl`: {'LIBS': ['SDL']}
```

I never got this error before in Git Bash. This is the error I got from pkg-config in the command line (when the PKG_CONFIG_PATH was missing). Since I never got it before, I suppose the variable was never missing in Git Bash (it was one of the additions) and the problem is due to something else. May not be helpful info but I thought I'd mention it.

**Comment by vLKp** [comment] 2017-10-14 17:21
I finally had a chance to borrow a Windows system to investigate this.  The problem technically affects all platforms, but only Windows users are likely to notice.  The path to **pkg-config** is always passed through **shlex.split** to apply standard shell quoting rules.  When you specify the path on the command line, you usually want this, since it lets you run a wrapper or pass extra arguments.  When the path is guessed for you, you don't need this, but it rarely matters on non-Windows.  On non-Windows, the path is unlikely to contain any characters that **shlex.split** handles specially, so the path is returned as-is.  On Windows, the path is guaranteed to contain a backslash, and may also contain spaces.  This causes **shlex.split** to return a result other than the input, so the command run is not **C:\bin\pkg-config.exe** as intended, but instead **C:binpkg-config.exe**, because the *b* and *p* were escaped by the leading backslash.  This latter path almost certainly does not exist, hence "No such file or directory" is raised.

You can work around this by disabling use of pkg-config (and then setting manually the CFLAGS, LIBS, and LINKFLAGS it would have set for you) or by setting its path explicitly (and escaping it accordingly).  [Only shlex.split pkg-config paths from user](/dxx-rebirth/dxx-rebirth/commit/b9af2dbedbceececaa8d5a7f3881baaa97a4a1f4) fixes this properly, avoiding the need for a workaround.

**Comment by ef314159** [comment] 2017-10-14 21:47
Alriiiight... I got an exe file built and working!

I had three more problems, all of which I THINK I fixed, but I'm dumb so I probably did it wrong. :V

It now complains that I have no "SDL_mixer.pc" for pkg-config:

```
DXX-Archive.3: reading SDL_mixer version from ('C:\\MinGw\\bin\\pkg-config.exe', '--modversion', 'SDL_mixer')
Package SDL_mixer was not found in the pkg-config search path.
Perhaps you should add the directory containing `SDL_mixer.pc'
to the PKG_CONFIG_PATH environment variable
No package 'SDL_mixer' found
DXX-Archive.3: reading SDL_mixer settings from ('C:\\MinGw\\bin\\pkg-config.exe', '--cflags', '--libs', 'SDL_mixer')
Package SDL_mixer was not found in the pkg-config search path.
Perhaps you should add the directory containing `SDL_mixer.pc'
to the PKG_CONFIG_PATH environment variable
No package 'SDL_mixer' found
DXX-Archive.3: SDL_mixer settings: {}
DXX-Archive.3: checking for usable library SDL_mixer...no
DXX-Archive.3: checking for usable header SDL_mixer.h...yes
scons: *** Header SDL_mixer.h is usable, but library SDL_mixer is not usable.  See sconf.log for details.  Stop.
```

This time, it's correct: The build instructions never mention an SDL_mixer.pc, so I don't have one. I stole one from somewhere else, made sure the paths were correct, and put it in `C:\Git\mingw64\lib\pkgconfig` with sdl.pc - it's [here](https://github.com/dxx-rebirth/dxx-rebirth/files/1384985/SDL_mixer.txt) (again renamed to .txt since Github won't take a .pc file). I have no idea if Rebirth needs any other CFLAGS, but the build just happened to magically work for me - I only tested opening one level with the new exe so if there are crashes, I probably haven't found them. Anyway, the build instructions should probably tell people to set up this file as well.

Another issue was that when trying to run the new d2x-Rebirth.exe, I got "The procedure entry point __gxx_personality_v0 could not be located in the dynamic link library libstdc++-6.dll". I fixed this by copying that dll from C:\MinGW\bin into my d2x-rebirth directory (replacing another version of the dll that was there). Once I did that, the game seemed to run fine. Maybe the thread should mention that you'll have to copy DLLs out of your MinGW folder, since you may be compiling against different versions than the ones Rebirth shipped with. Or (probably) having mingw64 would fix that as well.

The final issue was that d1x-Rebirth couldn't parse my old 
[d1x.ini](https://github.com/dxx-rebirth/dxx-rebirth/files/1385007/d1x.ini.txt) - "similar\misc\args.cpp:478: Unhandled argument "System" while processing "d1x.ini"". I've never used this file and everything in it is commented out - I just deleted it and the game ran fine. For all I know it's just a holdout from an old d1x-Rebirth install that I still had sitting in the folder anyway.

I'll try and reinstall the newest SCons to see if that's still broken. Otherwise, it looks like the build instructions just need to be updated to point to mingw64 specifically, include the sdl_mixer.pc file, and (possibly) mention copying MinGW's DLLs.

**Comment by vLKp** [comment] 2017-10-15 00:32
Good to hear.  For SDL_mixer, it is an optional compile-time dependency and, if used, becomes a mandatory load-time dependency.  As such, since you chose to fix the pkg-config file for it (this is the right choice: most people want SDL_mixer) rather than disable it, your built executable requires it to run.  Any problems with SDL_mixer should manifest as either a failure to build the executable or as an immediate failure to start, with an error message about a missing dll.  This would appear at the same point as the error you did see with `__gxx_personality_v0`.  If your build runs at all (and you already found that it does), then you should be fine.  I would not worry about encountering problems during gameplay as a result of any mistakes made with SDL_mixer (and nothing you described here looks like a mistake to me).

Regarding crashes, I consider it a bug worthy of an issue report if an unpatched version of Rebirth with its default flags crashes, no matter how you set up the environment that built it.  If you start adding custom CXXFLAGS or patching the code, you might break it, but the defaults should always work.

Regarding the ini file, yes, that's an outdated ini, and yes, you handled it properly.  Rebirth has always read that ini file for additional command line arguments.  Historically, Rebirth silently ignored arguments it did not understand, so uncommented garbage lines in the file were silently permitted, and the stock file contains several such lines.  Several years ago, I modified the command line parser to reject unhandled arguments, on the theory that a user who misspells an option (or uses an option that does not exist in the target build) would prefer an immediate failure with an error over having the game start and silently ignore the option.  There's a forum post up warning people to fix their ini file, but it is in a thread primarily targeted to people using prebuilt Windows binaries, so you may have skipped that thread.

@Mako88: would you mind editing your forum post of build instructions to include the changes that @ef314159 described here?

* SDL_mixer - disable or install fully, and if installed, ensure a pkg-config file is available
* Proper handling of the `__gxx_personality_v0` issue
* Recommend disabling minidump support or recommend using the mingw64 API headers

@ef314159: did my summary miss anything?

**Comment by ef314159** [comment] 2017-10-15 00:38
Nope, looks like that's everything! Thanks for the help!

**Comment by Mako88** [comment] 2017-10-16 14:56
Hopefully I should get a chance to rewrite those instructions later this afternoon. I'll close this issue when it's done.

**Closed** 2017-10-26 04:17 UTC
