### ISSUE TITLE
SDL2: Sounds are followed by noise

### ISSUE THREAD

**Issue by heftig** [dxx-rebirth/dxx-rebirth#396] opened 2018-07-29 18:08 UTC
### Environment

c65020bf041a52806b90d0bd527570dad64f6bfa

#### Operating System Environment

* [x] Arch

#### CPU environment

* [x] x86\_64 (64-bit Intel/AMD)

### Description

Sounds are followed by loud noise, apparently the same length as the sound. Music plays fine.

#### Regression status

Only happens when SDL2 is used.

### Steps to Reproduce

`scons sdl2=True sdlmixer=True`

- Start a new game and skip until spawn

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player

**Comment by parkerlreed** [comment] 2018-07-29 20:07
I don't even get music. Game starts silent, start game, plays fine but no music plus the static after the sounds.

https://www.youtube.com/watch?v=NsEa0MEtt1c&feature=youtu.be

````
[parker@e55 d1x-rebirth]$ ldd d1x-rebirth
        linux-vdso.so.1 (0x00007ffe8547a000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007fa356296000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007fa356060000)
        libphysfs.so.1 => /usr/lib/libphysfs.so.1 (0x00007fa355e33000)
        libSDL2_mixer-2.0.so.0 => /usr/lib/libSDL2_mixer-2.0.so.0 (0x00007fa355c14000)
        libSDL2-2.0.so.0 => /usr/lib/libSDL2-2.0.so.0 (0x00007fa3558e2000)
        libGL.so.1 => /usr/lib/libGL.so.1 (0x00007fa355657000)
        libGLU.so.1 => /usr/lib/libGLU.so.1 (0x00007fa3553d7000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fa35504e000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fa354cb9000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fa354aa1000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fa354883000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fa3544c7000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fa3542c3000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007fa3540bb000)
        libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007fa353e8a000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fa353b4b000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x00007fa353939000)
        libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007fa353683000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fa357339000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fa35345a000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fa353256000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fa353050000)
[parker@e55 d1x-rebirth]$ ./d1x-rebirth 

Type './d1x-rebirth -help' for a list of command-line options.

D1X-Rebirth v0.59.100 0.60.0-beta2-117-gc65020bf041a  Jul 29 2018 15:55:35
This is a MODIFIED version of Descent, based on Registered v1.5 Jan 5, 1996.
Copyright (C) 1994, 1995 Parallax Software Corporation
DESCENT is a trademark of Interplay Productions, Inc.
Copyright (C) 2005-2013 Christian Beckhaeuser, 2013-2017 Kp
Using SDL_mixer library v2.0.2
sdl-joystick: 0 joysticks
DXX-Rebirth: OpenGL: disabling automatic GL sync since VSync is turned off
Music descent.hmp could not be loaded: ModPlug_Load failed
Music briefing.hmp could not be loaded: ModPlug_Load failed
Music game01.hmp could not be loaded: ModPlug_Load failed
Music descent.hmp could not be loaded: ModPlug_Load failed
````

**Comment by vLKp** [comment] 2018-07-29 20:40
Confirmed.  Investigating now...

**Comment by vLKp** [comment] 2018-07-30 01:00
The Rebirth code has always handled sound this way.  Old versions of SDL-mixer handled the data in a way that the Rebirth behavior was harmless.  SDL2-mixer does not.

Documentation for SDL-mixer is silent on whether the old way was wrong.

SDL2-mixer documentation mentions in passing that the latter part of the buffer is undefined, but the porting guide makes no mention of this.  Running with `sdlmixer=0` does not provoke the problem, since the affected code is specific to sound conversions performed for the benefit of SDL-mixer / SDL2-mixer.  Since SDL-mixer returns the data required to do the right thing, I expect that the previous Rebirth behavior was silently wrong (which, considering this is sound related, is funny since silence is the right result), rather than actually correct.

[SDL2-mixer: fix noise from reading undefined sound data](/dxx-rebirth/dxx-rebirth/commit/1b8ff6ac7712fd3942831aef029bfcb280845b29) silences the noise for me, as well as improving the error reporting a bit.

**Comment by vLKp** [comment] 2018-08-01 01:26
Proposed fix worked for me and confirmed working by another previously affected user (though not yet confirmed or rejected by the original reporter).  Closing.

@heftig: please reopen if the cited commit does not resolve the problem.

**Closed by vLKp** 2018-08-01 01:26 UTC
Labels: bug, sdl2
