### ISSUE TITLE
Odd Arm Behavior of Green Bot When Receiving Damage (D2)

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#275] opened 2016-11-23 03:36 UTC
When a green bot receives damage, he doesn't fire for awhile and his arms get disjointed. Here's a demo:
http://missionaire.org/ACK/Descent_Stuff/weird_arms.dem

**Comment by zicodxx** [comment] 2016-11-29 15:56
This doesn't look like a bug for me. If the bots are hit, they do bend to bend their wings like that. I reproduced this easily in the MS-DOS version of the game running via DOSBox, reaching the same results as the demo. The Framerate was rather low but it was clearly noticeable. If this *is* a bug, it's there since the beginning but it doesn't look particularly wrong to me.

@Mako88 Just in case I missed what you wanted to show in the demo, if you can, try to reproduce it via DOSBox. The Bot in front of the door leading to the Energy Center in D2 Lvl 1 seems to be a reliable candidate as well. If you think it's comparable, we can close this issue.

**Comment by Mako88** [comment] 2016-12-04 01:01
You're right, this is original behavior. I should have checked before posting the issue. Closing.

**Comment by Mako88** [comment] 2016-12-04 15:15
Welp, closed it too soon. Them moving their arms slightly and a brief pause IS default behavior. However, the amount of pause and the arms actually coming disjointed from the body ISN'T default behavior. Reopening.

**Comment by zicodxx** [comment] 2016-12-04 20:45
I am still unable to produce the bots behaving differently in Rebirth compared to the MS-DOS version of the game. If you can bisect the issue, this may be helpful to find out what may be the problem.

**Comment by vLKp** [comment] 2016-12-04 22:25
To be sure we are all chasing the same problem, @Mako88, please post the standard bug report data:

- Test platform
- Commit used
- Build options used, including any applicable `site-local.py` values

My first thought on problem reports like this is that you are chasing a memory poisoning issue, which only shows up in poison-enabled builds and otherwise seems to work correctly.  These are particularly painful to bisect since poison instrumentation is recent, and defaulting poison on for debug builds is even more recent.

**Comment by Mako88** [comment] 2016-12-09 19:08
I'm sorry it's taken so long to get back to this.

This was on Arch Linux. It occurs only on debug builds and is currently present in 2abd810a49f877b71629eb016bb7b7f31177ef8. I believe you are right in saying this is a poison-enabled issue. I will attempt to bisect it using poison=overwrite in my builds.

**Comment by Mako88** [comment] 2016-12-09 19:16
A bit more information I discovered: This only happens when vsync is disabled AND on debug builds. I believe that this is an FPS issue then, since the release builds are capped at 200 FPS while debug is at 1000 FPS.

**Comment by zicodxx** [comment] 2016-12-11 16:51
I can confirm this by now, tested with the green bots in D2 Level 1. But I am not 100% convinced that this bug itself shows due to a mistake in animations. At least not alone. In a way, it seems - at least partially connected to #278. With increasing FPS rates, the longer bots seem to take to recover from hits from the player. 

The animation phases of the robot joints play during that time so it is hard to make conclusions where this problem stems from in particular.

**Comment by zicodxx** [comment] 2016-12-28 14:38
Pushed 03f5cbf3a40556b5f09f775231b06699800288a6 which addresses this issue. FrameTime got too small to return any substantial joint angle movement for the bots from fixmul, making them unable to recover from player hits and collisions properly (and taking much longer to recover until they could fire again). 

I solved this by scaling deltaang by DELTA_ANG_SCALE before being passed to fixmul. This solves the issue up to an FPS value of ~4000 (which the game doesn't support due to 'division by 0' issues) but all in all it's a limitation of fix being an integer. I do wonder if there are more code parts affected by this issue. Apparently the original developers were - at least partially - aware of issues like that as the AI code in particular has multiple occurrences of FrameTime being multiplied before being passed to fixmul. In that regard, I could not find anything wrong in the ai.cpp and aipath.cpp but this is a potential issue I'll keep my eye on.

**Closed by zicodxx** 2016-12-28 14:38 UTC
