### ISSUE TITLE
Snapshot build 20200401 is for Win64, cannot be executed on Win32

### ISSUE THREAD

**Issue by snytek** [dxx-rebirth/dxx-rebirth#504] opened 2020-04-26 12:09 UTC
#### Environment

https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20200401-win.zip

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [ X] Microsoft Windows 10

#### CPU environment

* [X ] x86 (32-bit Intel/AMD)
* [ ] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

Starting d2x-rebith-exe will instantly display a Windows message: 
- German: Diese App kann auf dem PC nicht ausgeführt werden
- English (translated): This app cannot be executed on the PC

#### Regression status

I noticed that the executable got bigger during the last releases. One time it grew to about 35 MB which still run fine, now it is around 55 MB and crashes on startup. 

I assume that some dlls were merged with the executable and that maybe a compilation issue (x64/x86) leads to this problem. The problem does not show up on Windows 10, 64bit systems.

### Steps to Reproduce

I assume: start exe on a Windows 10, 32bit computer

* Engines affected:
  * [ ] D1X-Rebirth
  * [X ] D2X-Rebirth

I haven't tested D1!

**Comment by vLKp** [comment] 2020-04-26 17:57
I don't have a Windows 32 bit system to test this, but I can see from file inspection that this will be true.  That snapshot was built for Win64, so you cannot run it on a Win32 system.  You will need to build a Win32 version yourself, find someone to build a Win32 version for you, or use a Win64 system.  This is not a bug in the program.

**Comment by snytek** [comment] 2020-04-26 19:52
All versions including 059 worked on x32 and x64 but the latest does not. I agree that this isn't a programing bug but something must have changed in the compilation process (the increase of the exe file size is a clear indication).

Sad to hear that this won't change. I won't be able to get this compiled in a reasonable amount of time and it's unlikely that I will find someone which does that for me.

However, thanks for your feedback.

**Comment by vLKp** [comment] 2020-04-26 20:29
I didn't say there will not be Win32 snapshots.  I said you cannot run a Win64 build on a Win32 system.  That has never worked for any Win64 program, and likely never will.  Is there a reason you are still running 32-bit for Windows 10?  I thought 32-bit had been discouraged for a long time.

As far as I know, @zicodxx is the one who provided prebuilt Windows snapshots recently, although @Mako88 did so at one time.  Perhaps one of them would provide another one for you.  I have never provided snapshots for any target platform, and have no plans to start doing so.

**Comment by snytek** [comment] 2020-04-27 07:56
Sorry, I misunderstood, I thought a decission was made to not further support 32 bit.

Of course you can't buy a 32 bit CPU nowadays but they are still around. I have 2 kids and both of them like to play D2 and have much fun with it (besides their father). I'm planning to replace this old computer but for the time beeing it won't be possible so I have to live with it.

I am new to GitHub - how do I contact Mako88? Zico, as I read, is in retirement.

**Comment by vLKp** [comment] 2020-04-29 02:47
Both of them have their e-mail addresses shown in their respective commits.  I don't know if that's a good way to contact them.  My use of @-mentions for their handles should cause the system to notify them about this thread when next they check activity on Github.  Last I heard, Mako88 had offline concerns occupying his time.

**Comment by vLKp** [comment] 2020-06-11 02:40
There is nothing I can do here.  I do not maintain prebuilt snapshots of any type, and currently have no plans to start.  I see that a new snapshot was posted at the end of May, and is still Win64.

As a test, I just built the current code using `i686-w64-mingw32-gcc-9.3.0` without issue, so 32-bit builds are still viable for anyone who wants to make one.  If the documentation is not sufficient to enable you to do this, please file an issue describing the problem.

**Comment by zicodxx** [comment] 2020-06-30 16:25
Late response, sorry:
Yes, I still provide builds when I have the time and the changes warrant it - it's the most I can still do these days.
The game compiles fine with a 32Bit MSYS environment, I just hadn't really considered a need for it in this day and age. Since both 32 and 64Bit binaries would require their own set of DLLs I can't also throw both binaries into one folder and pack them up (to my knowledge) - I would need to prepare different archives (and different build scripts - one for each MSYS environment). 

It's all possible - just more work and I don't really see the point of it, especially with MSYS2 being fairly easy to use, one could make such specific build on their own.

**Comment by vLKp** [comment] 2020-07-02 03:16
Correct: you need separate directories for 32-bit and 64-bit versions, since the names of the supporting libraries collide and you cannot have a file that is both 32-bit and 64-bit at the same time.  (There were some experiments with merged bitness files in some cases, but none ever became viable or widespread, as far as I know.  I don't remember if anyone ever tried to do merged files for Windows targets.)

@zicodxx: do you see any reason to leave this issue open?  Discussion has established that:

1. The current builds do not work on 32-bit.
2. I am not providing builds of any platform.
3. The builds you provide are 64-bit, and you don't see a reason to change that.
4. Local builds are (presumed to be) easy, for those people who need 32-bit.
5. I support and encourage people to be able to build locally, and to file defect reports against the documentation when it does not adequately cover building locally.
   - Anyone who builds locally can build for 32-bit or 64-bit, as they see fit.

From that, I do not see what else would be discussed here.

**Comment by zicodxx** [comment] 2020-07-05 09:01
@vLKp You're right of course, this can be closed. Sorry.

**Closed by zicodxx** 2020-07-05 09:01 UTC
