### ISSUE TITLE
Runtime bug: Filenames of movies within movie files are incorrectly treated case sensitively

### ISSUE THREAD

**Issue by AlumiuN** [dxx-rebirth/dxx-rebirth#644] opened 2022-07-09 00:11 UTC
Currently, the filenames of movies within movie files are being treated as case sensitive, when the behaviour of the original game was case insensitive. The main case where this is relevant is the Vertigo robot briefing movies, as one of the robots has a lower-case extension (i.e. it is called "RB9.mve), and as such Rebirth fails to play it.

**Comment by vLKp** [comment] 2022-07-09 15:19
Isn't this issue #379?  PhysFS 3.0.0 and PhysFS 3.0.1 are incorrectly case-sensitive in resolving files within the archive.  Per https://github.com/dxx-rebirth/dxx-rebirth/issues/379#issuecomment-390519276 , the high-resolution / low-resolution movies disagreed on the capitalization, so I chose not to change the code for those.  According to https://github.com/dxx-rebirth/dxx-rebirth/issues/379#issuecomment-389400528 , this was intended to be fixed in PhysFS 3.0.2.  However, I note that https://github.com/dxx-rebirth/dxx-rebirth/issues/379#issuecomment-477790175 asserts that the PhysFS changelog never mentioned such a fix.

What version of PhysFS are you using?  It is responsible for loading the files from the archive by name, so it is relevant to whether the archive is handled properly.

**Comment by AlumiuN** [comment] 2022-07-09 23:59
Ah, yes, it would be (even more specifically it's #427) - I'm using PhysFS 3.0.2, and another user reported the same issue with the Rebirth build from the website, so presumably whatever version Zico is using also exhibits the same problem.

**Comment by vLKp** [comment] 2022-07-17 15:04
Where is this other report, and when was it made?  Yes, #427 is a better citation than #379.  I found #379 first and did not recall that #427 was also out there.  While I am reluctant to add a code hack to deal with this, particularly in light of the results recapped in https://github.com/dxx-rebirth/dxx-rebirth/issues/427#issuecomment-502397899 (which make code hacks messier due to the multiple inconsistencies to be fixed), I may need to do so, since the original reports are now quite old, and it seems that PhysFS 3.0.2 is still affected.

**Comment by AlumiuN** [comment] 2022-07-17 22:33
It does actually look like a hack for this (general) situation already exists - PHYSFSEXT_locateCorrectCase in common/misc/ignorecase.h is used a few times in other situations, even if the header for it does state that it's probably not a good idea :P

**Comment by vLKp** [comment] 2022-07-22 01:23
Yes, that hack exists, but for the limited scope here, I would rather just have logic to explicitly try the alternate names that I recapped in https://github.com/dxx-rebirth/dxx-rebirth/issues/427#issuecomment-502397899 (which were derived from findings that @ryusei117 posted in https://github.com/dxx-rebirth/dxx-rebirth/issues/379#issuecomment-390519276).

**Comment by vLKp** [comment] 2022-09-24 18:01
[Add hack for case mismatch in Vertigo robot movies](/dxx-rebirth/dxx-rebirth/commit/ad7057be877fd189ef7577faa8a7b37619494547) should work around this in Rebirth.  Movies seemed to work better for me with it than without it.  Please sync and retest.

**Closed by vLKp** 2022-09-24 18:01 UTC
Labels: bug
