### ISSUE TITLE
When duplicating items, client's number is squared

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#71] opened 2015-05-28 00:57 UTC
In a multiplayer game when the host sets items to be duplicated, the number of items for the client is squared. I.E. if the host sets 4, the client will have 4^2 = 16 items.

**Comment by Mako88** [comment] 2015-05-29 11:48
Check the for loop on line 3263 of multi.cpp. Is the break condition correct? Also it's probably that for loop that's somehow the problem, right?

**Comment by Mako88** [comment] 2015-05-29 13:36
I think I figured it out...the duplication is called inside multi_prep_level which is called for every client that joins. So when host joins, the duplication happens (let's say it's 3). Then when the first client joins, it duplicates everything that's there (so all 3 get duplicated again to have 9). When the third client joins everything is duplicated again to make 27, etc.

**Comment by vLKp** [comment] 2015-05-30 03:27
Bug confirmed, but only when viewed from the client.  The host sees the correct number of items.

In [current HEAD](https://github.com/dxx-rebirth/dxx-rebirth/tree/3f9d110502ac9c7ad96c03967839eb347cb4a93e), [similar/main/multi.cpp:3263](https://github.com/dxx-rebirth/dxx-rebirth/blob/3f9d110502ac9c7ad96c03967839eb347cb4a93e/similar/main/multi.cpp#L3263) is a comment about multi_prep_level.  As best I can tell, it is only called once during level setup.  It will be called by each client, but I expected that and expected that the duplicates it creates would align the client's view with the host's view.  This function is also responsible for deleting robots and for converting objects into shields.

**Comment by Mako88** [comment] 2015-05-30 16:34
It's line 3239 now. Sorry. I think it's correct, just a bit ambiguous since it's saying if(i) instead of if(i > 0).

**Comment by vLKp** [comment] 2015-05-30 16:40
`if (i)` is short for `if (i != 0)`, which is in turn short for `if (i < 0 || i > 0)`.  Since `i` is `uint_fast32_t`, `i` is either 0 or >0, but never <0.

**Comment by vLKp** [comment] 2015-08-11 03:16
@zicodxx: any ideas why this is misbehaving?  Clients which join after the level has started see more powerups than the duplication setting says they should.  The host sees the right number.  Powerup duplication is handled in the same code that is responsible for deleting disallowed powerups.

**Comment by zicodxx** [comment] 2015-08-11 08:30
I still have to check this one out. My best guess is that the clients which join the game get the sync packets from host (syncing all objects including powerups - net_udp_send_objects) and then possibly also run through the function that is supposed to provide the multiplication at level start - duplicating the duplicates.

**Comment by vLKp** [comment] 2015-08-12 01:21
I considered something like that, but did not understand the sync flow well enough to confirm or refute it.  I wonder if the way that the duplicates are created on the host causes it not to treat them the same as if they had been loaded with the level.  AFP said that it is a squaring issue, but my recollection is that I saw an additive growth, not a geometric one.

**Comment by zicodxx** [comment] 2015-08-12 10:21
I have only a limited number of Multiplayer issues on my plate so I think I'll be able to take a look at it, too. If the initial duplication does indeed happen before the client receives UPID_OBJECT_DATA, it *should* theoretically work. But that would also rely on the fact that the initial object duplication creates all objects on the same object slots for all clients. Otherwise the object syncing function may later not know which objects to overwrite.
But I have to admit, I need to check your implementation of the feature and refresh my memory again on how object syncing works in detail. Maybe I am totally off on how this issues comes to be.

**Comment by vLKp** [comment] 2015-08-13 01:27
The feature was added in [Add netgame parameter to duplicate powerups](/dxx-rebirth/dxx-rebirth/commit/b46ecbb3e9fd8e88f488651f0c6186a8d7e54d54).  The duplication is done by `update_item_state::process_powerup` in `similar/main/multi.cpp`.  It is called from `multi_prep_level` when a powerup is not converted to a shield.  `multi_prep_level` is responsible for not duplicating a powerup which exists solely because it is a duplicate of some other powerup.  `process_powerup` is responsible for skipping powerups that should not be duplicated due to their type being ineligible for duplication or due to the powerup being of a type which is not duplicated in the current settings (e.g. a primary when the host is only duplicating secondaries).

**Comment by zicodxx** [comment] 2015-09-01 17:26
Okay the issue should be fixed in dcd91636d8be33b38d8b9fa38096c3b8b5d33da4. I was initially thinking that the clients would first call multi_prep_level and then request an object sync - but in reality it works the exact opposite way. With that, the host sent a client all its objects - including the duplicates - which then the client duplicated on its own. 

I am not really sure but I FEEL that object syncing should be the last a client does before joining the game - way after prepping the level on its own but changing this could be very invasive and probably mess up more than it fixes. 

I circumvented the issue by preventing object duplication if Network_rejoined is true - which is the case for latecoming and rejoining players and used for things like this. 
This should fix the issue and from all I can tell, it does. Tested a bit by joining, collecting, spewing powerups, recollecting them and rejoining on all these steps with different clients. It seems to work as it should so I am closing this issue for now. But if some issues still remain, just open it again.

**Closed by zicodxx** 2015-09-01 17:26 UTC
Labels: bug
