### ISSUE TITLE
Trigger in Descent2.dem causes crash

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#177] opened 2016-02-14 13:35 UTC
Unfortunately I discovered another crash issue when playing back Descent2.dem.
At 61% is the demo playback, the demo - and the whole program - crashes with the message:
 
> terminate called after throwing an instance of `'valptridx<d2x::trigger>::index_range_exception'`
>  what():  invalid index used in array subscript: base=0x98a2a0 size=100 index=255

The backtrace shows the origin of the crash in line 2188 in newdemo.cpp:
> const auto &&t = vctrgptr(vcwallptr(segp->sides[side].wall_num)->trigger);

**Comment by vLKp** [comment] 2016-02-14 17:42
The demo code uses an out-of-range value without checking.  `valptridx<T>` is designed to abort on invalid values.  The demo code must check that the wall has a trigger before attempting to access the trigger.  By omitting this check, the game will run the `TT_SECRET_EXIT` check against an undefined value, so demo files might "randomly" execute the secret-exit-found path.  Interestingly, right above this line is a comment from me from [Fix invalid access reading demos](/dxx-rebirth/dxx-rebirth/commit/80e98ce2d373c8846c0064c1986eec51cf337084) (though attributed to you [since you reindented it with spaces](/dxx-rebirth/dxx-rebirth/commit/d493912bcc114eb3718d4a80589d9d471e915c5f)) where I had to add a check for invalid wall numbers.  Apparently there are also cases where the wall number is valid, but points to a wall with no trigger.

I will add a check for this condition.

I will not be surprised to find more such crashes as more arrays are converted to use `valptridx<T>` pointers and thus gain checking.  You can sweep for unchecked values by uncommenting [the definition of `DXX_VALPTRIDX_WARN_CALL_NOT_OPTIMIZED_OUT`](/dxx-rebirth/dxx-rebirth/blob/08de1bbff0be775c06324bea32c7dce3352afb8b/common/include/valptridx.h#L31), then building with a compiler that optimizes out unreachable uses of `__attribute__((__warning__))`.  Recent gcc with `-O2` should work.  I believe clang does not currently handle `__attribute__((__warning__))` in an acceptable manner.

**Comment by zicodxx** [comment] 2016-02-15 11:48
Yes, this fixes the crash issue. But the demo playback still seems a little buggy. Since the demo does bail out usually, it's hard to blame it on this code part but I think it does. Near the end of the playback (after where the initial crash occurred), the force field around the reactor is supposed to disappear. 

But it seems this is not fully the case as only the outward wall face is updated to disappear while the inward walls still show the force field. As seen here: http://www.dxx-rebirth.com/tmp/ff.jpg

**Comment by zicodxx** [comment] 2016-03-30 13:37
I am going to reopen this. While the crash bug is fixed, the game still shows a graphical glitch for the force field that is supposed to be removed near the end of the demo but it still appears on the inside of the reactor segment as demonstrated by the screenshot above. I will need to doublecheck if this has the same cause tho.

**Comment by vLKp** [comment] 2016-03-31 02:02
Please do not repurpose tickets.  This ticket was filed as a crash bug, which is now fixed.  I can confirm that the texture problem is present, but I think it should be tracked in a separate ticket focused on the graphical problem.

**Comment by zicodxx** [comment] 2016-04-01 07:35
Makes sense. Opening a new one.

**Closed** 2016-04-02 19:19 UTC
Labels: bug
