### ISSUE TITLE
Unification: Multiplayer Death State

### ISSUE THREAD

**Issue by Matt1360** [dxx-rebirth/dxx-rebirth#49] opened 2015-03-21 06:06 UTC
Start a game with two players, A and B.  A can kill B, or B can kill A.  Either can commit suicide if they really want.

Either way, the killing player sees their victim explode... and then have the little blue cross warp/spawn animation show, with the ship then frozen in place, forever more.  The victims ship will stay there, not bob (I assume it doesn't get positional updates).  It is still in the physical world as well, as the ship can be head-butted, and it hurts.  You can shoot the ship, but of course no sound of shield damage is emitted.

Once the victim respawns (as normal, by hitting a key or whatever), the ship simply disappears, and the game proceeds as normal.

I think I'll ask @zicodxx to [help me](http://i.imgur.com/JiWONyG.gif) here.

**Comment by zicodxx** [comment] 2015-04-08 12:42
This is actually a regression caused by two different things: the removal of a variable and - more importantly - undoing an old hack improperly. Player explosion would immediately cause a respawn effect. This should now be fixed in b512127328b7456a1816d84d5908025a388a7b9b.

**Closed by zicodxx** 2015-04-08 12:42 UTC
