### ISSUE TITLE
Command-Line/INI parser does not return correct place of fail

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#198] opened 2016-05-30 11:57 UTC
Testing the new ini parsing, I found a little bit of a mistake. My INI file only has to commands
> -use_players_dir -nomovies

That's all what exists in this file.

If I launch d2x-rebirth from command-line/bash with argument -fail, it will return:
> similar/misc/args.cpp:473: Unhandled argument "-fail" while processing "d2x.ini"

It should detect that the invalid argument was given in the command-line.

**Comment by vLKp** [comment] 2016-05-31 00:08
This is probably caused by [... Also allow commandline arguments to override ini arguments...](/dxx-rebirth/dxx-rebirth/commit/8fb9a05f7dc5a9139dedb6ad11ecc557866a389c).  When an exception is thrown, the list of ini files is used to produce the attribution string.  When ini files are added by processing `-ini`, `ReadCmdArgs` adds the new file, calls `ReadIniArgs`, then removes it.  However, when the default ini is read, it is not removed after the call to `ReadIniArgs`.  Originally, this was because nothing else happened after that call returned.  The `Inilist` immediately went out of scope, so clearing it was pointless.  After Mako88's change, the variable remains in scope during the call to `ReadCmdArgs` and retains the unused value of `INI_FILENAME`.

**Comment by Mako88** [comment] 2016-05-31 12:47
Tested with the latest beta build. Fixed; can be closed.

**Closed** 2016-06-01 01:57 UTC
Labels: bug
