### ISSUE TITLE
Escape Music D1

### ISSUE THREAD

**Issue by DescentMax** [dxx-rebirth/dxx-rebirth#356] opened 2017-11-12 03:11 UTC
The escape sequence music doesnt play when using Jukebox.

**Comment by DescentMax** [comment] 2017-11-13 00:25
D1 Escape works again. Audio Driver issue repaired. Works again

**Comment by DescentMax** [comment] 2017-11-13 01:16
Tested further still having issue. Seems to be random. Thought was fixed but issue still remains.

**Comment by vLKp** [comment] 2017-11-15 05:21
With the very limited information provided, I doubt I can help you.  In what version of Descent Rebirth did you observe the problem?  If you built it yourself, what options did you use?  If you downloaded a compiled build, from where did you get it?  Is the issue reproducible when not using the Jukebox?  On what operating systems is this observed?  On what levels is the escape music expected to play?  From what supporting files is it played?  I do not recall ever getting escape music in the game, though that may be because I reduced music volume to zero for in-game play.

**Comment by DescentMax** [comment] 2017-11-18 03:13
I apologize for the limited Info. Basically I took the D1 Mac Music and added the escape sequence from the .mp3 files to the Escape Sequence in the Jukebox. It happens on random levels but when I go back to the level it occurred on, it works again but the next level it doesnt play it. It plays the built in music just fine, just in the jukebox. Here is my Specs
Windows 10 Pro 64-Bit
12GB DDR3
AMD FX 6300 3.5GHz 4.1GHz Turbo
240GB SSD
NVIDIA 650TI 2GB GDDR5
Realtek HD Audio
D1x and D2x 0.59.100-743-G425B78B8A63B ( latest November Nightly build)

**Comment by vLKp** [comment] 2017-11-18 20:03
I cannot reproduce this.  I tried in both `Descent: First Strike` through D1X-Rebirth and `Descent 2: Counterstrike` through D2X-Rebirth.  Along the way, I encountered the following failures, none of which match the reported symptoms:

* Early return from `start_endlevel_sequence` because `endlevel_data_loaded == 0`.  This skips the endlevel sequence and skips the endlevel song.  In my case, it was `0` because of a failure to load debriefing files.  I did not investigate why these files failed.  When this failure mode applies, it applies to every pass through the affected level(s).  You reported random failures.
* Failure to open file because it is outside the PHYSFS working area.  While some code comments suggest this is a supported use case, I did not pursue it further.  I moved the sample file into the PHYSFS working area.  This failure is not random.  Either it always works or it never works.
* SDL_mixer not configured for mp3 support.  I switched to flac to continue work.  This is not your problem, since you specified a single mp3 to play, and SDL_mixer does not gain/lose mp3 support while the program is running.

Once past those problems, the endlevel song started on every attempt.  I tried the first 15 levels of Descent 2 and the first 3 levels of Descent 1.

If I had to guess, I would blame global variables that are not reinitialized or corruption of global memory.  Both are greatly improved relative to earlier releases, but there is still much to be done.  As it stands, I have no further ideas to try on this ticket at this time.  If you can provide a reliable way for me to reproduce this, I will revisit it.  Otherwise, this one is works-for-me.

**Comment by DescentMax** [comment] 2017-11-21 19:21
It could be my system causing that. Windows 10 collapsed the other day I'm just now getting things back up and going. Ill do fresh testing to confirm

**Comment by vLKp** [comment] 2018-04-02 03:43
I was unable to reproduce the problem.  Original reporter has not returned.  Closing.

Please reopen if you believe this to be a game bug.

**Closed by vLKp** 2018-04-02 03:43 UTC
Labels: cannot-reproduce, needinfo
