### ISSUE TITLE
Runtime bug: On D1, "no primary weapons available" causes sound spam with fire button held

### ISSUE THREAD

**Issue by ziplantil** [dxx-rebirth/dxx-rebirth#499] opened 2020-03-28 02:03 UTC
### Environment
a645fd2eba4f180f12a082225b2905b7113aa8dc

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [x] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment
All D1 missions, player having at least both laser and vulcan.

### Description
If the player is out of both energy and vulcan ammo and presses the primary fire button, the "no primary weapons available" message will appear and a sound will play (although not on DOS), which is expected behavior; however, holding down the fire button causes the sound to play every tick/frame, causing it to become very loud, which can startle unsuspecting players.

#### Regression status
Probably ever since the "no primary weapons available" sound was introduced; there is no such sound in DOS and therefore also no bug to revolve around it.

### Steps to Reproduce
1. Open say D1 level 1
2. Collect the vulcan (right, left, down, down)
3. Shoot the laser at the wall until you run out of energy
4. Shoot the vulcan at the wall until you run out of vulcan ammo
5. Try holding down the fire button after you get the "no primary weapons available" message

Expected: message appears, sound plays once
Actual: message appears, sound plays over and over again, so often that it causes the sound to layer, increasing its volume to the point of being very loud

* Engines affected:
  * [x] D1X-Rebirth
  * [ ] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

MP not tested, but likely.

* Players affected by issue:
  * [ ] Game host
  * [ ] Game guests

**Comment by vLKp** [comment] 2020-03-28 18:02
Confirmed.  Without the above fix, I encounter the described problem.  With it, the code no longer attempts to select lasers when the player is already on lasers.  You no longer get the error sound (at all) when the game forces a weapon change due to ammo exhaustion.  I think the error sound has some use when the player chose to change weapons, but I don't see the value of playing it when the player's weapon was forcibly changed.

Closing.  Please reopen if the problem persists.

**Closed by vLKp** 2020-03-28 18:02 UTC
Labels: bug
