### ISSUE TITLE
D1: Multiplayer Bug

### ISSUE THREAD

**Issue by TORRaven** [dxx-rebirth/dxx-rebirth#480] opened 2019-12-13 04:37 UTC
I noticed this bug:  cannot join (or re-join) network game.
I have tested this on a LAN.  Two PC's, both running Windows 10, and same D1X version.  Firewall turned off with port 42424 open on router.

From either PC, I can host a game, and it shows up on the tracker.
The other PC *might* connect once.  But if player 2 leaves the game, they cannot re-join unless they create a new pilot from the main menu.  Existing pilots cannot join the game in progress.  Nor can existing pilots join new games created.  Always met with the same error that the port may be blocked, version different, etc.

**Comment by vLKp** [comment] 2019-12-14 05:35
I cannot reproduce this with the instructions provided.  I built the latest code (currently [Fix Win32 build of scores.cpp](/dxx-rebirth/dxx-rebirth/commit/ca383c1fe76bf519f3064d2188d77ab54f2b6b42)), started two instances of the game, had one host an anarchy game, and had the other join the game.  The guest then quit the game, and rejoined without issue using the same pilot.  I tested on `Descent: First Strike` level 1 using v1.5 retail data.

**Comment by TORRaven** [comment] 2019-12-16 00:44
Must be something with my Router Firewall (Ubiquiti USG).

If i try to join the net game, it fails.  But if i point it directly to the LAN IP of the host, it works fine.
Sorry for the hassle!

**Comment by vLKp** [comment] 2019-12-16 01:36
Routing a join back into the same LAN is a common request, and requires a bit of special processing on the LAN's edge router.  I'm not familiar with that particular device, so I don't know if it is even possible for you to configure it to do the right thing here.  I've seen this configuration referred to as [hairpin routing](https://en.wikipedia.org/wiki/Hairpinning) since you want to reflect back inside rather than crossing the router.  Perhaps that name will help you if you want to research how to make the router support this.

I'm not sure why you were able to get intermittent successes.  The router may have been flapping between dropping the traffic or performing the required reflection.  It's probably not worth investigating since you have a working setup, but if you want to dig deeper, I would start by inspecting the router's NAT tables to see which connections it knows and where it thinks they go.

I can say that with the way Rebirth handles networking, using the internal addresses should have no negative consequences for you, even if you later have an Internet user join the same game (assuming the router is configured to forward that person's traffic to the host).  Rebirth doesn't need all players to see each other, so having some guests inside the LAN and some outside is fine.

---

Closing since this was reclassified as an issue external to the game.

**Closed by vLKp** 2019-12-16 01:36 UTC
Labels: cannot-reproduce
