### ISSUE TITLE
Build failure: similar/main/fireball.cpp missing #include <optional>

### ISSUE THREAD

**Issue by noabody** [dxx-rebirth/dxx-rebirth#605] opened 2021-09-25 02:45 UTC
#### Operating System Environment

* Manjaro
  * [x] Pahvo 21.1.4
#### CPU environment

* [x] x86\_64 (64-bit Intel/AMD)

### Description

similar/main/fireball.cpp missing include:
```#include <optional>```
#### Regression status
With include the build proceeds normally.

### Steps to Reproduce
Attempt to build without include produces error:
```'optional' in namespace 'std' does not name a template type```

**Comment by MaddTheSane** [comment] 2021-09-25 03:48
Pull request #604 should fix this issue.

**Comment by vLKp** [comment] 2021-09-25 18:11
Pull request #604 states it is for Mac OS X, and so I assume it uses Apple's C++ standard library.  As a Linux distribution, I would expect Manjaro would be using gcc and its standard library - where this works, albeit because of an incidental inclusion via another header.  For me, without this extra include, the build works correctly on all of gcc-7.5.0, gcc-8.5.0, gcc-9.3.0, and gcc-10.3.0, which is why the change was published without this inclusion.

@noabody: with what compiler (name and version) and standard library did you try to build this?  Typically, the `Regression status` field is used to report the first commit that exhibits the problem, not the expected results.

**Comment by vLKp** [comment] 2021-09-25 18:19
I merged pull request #604, which should resolve this.

**Closed by vLKp** 2021-09-25 18:19 UTC
Labels: build-failure
