### ISSUE TITLE
Build failure: INSTALL documentation appears to be insufficient

### ISSUE THREAD

**Issue by AlumiuN** [dxx-rebirth/dxx-rebirth#473] opened 2019-11-18 02:21 UTC
### Environment

Latest commit (b399794)

#### Operating System Environment

Microsoft Windows 10 (up to date)
Compiler is mingw-w64 using gcc 8.1.0 (32-bit)

#### CPU environment

Compiler targeting x86 (32-bit Intel/AMD)
Host system is x86\_64 (64-bit Intel/AMD)

### Description

The INSTALL.markdown file's instructions appear not to be sufficient in allowing the build to be successful. A few issues I've had in attempting to build:

- No information is given on where the build system will look for the required libraries; pkg-config appears to be leveraged to be able to find libpng, but not for PhysFS, and even adding the relevant directories to the system PATH variable appears to not work in that case (I'm using PhysFS 2.0.3 if that helps)

- libpng is not included in the listed prerequisites (possibly others, but I have yet to be able to get past the PhysFS part of the build script)

- Less of an issue than an update, but current versions of scons support Python 3

Note that I'm a fairly amateur developer (my experience is wholly in small, simple applications and Wolfenstein 3D mods), so it's entirely possible, if not likely, that there is more than a small element of user error involved.

**Comment by vLKp** [comment] 2019-11-18 04:43
- Yes, the path documentation would be good to improve.  I think it will look in the default search path for your linker.  If I knew what that would be, I would document it. :smile:  Based on some searches, it looks like you can print the default search path with `ld --verbose | sed -e '/SEARCH_DIR/!d' -e 's/;\s*/\n/g'`.  Please post that output here as a comment.  I suspect the answer will be that it searches a few directories relative to wherever you unpacked the development tools.  For my cross-compiler, it produces:
  ```
  $ mingw32-ld --verbose | sed -e '/SEARCH_DIR/!d' -e 's/;\s*/\n/g'
  SEARCH_DIR("=/usr/mingw32/lib")
  SEARCH_DIR("=/usr/local/lib")
  SEARCH_DIR("=/lib")
  SEARCH_DIR("=/usr/lib")
  ```
- SConstruct doesn't use `pkg-config` for physfs.  I think PhysFS historically did not have a pkg-config file, though I see one installed with PhysFS 3.  This was only added in [Added pkg-config support](https://hg.icculus.org/icculus/physfs/rev/aae614cdd005) (2013-11-13), so it isn't in PhysFS 2.  I should add support for searching for it, so that this works better for PhysFS 3 users.
- libpng: I think the install documentation has not been updated since before libpng became an option.  Good catch.  This should be fixed in the documentation.
- Python 3: yes, that also should be fixed.  There was a time where `scons` supported python3, but the Rebirth `SConstruct` file did not.  That has long since been fixed.  I routinely use Python 3 to run `scons` on Rebirth.

> Note that I'm a fairly amateur developer ...

The intended audience is end users who are comfortable following instructions, but not comfortable debugging error output from developer tools.  If you can't get it working with what's in the documentation (and maybe some modest search engine usage), then the documentation needs to be better.  I appreciate the disclaimer, but I also appreciate having a good test audience. :smile:

**Comment by AlumiuN** [comment] 2019-11-18 09:40
I don't have sed (at least not somewhere that Powershell can find it), but it looks like the search dirs are pretty much as expected:

```
SEARCH_DIR("=/c/mingw810/prerequisites/i686-binutils-nomulti/i686-w64-mingw32/lib");
SEARCH_DIR("=/c/mingw810/prerequisites/i686-binutils-nomulti/lib");
SEARCH_DIR("=/usr/local/lib");
SEARCH_DIR("=/lib");
SEARCH_DIR("=/usr/lib");
```

The only one of those that corresponds to an existing folder is "=/lib"; that would lead me to expect that it would expect headers to be in the corresponding "include" folder. Putting PhysFS into those means it finds them. Unfortunately, doing the same with my SDL files (I'm using the prebuilt versions, so I don't have a pkg-config file for those) doesn't seem to work how I would expect it to, so I might have to set up a pkg-config file for them.

**Comment by vLKp** [comment] 2019-11-19 05:07
> I don't have sed

Sorry.  The output you provided is fine.  Your guess about `/lib` seems reasonable.

> the corresponding errors in sconf.log are pretty much all variations of the following:

I recall @zicodxx reporting a similar problem trying to do native Windows builds.  I've never encountered it personally, which makes writing a patch to fix it a bit more difficult.  It seems strange to me that a core header is redundantly declaring a symbol provided by a built-in.  As a temporary fix, you could try removing `-Werror=redundant-decls` by applying the below patch:

```diff
diff --git a/SConstruct b/SConstruct
index 68abb178c..9a81f3dd8 100644
--- a/SConstruct
+++ b/SConstruct
@@ -4261,7 +4261,6 @@ class DXXCommon(LazyObjectConstructor):
             Werror + 'pointer-arith',
             Werror + 'cast-qual',
             Werror + 'missing-declarations',
-            Werror + 'redundant-decls',
             Werror + 'vla',
         ])
         env.Append(
```

The best long term fix would be for the compiler to stop rejecting its own headers.  As a compromise long term fix, I could try to exclude `-Wredundant-decls` on platforms where the compiler rejects its own headers.

---

Separately, I should warn you that even if you get past that, mingw-gcc-8 seems to die compiling `mveplay.cpp`; mingw-gcc-9 handles it correctly.

Also, the source you checked out would fail to build in `scores.cpp` on Win32.  I fixed that earlier today.

**Comment by AlumiuN** [comment] 2019-11-19 06:33
Thanks; interestingly, `mveplay.cpp` seems to compile for me, and the build process appears to succeed. A couple of notes:

- The link time optimization option causes a build failure for me with the following error:
```LD  d1x d1x-rebirth\d1x-rebirth.exe
lto1.exe: internal compiler error: in gen_subprogram_die, at dwarf2out.c:22668```
I'm not sure if this is an issue with anything in the code or if my toolchain just doesn't like doing it.
- Some aspect of the compilation process doesn't like spaces in file paths; LibPNG installed itself to my 'Program Files (x86)' directory and the error (which I forgot to copy) complained about not being able to find "\(x86\)\libpng\something", but it compiled fine when I copied somewhere else and updated the .pc files and PKG_CONFIG_PATH.
- I get a non-fatal warning when compiling D2X's gamepal.cpp:
```d2x-rebirth\main\gamepal.cpp: In function 'int d2x::load_palette(const char*, int, int)':
d2x-rebirth\main\gamepal.cpp:85:10: warning: 'char* strncpy(char*, const char*, size_t)' specified bound 13 equals destination size [-Wstringop-truncation]
   strncpy(last_palette_loaded,name,sizeof(last_palette_loaded));
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
d2x-rebirth\main\gamepal.cpp:104:10: warning: 'char* strncpy(char*, const char*, size_t)' specified bound 13 equals destination size [-Wstringop-truncation]
   strncpy(last_palette_loaded_pig,name,sizeof(last_palette_loaded_pig));
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~```
I'm not sure if strncpy has different behaviour in different places, but if it behaves how I think it does, I think those should have `sizeof(...) - 1` as the bound.

Anyway, other than those, it's working great! Thank you for your help :)

**Comment by vLKp** [comment] 2019-11-23 19:16
> interestingly, `mveplay.cpp` seems to compile for me, and the build process appears to succeed.

I guess the compiler bug that affected it was fixed in the release you used.  Good.

> * I'm not sure if this is an issue with anything in the code or if my toolchain just doesn't like doing it.

That is an internal error in your toolchain.  If I understood better what it rejected, I could try to change the code to work around the error.  It may not be worth the trouble though.

> * Some aspect of the compilation process doesn't like spaces in file paths

I am not surprised.  The standard way to use `pkg-config` is to run it, and paste its output into a shell command line.  That output must already be properly quoted when it is printed by `pkg-config`.  In turn, this means that the input file that tells `pkg-config` what to print needs proper quoting.  I can't add quotes because it is normal for there to be multiple distinct and useful parameters in the output, so treating the entire output as a single parameter is also wrong.

> * I'm not sure if strncpy has different behaviour in different places, but if it behaves how I think it does, I think those should have `sizeof(...) - 1` as the bound.

I agree that the code appears to be incorrect as written, but I partially disagree about the fix.  Changing the bound as you describe would preserve the old value of the final element of the array.  However, in the general case, there is no guarantee that the old value is reasonable.  To be truly safe, the bound should be reduced _and_ the code should explicitly reset the final element to a null byte.

---

Although you now have a working build, I am leaving this ticket open until I can more thoroughly address in the documentation the issues that were solved interactively here.  In particular:
- I think the documentation needs to address your original report about not knowing where to put supporting libraries.  Could you elaborate on how you solved that?  I understand that the `=/lib` gave you a hint about what to do.  Did you have a directory `C:\lib` that you put the files in?  If not, where was this directory, and how did you find it?
- The documentation would benefit from a warning about the spaces-in-paths problem.
- I should probably do something about the `-Wredundant-decls` issue too.  It would be nice if I could get a test case that reproduces the problem, so that I could write an SConf check for it.  Otherwise, I'll have to disable it for all Windows builds, which is unfortunate.

**Comment by AlumiuN** [comment] 2019-11-24 00:24
> > - I'm not sure if strncpy has different behaviour in different places, but if it behaves how I think it does, I think those should have sizeof(...) - 1 as the bound.

> I agree that the code appears to be incorrect as written, but I partially disagree about the fix. Changing the bound as you describe would preserve the old value of the final element of the array. However, in the general case, there is no guarantee that the old value is reasonable. To be truly safe, the bound should be reduced and the code should explicitly reset the final element to a null byte.

Ah, yes, I forgot that it doesn't behave how I think it does (namely, I forgot it doesn't automatically null terminate) :P

> - I think the documentation needs to address your original report about not knowing where to put supporting libraries. Could you elaborate on how you solved that? I understand that the =/lib gave you a hint about what to do. Did you have a directory C:\lib that you put the files in? If not, where was this directory, and how did you find it?

The only library I needed to shift (and as it now has a pkg-config option, I probably needn't have used) was PhysFS, and the "=/lib" directory corresponded to my toolchain's 'lib' directory (in this case, the rather unwieldy "D:\Programs\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\i686-w64-mingw32\lib"), which was the directory that had (most of) the other standard library files (for some reason it has a couple of lib directories in other places, but they only had a few files in them).

> - I should probably do something about the -Wredundant-decls issue too. It would be nice if I could get a test case that reproduces the problem, so that I could write an SConf check for it. Otherwise, I'll have to disable it for all Windows builds, which is unfortunate.

I don't get the same issue when compiling Wolf4SDL with -Wredundant-decls; I didn't explicitly test Rebirth and SDL1.2 with it enabled to see if the same issue was occuring, but given that's all I had to change to get it to build, that would suggest that there might be something else at play rather than it just being a platform issue. Unfortunately I no idea what that something else might be.

**Comment by AlumiuN** [comment] 2019-12-27 09:49
I've encountered another build issue in attemping to build with the latest commit, but I'm not sure on its source. The rather verbose error I get is as follows (I really hope this is collapsible):
```
similar\main\inferno.cpp:439:1: warning: character constant too long for its type
 static int main(int argc, char *argv[])
 ^~~~~~~~~
similar\main\inferno.cpp:441:1: warning: character constant too long for its type
  if (!PHYSFSX_init(argc, argv))
 ^~~~~~~~~
similar\main\inferno.cpp:731:1: warning: character constant too long for its type
 int main(int argc, char *argv[])
 ^~~~~~~~~
similar\main\inferno.cpp:746:1: warning: character constant too long for its type
  return dsx::main(argc, argv);
 ^~~~~~~~~
<command-line>: error: expected ',' or '...' before '\x62613666'
similar\main\inferno.cpp:429:43: note: in definition of macro 'DXX_RENAME_IDENTIFIER2'
 #define DXX_RENAME_IDENTIFIER2(I,N) I##$##N
                                           ^
similar\main\inferno.cpp:431:14: note: in expansion of macro 'DXX_RENAME_IDENTIFIER'
 #define argc DXX_RENAME_IDENTIFIER(argc_gc, DXX_git_commit)
              ^~~~~~~~~~~~~~~~~~~~~
similar\main\inferno.cpp:431:45: note: in expansion of macro 'DXX_git_commit'
 #define argc DXX_RENAME_IDENTIFIER(argc_gc, DXX_git_commit)
                                             ^~~~~~~~~~~~~~
similar\main\inferno.cpp:439:21: note: in expansion of macro 'argc'
 static int main(int argc, char *argv[])
                     ^~~~
similar\main\inferno.cpp: In function 'int d1x::SDL_main(int)':
<command-line>: error: expected ')' before '\x62613666'
similar\main\inferno.cpp:429:43: note: in definition of macro 'DXX_RENAME_IDENTIFIER2'
 #define DXX_RENAME_IDENTIFIER2(I,N) I##$##N
                                           ^
similar\main\inferno.cpp:431:14: note: in expansion of macro 'DXX_RENAME_IDENTIFIER'
 #define argc DXX_RENAME_IDENTIFIER(argc_gc, DXX_git_commit)
              ^~~~~~~~~~~~~~~~~~~~~
similar\main\inferno.cpp:431:45: note: in expansion of macro 'DXX_git_commit'
 #define argc DXX_RENAME_IDENTIFIER(argc_gc, DXX_git_commit)
                                             ^~~~~~~~~~~~~~
similar\main\inferno.cpp:441:20: note: in expansion of macro 'argc'
  if (!PHYSFSX_init(argc, argv))
                    ^~~~
similar\main\inferno.cpp:441:19: note: to match this '('
  if (!PHYSFSX_init(argc, argv))
                   ^
similar\main\inferno.cpp:432:36: error: 'argv_gd$MC42MC4wLWJldGEyLTYwNi1nMDVhNTRlZjdjMTdlKg─╜─╜' was not declared in this scope
 #define argv DXX_RENAME_IDENTIFIER(argv_gd, DXX_git_describe)
                                    ^~~~~~~
similar\main\inferno.cpp:429:37: note: in definition of macro 'DXX_RENAME_IDENTIFIER2'
 #define DXX_RENAME_IDENTIFIER2(I,N) I##$##N
                                     ^
similar\main\inferno.cpp:432:14: note: in expansion of macro 'DXX_RENAME_IDENTIFIER'
 #define argv DXX_RENAME_IDENTIFIER(argv_gd, DXX_git_describe)
              ^~~~~~~~~~~~~~~~~~~~~
similar\main\inferno.cpp:441:26: note: in expansion of macro 'argv'
  if (!PHYSFSX_init(argc, argv))
                          ^~~~
similar\main\inferno.cpp:432:36: error: 'argv_gd$MC42MC4wLWJldGEyLTYwNi1nMDVhNTRlZjdjMTdlKg─╜─╜' was not declared in this scope
 #define argv DXX_RENAME_IDENTIFIER(argv_gd, DXX_git_describe)
                                    ^~~~~~~
similar\main\inferno.cpp:429:37: note: in definition of macro 'DXX_RENAME_IDENTIFIER2'
 #define DXX_RENAME_IDENTIFIER2(I,N) I##$##N
                                     ^
similar\main\inferno.cpp:432:14: note: in expansion of macro 'DXX_RENAME_IDENTIFIER'
 #define argv DXX_RENAME_IDENTIFIER(argv_gd, DXX_git_describe)
              ^~~~~~~~~~~~~~~~~~~~~
similar\main\inferno.cpp:428:18: note: in expansion of macro 'argv'
 #define PROGNAME argv[0]
                  ^~~~
similar\main\inferno.cpp:457:70: note: in expansion of macro 'PROGNAME'
  printf("\nType '%s -help' for a list of command-line options.\n\n", PROGNAME);
                                                                      ^~~~~~~~
similar\main\inferno.cpp: At global scope:
<command-line>: error: expected ',' or '...' before '\x62613666'
similar\main\inferno.cpp:429:43: note: in definition of macro 'DXX_RENAME_IDENTIFIER2'
 #define DXX_RENAME_IDENTIFIER2(I,N) I##$##N
                                           ^
similar\main\inferno.cpp:431:14: note: in expansion of macro 'DXX_RENAME_IDENTIFIER'
 #define argc DXX_RENAME_IDENTIFIER(argc_gc, DXX_git_commit)
              ^~~~~~~~~~~~~~~~~~~~~
similar\main\inferno.cpp:431:45: note: in expansion of macro 'DXX_git_commit'
 #define argc DXX_RENAME_IDENTIFIER(argc_gc, DXX_git_commit)
                                             ^~~~~~~~~~~~~~
similar\main\inferno.cpp:731:14: note: in expansion of macro 'argc'
 int main(int argc, char *argv[])
              ^~~~
In file included from D:\Libraries\SDL\include\SDL/SDL.h:30,
                 from similar\main\inferno.cpp:46:
D:\Libraries\SDL\include\SDL/SDL_main.h:54:14: error: no previous declaration for 'int SDL_main(int)' [-Werror=missing-declarations]
 #define main SDL_main
              ^~~~~~~~
similar\main\inferno.cpp:731:5: note: in expansion of macro 'main'
 int main(int argc, char *argv[])
     ^~~~
similar\main\inferno.cpp: In function 'int SDL_main(int)':
<command-line>: error: expected ')' before '\x62613666'
similar\main\inferno.cpp:429:43: note: in definition of macro 'DXX_RENAME_IDENTIFIER2'
 #define DXX_RENAME_IDENTIFIER2(I,N) I##$##N
                                           ^
similar\main\inferno.cpp:431:14: note: in expansion of macro 'DXX_RENAME_IDENTIFIER'
 #define argc DXX_RENAME_IDENTIFIER(argc_gc, DXX_git_commit)
              ^~~~~~~~~~~~~~~~~~~~~
similar\main\inferno.cpp:431:45: note: in expansion of macro 'DXX_git_commit'
 #define argc DXX_RENAME_IDENTIFIER(argc_gc, DXX_git_commit)
                                             ^~~~~~~~~~~~~~
similar\main\inferno.cpp:746:19: note: in expansion of macro 'argc'
  return dsx::main(argc, argv);
                   ^~~~
similar\main\inferno.cpp:746:18: note: to match this '('
  return dsx::main(argc, argv);
                  ^
similar\main\inferno.cpp:432:36: error: 'argv_gd$MC42MC4wLWJldGEyLTYwNi1nMDVhNTRlZjdjMTdlKg─╜─╜' was not declared in this scope
 #define argv DXX_RENAME_IDENTIFIER(argv_gd, DXX_git_describe)
                                    ^~~~~~~
similar\main\inferno.cpp:429:37: note: in definition of macro 'DXX_RENAME_IDENTIFIER2'
 #define DXX_RENAME_IDENTIFIER2(I,N) I##$##N
                                     ^
similar\main\inferno.cpp:432:14: note: in expansion of macro 'DXX_RENAME_IDENTIFIER'
 #define argv DXX_RENAME_IDENTIFIER(argv_gd, DXX_git_describe)
              ^~~~~~~~~~~~~~~~~~~~~
similar\main\inferno.cpp:746:25: note: in expansion of macro 'argv'
  return dsx::main(argc, argv);
                         ^~~~
cc1plus.exe: some warnings being treated as errors
scons: *** [similar\main\.d1x-rebirth.inferno.o] Error 1
scons: building terminated because of errors.
Failed target count: total=1; targets with enable_build_failure_summary=1: 1
Failed node list:
        similar\main\.d1x-rebirth.inferno.o
Failed command list:
 g++ -c -g -O2 -ftabstop=4 -Wall -Werror=extra -Werror=format=2 -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -fno-omit-frame-pointer -funsigned-char -std=gnu++14 -Werror=unused -Werror=useless-cast -Wno-implicit-fallthrough -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wsuggest-attribute=noreturn -Wlogical-op -Wold-style-cast -Wno-sign-compare -D_WIN32 -DWIN32_LEAN_AND_MEAN -DPHYSFS_DEPRECATED= -DNDEBUG -DRELEASE -D_WIN32_WINNT=1536 -DDXX_BUILD_DESCENT_I -D__STDC_FORMAT_MACROS -DDXX_USE_SHAREPATH=0 -DDXX_git_commit=b'05a54ef7c17eeb749db4e83793252339dcc0ba6f' -DDXX_git_describe="MC42MC4wLWJldGEyLTYwNi1nMDVhNTRlZjdjMTdlKg\u013d\u013d" -Icommon\include -Icommon\main -I. -ID:\Libraries\libPNG\include\libpng16 -ID:\Libraries\SDL\include\SDL -Id1x-rebirth\main "similar\main\inferno.cpp" -o "similar\main\.d1x-rebirth.inferno.o"
```

This only occurs when I clone the repository using desktop Git, but doesn't if I just download the source as a whole from Github. I've tried to follow the cause back to something that might cause it, but all I can tell is that it's reading information about the current repository version from the .git directory (which is not present if the source is downloaded as a ZIP) and I think it's getting mangled somewhere in the process.

**Comment by vLKp** [comment] 2019-12-28 21:45
I pushed changes for the documentation to address the bullet points I identified above.  I removed `-Wredundant-decls` from the `SConstruct` default options since I don't have a test case for which systems will or will not choke on it.

---

No, the error is not collapsible, but that is fine.  I am a C++ programmer.  We are accustomed to long backtraces when templates go wrong. ;)

Yes, this can only happen when you have a Git repository available in the build area, since `SConstruct` reads the current commit ID from that.  I do not get this error, and the error itself looks quite strange.  It looks like you patched `SConstruct` to remove `-Wredundant-decls`, which would have made your working copy unclean, which would account for the presence of a trailer.  However, the trailer should have been a `*` or a `+` before encoding.  Somehow, a special high value was appended to the commit ID instead.  If you had posted the `SConf` output, this would be a bit easier.  If I had to guess, I would say your compiler seemed to accept extended identifiers without a special option, but then actually passing them on the command line mangled them.  The values shown in the output are not what they should have been.  I will look at finding some other way to pass base64 encoded text here.

**Comment by AlumiuN** [comment] 2019-12-28 23:08
Here's the SConf.log. I did indeed remove the -Wredundant-decls.
[sconf.log](https://github.com/dxx-rebirth/dxx-rebirth/files/4007550/sconf.log)

**Comment by vLKp** [comment] 2019-12-29 22:28
I pushed a change to remove use of the extended identifiers, which should solve that problem.  This ticket was originally about the install documentation, which I think I addressed above.  If you think the documentation needs more work, please reopen this issue.  If you still have problems with the build failing, please open a new issue about that.

**Closed by vLKp** 2019-12-29 22:28 UTC
Labels: build-failure
