### ISSUE TITLE
SDL2: 'Ship Destroyed' leads to small window 'at-death' sequence...

### ISSUE THREAD

**Issue by andrew-strong** [dxx-rebirth/dxx-rebirth#399] opened 2018-08-04 08:18 UTC
### Environment

Built from git:
commit eff80c2d130dd4cfab436b31f09bcf030dacd373

#### Operating System Environment

* [x] Slackware -current

#### CPU environment

* [x] x86\_64 (64-bit Intel/AMD)

#### Game environment

d2x-rebirth compiled against sdl2

### Description

When the ship is destroyed, and playing in a non-windowed environment, the small
movie that plays on 'Ship Destroyed': spinning spilt weapons, robots flying in
the wreckage etc is played in a much smaller window at the top left of the screen.
The remaining screen real estate is black.

When running with `-debug` the following can be seen:

```
Ship destroyed!
Sending event EVENT_KEY_COMMAND:      ESC
GUIDE-BOT: Coming back to get you.
Sending event EVENT_KEY_RELEASE:      ESC
Sending event EVENT_KEY_COMMAND:      ESC
common/arch/sdl/window.cpp:47: sending event 13 to window of dimensions 1920x1080
common/arch/sdl/window.cpp:51: sending event 11 to window of dimensions 603x458
common/arch/sdl/window.cpp:55: sending event 12 to window of dimensions 603x458
Sending event EVENT_KEY_RELEASE:      ESC
Sending event EVENT_KEY_COMMAND:      ENTER
common/arch/sdl/window.cpp:92: sending event 13 to window of dimensions 603x458
common/arch/sdl/window.cpp:97: sending event 15 to window of dimensions 603x458
common/arch/sdl/window.cpp:118: sending event 12 to window of dimensions 1920x1080
common/arch/sdl/window.cpp:92: sending event 13 to window of dimensions 1920x1080
common/arch/sdl/window.cpp:97: sending event 15 to window of dimensions 1920x1080
common/arch/sdl/window.cpp:118: sending event 12 to window of dimensions 733x793
Sending event EVENT_KEY_RELEASE:      ENTER
Sending event EVENT_KEY_COMMAND:      Q
Sending event EVENT_KEY_RELEASE:      Q
Sending event EVENT_KEY_COMMAND:      ENTER
common/arch/sdl/window.cpp:92: sending event 13 to window of dimensions 733x793
common/arch/sdl/window.cpp:97: sending event 15 to window of dimensions 733x793
Cleanup...
andrew@illium~$ 

```
I am not sure how to interpret the changing screen sizes given in this
debug output but I am hoping this points to the problem at least.

Please let me know if I need to provide more information, particularly if this
issue cannot be reproduced.

#### Regression status

Not seen in the sld1 version of d2x-rebirth although I have
not recompiled against older sdl to test this assertion.

### Steps to Reproduce

On d2x-rebirth I can consistently trigger this issue by:

 1. Starting the game
 2. Allowing the ship to be destroyed
 3. Observing the shrunken screen for 'Destroyed Ship' mini-movie.

* Engines affected:
  * [ ] D1X-Rebirth
  * [x] D2X-Rebirth
 
 I have not tested with d1x-rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative
  
 I have only tested single player.

**Comment by vLKp** [comment] 2018-08-04 21:49
I am not surprised something like this would happen, considering the difference between SDL1's full screen (where your monitor resolution is set to game window size) versus SDL2's full screen (where the game window is supposed to scale to your monitor).

Confirmed.  I was about to report that I could not reproduce this, but I tried clearing the resolution data in my `descent.cfg`, and that allowed the problem to appear.  Normally, my resolution data calls for a window that fills my screen even when I don't play in fullscreen mode, which masks this issue.  It looks like the at-death sequence switches to a window sized to your saved resolution, but keeps the SDL window maximized.

**Comment by andrew-strong** [comment] 2018-08-06 23:17
Thanks for looking at this issue. Certainly as you have suggested setting a full screen  (1920x1080 in my case) in `descent.cfg` provides a very reasonable work-around with the at-death sequence remaining a reasonable size

And thanks again for your work on dxx-rebirth!

**Comment by vLKp** [comment] 2018-08-22 02:10
I wasn't thinking of it as a workaround so much as a reason why I missed it originally, but I am glad that it suffices for you.  I will try to fix this properly as part of other SDL2 related issues, but since it only appears when the player dies and does not interfere with gameplay, it is low priority.  As an alternative workaround, try not to die. :wink:

**Comment by andrew-strong** [comment] 2018-08-23 00:45
The alternative workaround (try not to die) is an excellent suggestion and one I will work on :)

**Comment by zicodxx** [comment] 2019-08-22 10:03
@andrew-strong @vLKp Is any of you still able to reproduce this issue? I wanted to take a look at it, but deleting descent.cfg and playing the game in window mode, I am unable to reproduce this. The letterbox effect (which I assume initially caused this issue) looks accurate on my end as well. Has this maybe been fixed over time?

**Comment by andrew-strong** [comment] 2019-08-25 00:02
@zicodxx The issue is still reproducible with the current development version, I have just rebuilt today to test. It is however not seen in windowed mode but rather in full screened mode. It becomes more apparent of the resolution in descent.cfg is set a little lower than it really should be...

**Comment by tycho** [comment] 2020-02-08 01:58
I just saw this issue and it appears that the cockpit mode `CM_LETTERBOX` gets the game screen mode (usually 640x480) instead of the actually set SDL2 video mode (the native display mode). This makes the death sequence render properly for me, though it might not be the correct fix:

```diff
diff --git a/similar/main/game.cpp b/similar/main/game.cpp
index b19116edc..fa2f5e45b 100644
--- a/similar/main/game.cpp
+++ b/similar/main/game.cpp
@@ -239,8 +239,8 @@ void init_cockpit()
                        break;
 
                case CM_LETTERBOX:      {
-                       const unsigned gsm_height = SM_H(Game_screen_mode);
-                       const unsigned w = SM_W(Game_screen_mode);
+                       const unsigned gsm_height = grd_curscreen->get_screen_height();
+                       const unsigned w = grd_curscreen->get_screen_width();
                        const unsigned h = (gsm_height * 3) / 4; // true letterbox size (16:9)
                        const unsigned x = 0;
                        const unsigned y = (gsm_height - h) / 2;
```

**Comment by vLKp** [comment] 2020-03-28 18:00
The above commit adopts @tycho's suggestion.  It fixes both the reported problem with the at-death window, and the Descent 1 exit tunnel playing improperly, since that also used letterbox mode.

Closing.  Please reopen if you find a path which can still cause the undersized window.

**Closed by vLKp** 2020-03-28 18:00 UTC
Labels: bug, sdl2

**Comment by andrew-strong** [comment] 2020-03-29 02:38
Confirmed fix on my system... Thanks :)
