### ISSUE TITLE
Crash when port line is left blank

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#246] opened 2016-10-11 20:25 UTC
If the port in the advanced options menu is left blank, the game crashes. (I can't get a backtrace now, but will later if you need it.)

**Comment by vLKp** [comment] 2016-10-12 02:11
I cannot reproduce this.  I get the expected messagebox telling me that blank is not a legal input.

0.58.1-d2x-7027-g1af6507

**Comment by vLKp** [comment] 2016-10-15 01:03
Marking this as invalid since I cannot reproduce it with the steps provided, and there is no other data upon which to base a speculative fix.

**Comment by Mako88** [comment] 2016-10-15 02:00
I'll be able to test this again tomorrow evening and give you some more concrete data.

**Comment by Mako88** [comment] 2016-10-15 14:32
I still haven't had an opportunity to get a backtrace, however, to reproduce the crash you have to push an arrow key while the error message box is up. After pushing an arrow key, you won't be able to hit enter to close the message box and the game freezes.

**Comment by vLKp** [comment] 2016-10-15 17:38
I see it now.  It is a hang when tail call optimization turns an infinite recursion into an infinite loop.  It is a crash when tail call optimization does not apply, since `newmenu_scroll` calls itself recursively until it exhausts the stack.  In both cases, it occurs only if you try to loop around and have exactly one element in the menu, in this case the OK choice.  If the user dismisses the menu without attempting to scroll the selection, everything is fine.  The critical part is that you **must** scroll, such as by pressing an arrow key (as described in [comment #3](#issuecomment-253987715)), to trigger the bug.

**Comment by vLKp** [comment] 2016-10-15 17:55
Fixed in 2d54a0c57d9ca1cc29d7105cbba03ebdc393eef4.

**Closed by vLKp** 2016-10-15 17:55 UTC
Labels: bug
