### ISSUE TITLE
The 20220823 source tarball version cannot play multiplayer with players using the 20220823 windows version

### ISSUE THREAD

**Issue by stev6502** [dxx-rebirth/dxx-rebirth#660] opened 2022-08-27 13:36 UTC
Using the downloads from https://www.dxx-rebirth.com/download-dxx-rebirth/
commit: [366b048](https://github.com/dxx-rebirth/dxx-rebirth/commit/366b048879d62a3096357509fc856dde1abfb7ff), date: 2022/08/23

[[DOWNLOAD](https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20220823-src.tar.xz)] Source Tarball (Linux, BSD and other *NIX-style systems)
[[DOWNLOAD](https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20220823-win.zip)] Windows 7, 8, 8.1, 10 package

Download source tarball and compiled using Fedora 36 with SDL2
cd <folder where source is>
scons-3 d1x=1 d2x=1 sdl2=1
sudo scons-3 install d1x=1 d2x=1 sdl2=1
compiled and installs without any errors 
d1x-rebirth and d2x-rebirth run without any errors

But, as I was not able to join multiplayer games hosted by players using the Windows version and they cannot join my multiplayer games this ended up with me here raising a bug

Can someone else try this:  compile the source tarball using the links above for Linux and test it with someone using the windows version and verify that I am not going crazy.  Thank you.

temporary workaround is
use the Windows zipfile and run it with Wine using Linux 

The error message when trying to do multiplayer (from Windows players) joining my Linux hosted game
Error:  No response by host
Possible reasons
* no game on XXX.XXX.XXX.XXX (anymore)
* host port XXXXX is not open
* game is hosted on a different port
* host uses a game version I do not understand

the test games appeared on the dxx-rebirth tracker

This was not happening before updating to the 20220823 release

**Comment by vLKp** [comment] 2022-08-27 18:51
I do not have a Windows test partner available, but I fetched the source and examined the binaries.  I do not see why this would happen.  As best I can tell, the Windows binaries have the same protocol version as the source code says they should have.  They also claim to be built from the same commit.  The `SConstruct` in the source archive has a header stating it came from commit 366b048879d62a3096357509fc856dde1abfb7ff.  The Windows binaries have a global variable stating they came from `0.60.0-beta2-2046-g366b048879d6`:
```
(gdb) p -elements unlimited -- g_descent_version                                
$1 = "D1X-Rebirth v0.61\\x20\\x30.60.0-beta2-2046-g366b048879d6"
```

```
$ git log -1 0.60.0-beta2-2046-g366b048879d6
commit 366b048879d62a3096357509fc856dde1abfb7ff
```

I also examined the content of the network messages in the Windows binary; it is what I would expect for the protocol version the game claims to have been built from.

---

Can a Linux guest join a game hosted by a Linux user?  This would rule out basic problems with Linux hosts.
What packets are sent/received by the host during the failed join?
Do I understand correctly that the Linux user, upon using Wine to run the posted Windows build, was able to play with Windows users running that same build?  This would rule out basic issues with one side running a game build other than the intended one.

**Comment by stev6502** [comment] 2022-08-28 00:32
To test this further I setup a VM with Windows 7 (using the Linux host) and put the Windows DXX-Rebirth on it.
Using the Linux host,  run DXX-Rebirth (Descent 1) and begin a multiplayer game which appeared on the DXX-Rebirth tracker.  With the Windows 7 VM using the DXX-Rebirth Windows download, tried to join the multiplayer game and cannot join.  Reproduces the issue described above.

I did it this way to make sure that this is not being caused by a network issue

Could it be that the Download link on https://www.dxx-rebirth.com/download-dxx-rebirth/ for the Source Tarball (Linux, BSD and other *NIX-style systems) is wrong somehow?

For Linux it shows the version as D1X-REBIRTH V0.61
For the Windows 7 VM it shows the version as D1X-REBIRTH V0.61\X20\X30.60.0-BETA2-2046-G366B048879D6
The version strings do not match when I downloaded from https://www.dxx-rebirth.com/download-dxx-rebirth/

**Comment by stev6502** [comment] 2022-08-28 00:59
Extra information:
Using the Linux host and Wine to run the Windows version from Linux,  start a multiplayer game and use the Windows 7 VM and joined the game successfully.   I had one on my left monitor and one on my right monitor and managed to play a multiplayer game against myself   [both showed the version strings as D1X-REBIRTH V0.61\X20\X30.60.0-BETA2-2046-G366B048879D6]

it appears the download at https://www.dxx-rebirth.com/download-dxx-rebirth/ for the Source Tarball (Linux, BSD and other *NIX-style systems) has an issue

**Comment by vLKp** [comment] 2022-08-28 01:05
The Linux source tarball unfortunately lacks `.git`, so the build system cannot determine and embed the full version in the Linux executable when you build for yourself.  The Windows build is apparently built in a full git clone, so it has access to the full version history and embeds the qualified tag.  If you can do so readily, it would be interesting to use the source tarball to compile a Windows build of the game and compare how that behaves relative to the prebuilt Windows build.

It's possible that the source download is wrong, but I think it is right.  I checked out the claimed commit and compared it to the source tarball.  There are differences, but only in non-source files, so I think it effectively is the commit it claims to be.

**Comment by stev6502** [comment] 2022-08-28 04:25
I dont know enough about Windows to compile the code under that platform (for Linux it is easy).  Alternatively I can use Wine to run the windows binary from linux and can continue playing the retro version which is not affected by any of this

**Comment by vLKp** [comment] 2022-08-28 16:29
@zicodxx: when you built this snapshot, was there anything odd that might explain the reported behavior?

@stev6502: if you have a mingw cross-compiler on Linux, you can cross-compile to Windows.  That is how I test that the Windows build still works.  You will need to install the supporting packages through the cross environment as well.

My candidate explanations, based on the available data:
- The Windows build is not what it claims to be, and therefore speaks a different protocol version.  Static inspection of the binary leads me to believe it speaks the protocol it should for that source code commit, so this seems unlikely.
- Cross-play between Linux and Windows builds from the same source code is broken in that revision.  This would be strange since none of the negotiation code is supposed to be platform-sensitive.
- Linux builds cannot host in that revision.  This also seems unlikely.  I can test this, and just did.  Hosting a game from Linux and then joining that game from Linux worked fine.

At this point, I do not see what I can do for you with the available information.  I don't have a Windows test player to try this.  I don't see anything wrong in static inspection of the binaries.  If you want to continue this, I need you to collect more information.  Ideally, I would like a `tcpdump` capture of the game's traffic when a Linux user hosts and the Windows user tries and fails to join.  Failing that, you could try capturing the game log from both sides when the game is invoked as `d1x-rebirth -debug`, but based on some quick samples of that here, I am doubtful it will show what I need.

**Comment by agibson2** [comment] 2022-08-28 20:16
Any chance there is something else wrong?  I played with dxx rebirth with others on Discord.  I didn't ask what OS they were using but I suspect it was Windows.  Port forwarding and source port translation doesn't go well with descent at times.... Is it possible the problem is related to that?  It is also possible the the person on Linux just happened to be behind a home router that didn't mess with source port (PAT) or was setup to forward ports 1 to 1 NAT and the person on Windows did not.

**Comment by vLKp** [comment] 2022-08-28 21:36
Rebirth should work fine with port forwarding.  Back when I did multiplayer over the Internet, that is how I had it set up.

Prior to a mention in a recent issue, I was not aware of Luxtorpeda.  Even now, I have not used it, as it appears to rely on Steam, which I do not use.  As such, I can offer no support specific to it.

I suggest that instead of referring to "the same timestamp of source", you refer to a specific immutable identifier, such as a git commit.  This will remain consistent for future readers, and can be resolved without exploring the Luxtorpeda site.  As is, I cannot tell from this ticket or from Luxtorpeda's documentation what version(s) of Rebirth are available to Luxtorpeda users.  I searched their issue tracker and found https://github.com/luxtorpeda-dev/packages/issues/711, filed by @agibson2 a few weeks ago, and the response in that issue from the maintainer indicates that Luxtorpeda was updated to the then-current commit, but no details on what that update required.  (As a tip for any committers reading this, referencing the issue in your git log message will create an automatic cross-reference, so that issue readers can find the relevant commits.)  On further exploration, I found the build script at  https://github.com/luxtorpeda-dev/packages/blob/6d8a8300d7a9b87f8e9050e0093c6e97c9f700b7/engines/dxx-rebirth/build.sh .  That is a pinned version.  The corresponding path in `master` is https://github.com/luxtorpeda-dev/packages/blob/master/engines/dxx-rebirth/build.sh .  From the build script, I can see what Rebirth commit is used by Luxtorpeda - and that the `git clone` is done in an inefficient way.

> I do wish any release on the dxx-rebirth website ...

Could you elaborate here?  I already take care to update the multiplayer protocol version number whenever I make an incompatible change.  Additionally, any builds done from a git checkout will embed `git describe` data in the version string, from which recipients can find the exact git commit used.  I have not yet had an instance where that output was insufficient, but if embedding also the exact git commit would be useful, that is easy to add.

**Comment by agibson2** [comment] 2022-08-28 22:05
Luxtorpeda at first had an old version from a long time ago built so it wasn't compatible multiplayer.  I suggested that they update it a few weeks ago and they seemed to look at your website to know what version to build against to be compatible with the Windows build that is also published on the dxx-rebirth website.  I didn't realize that the protocol is being changed often lately so hopefully they can keep up.  You do post the git commit # for the build so hopefully they can automate it.

As for port forwarding, is there a write-up about how it is implemented in dxx-rebirth?  I recall finding something on it a few weeks ago but it was more of an overview.  I would better be able to respond knowing that.  Ports can get confusing to discuss.  I had to change my firewall (pfSense) to not translate the source port when sending the packet outbound otherwise clients were trying to use a random port (that isn't forwarded).  I only forwarded 42424.  I don't us UPnP automatic port forwarding which allows apps to tell routers/firewalls what port to open up.  I want to know what is being opened up on the firewall so I don't enable/allow that on pfsense.  Not sure if dxx-rebirth uses that protocol or not for opening ports on firewalls/routers though.

Using git commit instead of timestamp makes sense... I will refer to the git commit from now on.

As for the version stuff, I just figured that anytime there was a protocol mismatch, the version of the exe would also be bumped instead of both versions being 1.6.1 for example (or whatever the version is).  Not a big deal... just an observation that the version of the program doesn't change but the protocol does.  Just having someone say what version of the app they are using to make sure they are the same isn't enough because the version doesn't appear to be getting changed for new releases.  To be clear, that isn't a problem... just an observation and was a surprise to me on how things are done.  No wrong or right way... just the way your dev teams wants to do it :).

**Comment by vLKp** [comment] 2022-08-28 22:50
> I didn't realize that the protocol is being changed often lately so hopefully they can keep up.

Protocol version bumps are irregular, and happen as needed.  I try to batch them up when I can (making multiple protocol-breaking changes all at once, rather than releasing multiple breaks over a span of a few weeks).  You can see the recent bumps using a `git log` command:

```
$ git log --pretty='%ad %s' -GMULTI_PROTO_VERSION 2b058c7150000169af810fc3c8311d695e4eb829.. -- common/main/multi.h
Sat Aug 20 19:32:38 2022 -0500 Feat: Pitch unlocker
Sat Jul 9 13:39:29 2022 +0000 Remove obsolete MULTI_FIRE field `nfires`
Sun Jun 5 17:44:53 2022 +0000 Simplify UPID_QUIT_JOINING
Sat Feb 5 13:30:56 2022 +0000 Improve vulcan/gauss pickup rules
Sat Aug 1 18:29:01 2020 +0000 Fix hoard orb handling on player death
Wed Jun 10 02:25:33 2020 +0000 Increase multiplayer protocol version number
Thu Jun 27 03:26:20 2019 +0000 Add experimental support for guidebot in multiplayer
Mon Dec 3 04:25:11 2018 +0000 Add experimental support for larger cooperative games
Sun May 13 03:14:34 2018 +0000 Prevent stacking weapon rotation sounds
Thu Apr 12 04:19:35 2018 +0000 Add support for shuffling powerups in anarchy games
```

This finds every commit which touches the relevant `#define` in `common/main/multi.h`, and shows the date on which it was authored and a subject from the log message.  From this, it looks like we didn't change the protocol at all in 2021, but touched it several times this year.  2b058c7150000169af810fc3c8311d695e4eb829 is an arbitrarily chosen commit in the past, to avoid the history running all the way back to the beginning.  You could pick something farther back if you want to trace more changes.

> You do post the git commit # for the build so hopefully they can automate it.

Technically I don't post anything. ;)  @zicodxx creates the Windows binaries and updates the website.  However, he is generally amenable to reasonable requests, so if there are minor changes that would help Luxtorpeda handle this better, I'd be happy to hear about them.

> As for port forwarding, is there a write-up about how it is implemented in dxx-rebirth?

I don't recall one, but there is nothing special.  Rebirth listens on UDP port 42424 if not told otherwise.  The network model is hub-and-spoke, so as long as would-be guests can get a packet to the host's listening socket, and the host can respond symmetrically, everything should work.  I ran my personal games on a different port than 42424, and it worked fine.  My guests were behind NAT devices that did not allow unsolicited incoming traffic, so they could not host, but they could join my game without special setup.  I was behind a NAT device that did require one time special setup from me to forward my game port from my public IP to my gaming computer.  As far as I know, Rebirth does not care what port its peers think it is using, so a random public port should be fine _if_ the NAT device can get the responses back to Rebirth.  Stateful NAT devices should handle this automatically.  A stateless one would not interact well with random port remapping.  This issue isn't a good place to discuss that, but if you'd like to discuss it, I'm happy to entertain that discussion in a separate issue.

Rebirth does not use UPnP, so it does not matter whether your router allows that.

> As for the version stuff, ...

Back before I joined the project, zico made regular releases and updated the version number with each release, much as you describe.  I write and publish code, but I don't deal with releases directly, so I don't touch the version number.  The project has not had a full release in quite a while, but zico provides snapshots of pre-release code as a courtesy to the community.  Since these are considered snapshots, they do not come with their own version number.

Builds with access to a git tree embed `git describe` data, but this doesn't directly show a timestamp (though it can be used to derive one), and not everyone seems to know how to interpret this data.  I see a few options:

- Do nothing.
- Ask zico to routinely bump the version number when he makes snapshot releases.  If we do this, we may want to go to making heavier weight releases, complete with git tags, encouraging Linux distributions to package those tags, and so on.
- I intermittently bump the version number when it seems like a good idea to me.  (I bump the protocol number when I need to do so to avoid networking bugs, but that number isn't readily visible to users.)
- I change the data visible in the program to more clearly communicate the date of the git commit from which it was drawn.  If you like this option, please indicate where you would want to see the data, and whether this should be in addition to the `git describe` output or present only when `git describe` is missing.  (I don't want to remove `git describe` data when that information is available, but I am fine with supplementing it.)  As a recap/reminder, the `git describe` data is: `0.60.0-beta2-2199-gd6f9b6fd7af0`, though the numbers will vary over time.

For historical reasons, the version number is not amenable to embedding a date stamp the way some projects do, so we cannot go to calling our releases 20220828, etc.  We could probably make that work if we went split the date into major/minor/micro versions, but I haven't tried that.  Under that scheme, all releases this year would be major version 2022 (up from `0` today).  Releases this month would be minor version 8 (down from `61` today).  Next month would be minor version 9, and so on.

**Comment by d10sfan** [comment] 2022-08-29 02:40
@vLKp 

Hello, I'm the maintainer of luxtorpeda-dev! Appreciate the project that you all work on. 

Because of the need for a consistent environment across different systems, I compile almost all of the Linux engines using a common runtime. I usually use github releases or rely on people notifying me about new changes.

For the releases themselves, if there was a possibility for you all to also create github releases on new releases, I could subscribe and have github email me whenever there's a new release. If that would not work, let me know, and I may be able to come up with some other way to determine if there's a new release, such as if your main branch has some signal that I could look for.

**Comment by stev6502** [comment] 2022-08-29 10:05
Ok this is interesting,  I found a solution with some creative thinking:
As I have access to a commercial VPN service, I have put that to use and established a VPN connection.  My VPN configuration has been configured to redirect all inbound traffic (TCP/UDP) on port 16116 to my computer.

Scenario 1:   Using Wine (Linux host) run the Windows binary and do multiplayer with another player using a Windows PC
This tested ok and worked,  we were able to play a 2 player co-op multiplayer game using d1x-rebirth with this configuration
My Linux command line to do this was:
# Use for Wine
cd /home/stev/.wine/drive_c/Games/DXX-Rebirth/D1X-Rebirth
wine ./d1x-rebirth.exe -tracker_hostaddr tracker.dxx-rebirth.com -maxfps 60 -debug -verbose -tracker_hostport 9999 -udp_hostport 16116 -udp_myport 16116

Scenario 2:  Repeat the above with the compiled d1 rebirth (native Linux version)
This also tested ok as above
My Linux command line to do this was  [this runs the compiled binary from /usr/local/bin/d1x-rebirth]
# Use for Linux
cd ~/.d1x-rebirth
d1x-rebirth -hogdir /home/stev/games/descent -tracker_hostaddr tracker.dxx-rebirth.com -maxfps 60 -debug -tracker_hostport 9999 -udp_hostport 16116 -udp_myport 16116

**Comment by stev6502** [comment] 2022-08-29 10:07
Unless I use the VPN configuration (explained above) I cannot join or host any multiplayer games with dxx-rebirth.
I did not expect this to happen and are surprised by this outcome

**Comment by vLKp** [comment] 2022-08-29 15:15
@d10sfan wrote:
> For the releases themselves, if there was a possibility for you all to also create github releases on new releases 

I am not aware of a reason this would not work, but I have not looked at it before.  Presently, @zicodxx creates the Windows snapshots as he sees fit and does not specifically coordinate them with me.  To get the Github releases object created, either @zicodxx would need to do it when he creates the Windows snapshot or I would need to notice he has posted one and go create the release object.

---

@stev6502 wrote:
> ...

That is quite strange.  Do you have some security module that is denying Linux Rebirth access to receive incoming traffic, but allowing that same traffic when you play through Wine?  _Joining_ a game ought to work even from behind a NAT device that permits no unsolicited inbound traffic, since the host does not send unsolicited traffic to the guest.  The host only responds to the traffic sent by the guest, which should cause the NAT device to consider the traffic as solicited and allow it through.  Your experience suggests that some network step does not allow _any_ Rebirth traffic to flow inbound, but _only_ when using the Linux Rebirth build.  Switching to the Windows Rebirth build through Wine ought not make a difference if the NAT device is guilty, which suggests something on the machine where this is run, such as an SELinux policy.  If Linux Rebirth's networking were completely broken, it should not start working when you activate the VPN.  Do you have SELinux enabled?  If yes, how strict is it?  Is it generating any audit messages related to Rebirth?  As a test, if you switch it to permissive mode (which disables its ability to block traffic), does the Linux Rebirth then work properly?

**Comment by stev6502** [comment] 2022-08-30 00:03
SELinux is enabled and no alerts appeared in the SELinux Alert Browser.   Firewalld is configured to allow ports 1025-65535 tcp/udp.  I will have to do further troubleshooting to figure this one out.

**Comment by agibson2** [comment] 2022-08-30 00:57
You can't go by the version number.  The devs don't appear to update the version so it is hard to tell what version of the program you have.  It would be really handy to be able to look at the version number in the game to know if you are using the same version as others or not without having to remember which .exe you downloaded.

**Comment by agibson2** [comment] 2022-08-30 01:11
It appears Luxtorpeda's protocol still doesn't match.  Luxtorpeda updated d1x to a newer dxx-rebirth when I launched it from Steam on Steam Deck.  It shows protocol 14 for Luxtorpeda when trying to connect multiplayer and the Windows build on the site is protocol 16.  If I use the old .exe for windows from July (protocol 14), it joins just fine.  Either there is a problem with the code somehow being different protocol for Linux and windows or Luxtorpeda's compile is still using the old git commit somehow.

I really wish the version was bumped so that we could know for sure what version is being compiled.

**Comment by agibson2** [comment] 2022-08-30 04:16
I looked at the source and commit 366b048879d62a3096357509fc856dde1abfb7ff
#define MULTI_PROTO_VERSION	static_cast<uint16_t>(16)
And the older source commit d1ed53ebd9cb9bad753c5e25331a184461338d9e
#define MULTI_PROTO_VERSION	static_cast<uint16_t>(14)

If luxtorpeda is using commit 366b04... and so is the source from the windows build from the website, they both should have the protocol set to 16.  I don't understand how Luxtorpeda can still be at 14.  Maybe the new build really isn't live on Luxtorpeda?

**Comment by agibson2** [comment] 2022-08-30 04:52
I looked at the Luxtorpeda page and it is still checking out d1ed53e so it just hasn't been updated yet.

git checkout -f d1ed53e

It looks like there is a compile issue with C++20/gcc10 or something that Luxtorpeda devs might still be working on.
https://github.com/luxtorpeda-dev/packages/pull/732

**Comment by vLKp** [comment] 2022-08-31 01:40
@agibson2 wrote:

> The devs don't appear to update the version so it is hard to tell what version of the program you have.

The version number will be updated with each release.  As noted above, the builds on the website are snapshots of the development code.

> It would be really handy to be able to look at the version number in the game to know if you are using the same version as others or not without having to remember which .exe you downloaded.

Is this not what the `git describe` output provides?  The version strings that @stev6502 quoted for the Windows build appears to have the `git describe` annotation, which tells you exactly what you have.  However, as I noted in https://github.com/dxx-rebirth/dxx-rebirth/issues/660#issuecomment-1229350231, the source tarball from the website lacks a `.git` directory, and so cannot produce the same detail.  The Luxtorpeda build appears to happen in a full git repository, so it should have access to `git describe` data, and therefore Luxtorpeda builds should show the full identifier on the main menu.  If you think they do not, please provide a screenshot of the main menu and a description of where you obtained the build that lacks this detail.

> It looks like there is a compile issue with C++20/gcc10 or something that Luxtorpeda devs might still be working on.

Yes.  Luxtorpeda was using a compiler version that is below the current minimum supported version.  As of the switch to C++20 in July 2022, the minimum version of gcc is gcc-10, which was first released in May 2020.  This was picked because even Debian stable offers gcc-10 in its main repository.  The Luxtorpeda project is aware of this version requirement and is investigating how to get a newer gcc in the relevant build environment.

**Comment by agibson2** [comment] 2022-08-31 02:20
@vLKp, Thanks.  I did somehow miss or misunderstand the comment about the commit being embedded in the version.  We can determine what we have from inside the game.  Thanks for taking the time to explain the things you have.

**Comment by vLKp** [comment] 2022-10-19 01:16
A newer source tarball is now available.  Do you still see problems using that tarball for the Linux users and the corresponding prebuilt Windows binary for the Windows users?

**Comment by zicodxx** [comment] 2022-10-26 15:18
I am sorry I am only seeing this now. I am very bad at keeping up with things these days. 
I am of course open to change things if it can improve the releases and make things generally easier for everyone involved. Tho, I am not quite sure how to do this or what would be involved, especially since my time schedule to do releases is quite erratic. But I am open for suggestions.

**Comment by stev6502** [comment] 2022-10-27 07:52
My experience with Fedora 36 Linux is bad;  with the latest version I am unable to join/host any multiplayer games at all.

This is my shell script that I use to run rebirth d1
#!/bin/bash
# Use for Linux
cd ~/.d1x-rebirth
d1x-rebirth-binary -hogdir /home/stev/games/descent -tracker_hostaddr tracker.dxx-rebirth.com -maxfps 60 -tracker_hostport 9999 -nostickykeys -verbose

I get this message on the terminal window
No ACK from tracker. Please check game log.
[Tracker] No response from game tracker. Tracker address may be invalid or Tracker may be offline or otherwise unreachable.

Previously I was able to play multiplayer and host with rebirth by forcing port forward via a VPN solution, this does not anymore eitther.   Whether I use the VPN or use my normal internet connection I cannot join or host.  I am able to join/play multiplayer with DXX-Retro so I know my network configuration is ok.

**Comment by stev6502** [comment] 2022-10-27 07:58
![Screenshot from 2022-10-27 17-58-15](https://user-images.githubusercontent.com/57219557/198225696-c45c7129-552a-4505-a9b9-b0244bd13749.png)

**Comment by stev6502** [comment] 2022-10-27 08:03
Firewall rules are clear so iptables is not blocking traffic or causing issues.
I tried disabling SELinux and that hasn't helped either

[stev@fedora ~]$ sudo iptables -L -n -v
Chain INPUT (policy ACCEPT 3063 packets, 2297K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 3757 packets, 1938K bytes)
 pkts bytes target     prot opt in     out     source               destination

**Comment by stev6502** [comment] 2022-10-27 09:22
went back to the source release for 20220823 and recompiled.   did not see any error messages while hosting my test game with that version.  I don't know why the 20220929 release hates my Fedora 36.

**Comment by stev6502** [comment] 2022-10-27 09:38
Tried a clean build of the 20220929 source and same issue.  Cannot host or join any multiplayer games with rebirth d1.  Same issue happening with rebirth d2.

**Comment by stev6502** [comment] 2022-10-28 12:56
When trying to host a game this message appears
No ACK from tracker. Please check game log.
[Tracker] No response from game tracker. Tracker address may be invalid or Tracker may be offline or otherwise unreachable.

Tried tcpdump to monitor all traffic to/from the rebirth tracker
[stev@fedora ~]$ sudo tcpdump -i eno1 host tracker.dxx-rebirth.com -vvv

Now this gets interesting, for about 60 seconds nothing happened and the game complains that the tracker is unreachable.  Then, suddenly UDP packets start happening and it appears to be working.  The only way to find out is to test with another player via the internet and I haven't been able to do that yet.

If I rollback to the prior release 20220823 then this strange behaviour is not happening and it works

**Comment by vLKp** [comment] 2022-11-02 01:10
Rebirth does not distinguish LAN play versus Internet play.  All peers are simply IP addresses to which traffic is sent.  If LAN works fine in both the good and bad builds, then I cannot debug this for you, because I can only test LAN play here.

Since you are able to freely flip between a working and non-working build, I suggest you use `git bisect` to find the specific commit that causes your problem.  Knowing that commit might provide some clue as to what has changed.

With regard to tcpdump, I was hoping for a bit more detail about the different traffic patterns between good and bad builds.  Ideally, you would post the packet captures of both.  Before doing that, check that you did not capture sensitive data you want to withhold.

---

It is not clear to me how the tracker fits into this.  The tracker is a convenience service to allow web users to discover your game and, depending on configuration options, can be used to confuse your NAT device (via "NAT hole punching") into allowing guests to join without the device being configured to do so.  If possible, I suggest excluding everything tracker-related from this problem until it is determined that the tracker's involvement influences the issue.

**Comment by stev6502** [comment] 2022-11-03 04:53
Using rebirth-d1 I tried to do:
multiplayer -> find lan/online games
no games are visible for me even when they are on the tracker.  this method never works for me

what does work is I look up the IP address of the game via the dxx-rebirth tracker website and then join game manually
type in the IP address of the game and join.  game plays normally.

Summary:  using the latest version for dxx-rebirth, I cannot not automatically find games via the tracker anymore.  unless I join manually via the IP method I cannot join any games.

The above behaviour explains this message:
No ACK from tracker. Please check game log.
[Tracker] No response from game tracker. Tracker address may be invalid or Tracker may be offline or otherwise unreachable.

When I revert back to the 20220823 release the tracker issue is gone

**Comment by stev6502** [comment] 2022-11-03 05:10
Tried capturing network traffic between my computer and the rebirth tracker
sudo tcpdump -i eno1 host tracker.dxx-rebirth.com -vvv

[rebirth-tcpdump.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/9925756/rebirth-tcpdump.txt)

**Comment by vLKp** [comment] 2022-11-07 02:07
That attachment does not show much, since it lacks the packet contents for the game data packets.  However, based on your recent comments, I made another pass through the changes in the described region, and found that a commit had unintentionally changed the numbers of several tracker related messages.  This likely would interfere with talking to the tracker, but it does nothing to explain why your Windows users cannot join.

Please sync to latest and retest.  If you still have problems, collect a packet capture in `pcap` format from both a good build and a bad build, and post both.  Ideally, don't have the tracker page open, since the packet capture you posted included your browser polling the php page.

**Comment by stev6502** [comment] 2022-11-07 04:03
I think the issue between Windows/Linux has already been solved;  I was able to join a game manually by typing in the IP address and that host was using windows.   This open ticket morphed into this tracker issue which has caused confusion (apologies for that).

As for me hosting, my opinion is that the NAT in the router here is interfering and I can bypass that issue with a VPN solution but only if the communication with the tracker is working the way it should.  Maybe this ticket should be closed and a new ticket opened for the tracker issue

**Comment by vLKp** [comment] 2022-11-07 04:15
If the fix I referenced above works, the tracker should start working for you.

Yes, if your router performs NAT, you must do one of two things:

- Configure the router to forward game traffic to the private IP of your host computer.  This is what I do.  It's simple, statically configured, and I never need to worry about it.  It also gives me precise control over who is invited in.  However, many users prefer not to configure their router.
- Enable in the host game's network options, and rely at play time, on the "NAT hole punch" dance, which requires everyone involved to talk to the tracker.  Guests tell the tracker they wish to join.  The tracker relies on its existing circuit with the host to tell the host to send an unsolicited packet to the guests.  This causes your router to allow the guest's unsolicited game info request in, because it thinks that is a response to the tracker-triggered outbound packet.  If any party is not able to talk to the tracker, this bullet point cannot work.

**Comment by stev6502** [comment] 2022-11-07 08:18
I cannot port forward on the router  (the router is not owned by me and I cannot access it) 
My workaround is to use a VPN solution and bypass the router completely

**Comment by vLKp** [comment] 2022-11-07 22:54
Is there anything remaining to address in this issue?

**Comment by stev6502** [comment] 2022-11-09 06:37
working ok now,  i was able to join games via the tracker that were hosted by the Windows version

**Closed** 2022-11-09 06:37 UTC
