### ISSUE TITLE
High score entry appears as empty

### ISSUE THREAD

**Issue by Neurochild247** [dxx-rebirth/dxx-rebirth#443] opened 2019-08-19 00:48 UTC
I just finished Descent today on the d1X-rebirth port and I noticed right away after putting my entry in the High Score Leaderboards is listed as empty. As shown in the Image.

![2019-08-18 20-18-09](https://user-images.githubusercontent.com/52017370/63232700-1d560800-c1f0-11e9-9bbb-4423c2c13b65.png)

Apart from the cool saying, All data from the final score totally empty.

I played it with the commit 38fabd7 (date 2019/08/14) on Windows 10 Version 1903 Build 18362.295. And by the way, the saves states cannot be played properly on previous versions. 

I don't know if the issue is also on present d2x-rebirth.

**Comment by vLKp** [comment] 2019-08-19 03:42
> And by the way, the saves states cannot be played properly on previous versions.

What do you mean here?

**Comment by Neurochild247** [comment] 2019-08-19 04:33
> > And by the way, the saves states cannot be played properly on previous versions.
> 
> What do you mean here?

I tried my coping my profile and saves on previous versions and some of my shots clip directly through bigger enemies, like, Fusion Hulk (the purple ones), the last boss on level 27 (making it unbeatable and the game unfinishable).

Oh, and I forgot. that screenshot come from commit ec234e0, (date 2019/08/07). I upgraded it to the latest version and still the same issue. High score entry listed as empty, no matter where you're placed on the leaderboards.

**Comment by zicodxx** [comment] 2019-08-22 09:29
@vLKp I bisected the issue and I could nail down the high scores breaking first with commit 0c7de10512101ee70ae3acae30e8a5d469565489, but I wouldn't be able to tell you why.  
I'll attach my pilot. You can load its savegame and (if compiled with debug=1) press DEL+SHIFT+B to get blow up the boss and teleport to the exit. This makes testing and confirming the high score issue really easy. 

I think there is something wrong entirely with how players are currently handled. Because during my tests I made a new pilot and it took over the highest level index from the last player selected. I.e. I loaded my 1st player which had D1 First Strike level 27 unlocked, made 2nd player with name TEST and that player could immediately jump to level 27 upon selecting NEW GAME. You can reproduce that with my profile as well. Just load me pilot, confirm you can select level 27 via NEW GAME, go to CHANGE PILOTS, make a new one and select NEW GAME again.
 
[.d1x-rebirth.tar.gz](https://github.com/dxx-rebirth/dxx-rebirth/files/3529336/default.d1x-rebirth.tar.gz)

@Neurochild247 I also tried to reproduce the "weapons clip through enemies" issue, but I wasn't able to with all the savegames i made during the test. Would you be so kind as to post your savegame and list exactly with which build you last saved this save and with which build you see this corruption of weapons not hitting enemies? Thank you.

**Comment by Neurochild247** [comment] 2019-08-22 17:22
@zicodxx  Please do. My saves were from commit ec234e0. The clipping of bigger enemies happen on any commit prior to that, even 0.58.1.

[shinzo.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/3531205/shinzo.zip)

Thanks in advance.

**Comment by vLKp** [comment] 2019-08-23 04:22
That commit moves non-game tracking of the pilot name out of the `Players[]` array.  If the high scores code is run outside regular game context, the name in `Players[]` may not be set up properly.  I think `Players[]` should still be valid during the high score screen though.

**Comment by vLKp** [comment] 2019-08-25 17:58
When the pilot's name is blank, none of the other fields are shown in the high score entry for that pilot.  Due to a bug in the commit zico identified, the pilot's name was blank during the campaign, and thus blank when the high score was saved.  The above commit sets the player's name when the campaign starts.  Please update to that commit and retest.  Reopen if the problem persists.

**Comment by zicodxx** [comment] 2019-08-28 08:37
Reopening this issue, because this bug still isn't fully fixed.
The name of the player is now properly set when starting a campaign, yes, but it still isn't carried over in savegames. Meaning once you start a campaign, get Game Over, you get your high score. But if you start a campaign, save, quit the game, load savegame and get game over again, the name (and high score) will be empty.

**Comment by vLKp** [comment] 2019-08-29 04:15
[Set player name in Players[] at single-player game load](/dxx-rebirth/dxx-rebirth/commit/9bb6a95e9053ad27b7716279b861090fdffb8f3c) resets the player's name on loading a save game.  @zicodxx, is that correct and sufficient?  Should the name be loaded from the savegame file instead of restored from the active pilot data?

**Comment by zicodxx** [comment] 2019-08-29 07:29
@vLKp As far as I understand and remember, the original save games did store the callsign but discarded it upon loading, making every save game entirely based on the pilot which loaded it. From what I can tell your fix restores that and I think that's good enough. I'm going to do some more testing with that to see how it works and if I can break it again. :D

**Comment by vLKp** [comment] 2019-09-01 00:46
The name is now recorded properly.  Closing.  Please reopen if you find other paths that affect the high score storage.

**Closed by vLKp** 2019-09-01 00:46 UTC
