### ISSUE TITLE
Runtime bug: Multiplayer sound volume issues

### ISSUE THREAD

**Issue by Birdseye6dof** [dxx-rebirth/dxx-rebirth#559] opened 2020-12-06 07:54 UTC
### Environment

From this version:
https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20201029-src.tar.xz

#### Operating System Environment

 * [ ] Microsoft Windows 10 (me and others in the games)
 * [ ] Linux (one user, need to find out his Linux version)

* [ ] x86\_64 (64-bit Intel/AMD)

#### Game environment:

Any Multiplayer game

### Description

Enemy ships' sounds are *much* louder than the player's own ship. Example: normally you can barely hear someone switch weapons, but now it's extremely loud almost as if I'm hearing the sound for my own ship's weapons changing. The sounds are so loud that other sounds sometimes are actually not hearable (or maybe dropped by the mixer in some way?) e.g. someone charging a fusion cycling their secondary I could have a smart come from behind and kill me with no lock sound.

I am available to test issues frequently as I run my own company from home. I also run an "all 6dof" discord where many players can test. We had been using Retro but the new versions of Rebirth are great and are more faithful to the original game. We want to use Rebirth as the new standard but the sound issue is quite distracting :) Everyone who played had the problem, it was 5 people including me. We played for a few hours/hundreds of kills on different levels, and I restarted my game several times.

#### Regression status

I have not seen this problem in other versions of Descent 1. 

### Steps to Reproduce

* Engines affected:
  * [ x] D1X-Rebirth
  * [ ] D2X-Rebirth  <--- Have not tested yet

* Game modes affected and tested:

  * [x ] Multiplayer competitive
  * [x ] Anarchy
    

* Players affected by issue:
  * [x ] Game host
  * [ x] Game guests

**Comment by vLKp** [comment] 2020-12-06 18:44
You wrote that you have not seen this problem in "other versions of Descent 1"; which versions of Descent 1 are included in that?  Your description suggests Retro is not affected.  Have you tried earlier builds of Rebirth to see when this first appeared?

There was a change that was made to _prevent_ problems with multiplayer sound stacking.  Prior to that change, if you were near someone who was cycling their weapons (such as by holding down the "Cycle to next primary weapon" key), you would get flooded with weapon change noises as each stacked atop the previous one.  [Prevent stacking weapon rotation sounds](/dxx-rebirth/dxx-rebirth/commit/4a98e796abb099eb4c592d9520e4edbef7a15d7e) fixed that.  That change required removing a special hack for sounds that had `forever == 0`.  However, on reviewing the code, I don't see anything obviously wrong.

Are you always able to hear an enemy's sounds as if they were your own?  If your enemy is in a closed room on the far side of the level and changes his weapon, do you hear it?  Absent a bug, you should not hear that at all, no matter how loud your sound setting.  Internally, such sounds are still created, but their volume should be set to 0 due to the distance check.  Or is the game properly applying the distance filter for deciding what to play, and only unconditionally playing maximum volume for sounds that you would have heard at some volume?

Am I correct that a user who changes his weapon exactly once still sounds too loud?  That would rule out sound stacking issues, as each weapon change is supposed to generate exactly one sound (which will take several seconds to play to completion).  Sounds that stack definitely end up louder than those that do not, and inappropriate stacking would implicate a different part of the code.

As regards testing, I expect that Descent 2 will exhibit the same problem.  The sound code is mostly common between the two games.  Likewise, I expect that if both Windows and Linux users are impacted, it's probably a logic bug in the game, and will impact all Linux users.

**Comment by Birdseye6dof** [comment] 2020-12-11 05:55
vLKP said: "Have you tried earlier builds of Rebirth to see when this first appeared?"

A)
- Original D1X using Windows XP & IPX networking on Kali (played within the last few years)
- Retro
- I have not tried earlier versions of Rebirth but I will. 
- I will try earlier versions of Rebirth to determine when the problem started. I will respond with results this weekend.


vLKP said: ""Are you always able to hear an enemy's sounds as if they were your own? <snip>"

A)
- There is clear distance drop off which seems correct, but the audio accelerates in volume as you get closer -- the increase in volume is incorrect, and suddenly increases to a volume much louder than in other versions of Descent 1. 
- The equipping/cycling is just very loud, not all the way across the level. Same distance thing.
- Fusion charge has the same problem, but no other weapon sounds do. The shot of the fusion is fine.
- Ships bumping against the wall has the same sound problem.
- It seems related to "area effect" sounds of an opponent's ship (bumps, fusion charge, pickup, cycling) but not shots themselves.
- Keep in mind the incorrect sounds are so loud that say when I charge fusion, it is much quieter than when my opponent charges it.  

vLKP said: ""Am I correct that a user who changes his weapon exactly once still sounds too loud?"

A) Yes.


Descent 2 Multiplayer has the same test results with one difference: When your opponent overcharges the fusion the sound cuts out, meaning you hear the fusion charging to it's maximum, then when the overcharge kicks in there is no longer sound. You see your opponent clearly charging still, as they are exhibiting fusion shake.

Sorry it took so long for me to respond, I should be able to respond faster from here on out. 
I enlisted DescentMax to do some testing with me (I know he has done some in the past with Zico) and I streamed it on Twitch trying to keep the video as short for you as possible:
D1: https://www.twitch.tv/videos/830665639
D2: https://www.twitch.tv/videos/830701819

The D2 video is longer because that was my first time in Rebirth D2 and we were getting oriented, but most of the tests should be done within 10mins. The first minute of the D1 video has some frame drops then it settles down  There is also a longer D1 video if you are interested in actual longer gameplay runs with 4 people: https://www.twitch.tv/videos/830738997  -- there are also some giddy folks enjoying your port 👍

**Comment by vLKp** [comment] 2020-12-27 22:10
@Birdseye6dof: were you able to test any more recent builds?  I understand that the sound problem is an issue that should be fixed, but I would prefer to fix it by finding when it broke and examining the change, rather than reproducing the problem and trying to determine where the logic first goes wrong.  The latter is not too difficult if I have both a good and bad build of similar base (say, within a month or two of each other).  Comparing current code to 0.58.1 is impractical.

**Comment by Birdseye6dof** [comment] 2021-01-08 00:45
Hello

I tested files from this archive: https://www.dxx-rebirth.com/download-archive-dxx-rebirth/

The sound problems exist in newer versions but are not present in the older 0.58.1 version. 

We tested the following:
commit: 0d70c38 , date: 2020/12/16
commit: d7999c9 , date: 2020/10/29
commit: 096a678 , date: 2020/06/30
D1X-Rebirth version: 0.58.1, date: 2013/08/04

commit: 096a678, commit: d7999c9,  and commit: 0d70c38 all exhibit the issue. 0.58.1 does not have the sound issues. We did not notice any differences between commit: 096a678, commit: d7999c9,  and commit: 0d70c38.

If you ever need testers I run my own business so I am available for quick tests during the day or evening, really no bother.

**Comment by vLKp** [comment] 2021-01-11 00:30
That is unfortunate.  If the regression is that old, finding it through commit hunting will be time consuming.

**Comment by Birdseye6dof** [comment] 2021-02-21 01:03
So this was fixed in the 1/26 version?

**Comment by vLKp** [comment] 2021-02-21 23:01
Not that I know of.  Are you no longer seeing the problem?

**Comment by Birdseye6dof** [comment] 2021-03-05 03:12
Same problem as before. However I noticed that with the "FX Volume" at maximum the sound problem is the least intrusive/annoying it can be, and with FX at the lowest you can hear (one notch above the left-most setting) the problem is maximized.

Basically as I turn down FX I'm hearing less of my ship and more of the opponent's incorrec  general "personal space" sound projection (them cycling missiles, bumping into stuff, taking damage, picking up stuff, fusion overbearingly loud).

**Comment by AlumiuN** [comment] 2021-03-05 03:36
Out of interest, is the volume of the problem sounds at the same volume regardless of what your FX volume is set to, or do they actually get louder overall?

**Comment by vLKp** [comment] 2021-06-28 03:45
In testing here, I observed:

- The sounds of both local and remote weapon switches respect the FX volume slider.
- The sound of the local weapon switch is quieter than the sound of a remote weapon switch, even when the remote ship is floating nose-to-nose with the listener.
- Closed doors correctly block the sound of remote weapon switches.

In debugging, I traced this to what I consider a bug in the Rebirth sound code.  When a sound is started, its volume is scaled down as a function of `digi_volume`.  When a sound's volume is updated due to positional changes, its volume is not scaled down as a function of `digi_volume`.  The local player's weapon switch sound is initialized (and scaled), then left to run.  Remote player weapon switch sounds are initialized (and scaled), then on every subsequent frame, their volume is recomputed in a different function (and thus not scaled).  This causes remote players to be louder than the local player, because the local player is scaled twice: once by SDL_mixer (which has been instructed to scale everything by `digi_volume`) and again by the explicit downscale at start.  Remote players only get one frame of their audio at the double-scaled effect, then switch to the single level of scaling provided by SDL_mixer.  Since even the loudest FX setting causes the sound intensity to be decreased, this guarantees that remote players are always louder than the local player.

I think the undesirable scaling change occurred in [Prevent stacking weapon rotation sounds](/dxx-rebirth/dxx-rebirth/commit/4a98e796abb099eb4c592d9520e4edbef7a15d7e), because the change to prevent stacking required tracking the sound in the global that enables resetting the volume.  I think that before that change, the remote weapon change sound was downscaled at initialization time, then left unchanged afterward, causing an effective double downscale.

The fix is to remove the incorrect downscale in the sound setup, since it only affected sounds that are never updated.  Unfortunately, this led to a need for other changes, as quite a few other sounds are now louder than they once were, at least for SDL mixer users.  This change should improve consistency between SDL mixer users and straight SDL audio users.

I pushed a fix for this, and reduced the hardcoded intensity of several sounds that were affected as well.  Please sync and retest.

**Comment by vLKp** [comment] 2021-07-25 23:06
I believe the above changes address this problem.  Please reopen if you still see issues.

**Closed by vLKp** 2021-07-25 23:06 UTC
Labels: bug
