### ISSUE TITLE
Runtime bug: Multiplayer Gamelog Bug reporting after Guide-bot inclusion

### ISSUE THREAD

**Issue by Johnsondr80** [dxx-rebirth/dxx-rebirth#437] opened 2019-07-24 04:53 UTC
#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [ ] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [x] Ubuntu 19.04 (Disco Dingo)

* [x] Arch (Manjaro Gnome 18.04-stable / kernel 5.2.1.1 x-86_64)
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment
Including but not limited to (presumably): 
Descent 2: Counterstrike
D2X-Rebirth
Multi player co-op with experimental Guide-bot inclusion. 
2-4 player at least, not tested with more.

### Description

Visually no issues are detected.

#### Regression status

New bug as far as i can tell. have not seen this up until today's build and testing.

### Steps to Reproduce

host a co-op multiplayer game with at least one guest player, with Guide-Bot inclusion. Play game normally over several levels (does not seem to happen often or frequently, shortcut to kill reactor and warp to exit may not produce bug in game log)
Quite game and review gamelog.txt

- Observed behavior
Observed nothing out of the ordinary on screen visually as far as eye could tell relating to the error seen in game log.
- Unrelated to this reported bug:
1. Guide bot behavior/movements seems erratic at times and "jerky"
2. Guide bot seems to return to "Player 0" | "Player 0" appears to be who ever has high score
3. On "Player 0"s screen you see "Coming back to get you" And on other Player screens you see "Coming back to get {insert players name tag}"
2&3 seem to be correct normal behavior and seen as expected. #1 may be a bug 

* Engines affected:
  * [ ] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [x] Multiplayer cooperative

* Players affected by issue:
  * [x] Game host
  * [x] Game guests

Gamelog Text with omitted (non-issue) Standard gamelog information portions pasted below

21:20:55.906245 D2X-Rebirth v0.61 0.60.0-beta2-437-g98ad2402bfac  Vertigo Enhanced  Jul 23 2019 17:29:37
21:20:55.906358 This is a MODIFIED version of Descent 2, based on Full Version v1.2.
21:20:55.906413 Copyright (C) 1994-1996 Parallax Software Corporation
21:20:55.906463 DESCENT is a trademark of Interplay Productions, Inc.
21:20:55.906514 Copyright (C) 1999 Peter Hawkins, 2002 Bradley Bell, 2005-2013 Christian Beckhaeuser, 2013-2017 Kp
21:20:55.947215 Using SDL_mixer library v1.2.12
21:20:56.006166 sdl-joystick: 1 joysticks
21:20:56.029155 sdl-joystick 0: Sony PLAYSTATION(R)3 Controller
21:20:56.029439 sdl-joystick: 6 axes
21:20:56.029702 sdl-joystick: 17 buttons
21:20:56.029949 sdl-joystick: 0 hats
21:20:56.030218 sdl-joystick: 6 axes (total)
21:20:56.030454 sdl-joystick: 17 buttons (total)
21:20:56.347763 DXX-Rebirth: OpenGL: disabling automatic GL sync since VSync is turned off
21:25:02.646856 Found 4 cooperative starts in mission "d2" level 16.

21:42:03.152027 similar/main/fireball.cpp:232: BUG: object 0x55b151c2f2c0 has type 4, expected 5

21:46:15.712761 similar/main/multi.cpp:743: BUG: object 0x55b151c2cae0 has type 1, expected 5
21:47:50.025508 similar/main/fireball.cpp:232: BUG: object 0x55b151c2f2c0 has type 4, expected 5

EOF

**Comment by vLKp** [comment] 2019-07-26 04:26
Jerky/erratic guidebot movement is unfortunate.  I'd like to fix it, but since it doesn't break anything, it will probably not be a high priority.

https://github.com/dxx-rebirth/dxx-rebirth/blob/7bd861e3749369a8acc405b25f24ab80cfac1521/similar/main/fireball.cpp#L232

Type 5 is `OBJ_WEAPON`, so this says that `get_weapon_id` was passed a type 4 (`OBJ_PLAYER`) where a weapon was expected.  This is usually harmless, but it is wrong and should be fixed.  It's probably not guidebot related.

https://github.com/dxx-rebirth/dxx-rebirth/blob/7bd861e3749369a8acc405b25f24ab80cfac1521/similar/main/multi.cpp#L739 (Why is this line number wrong?)

Expected `OBJ_WEAPON`, got `OBJ_FIREBALL`.  That is weird, but the only consequence is that the death accounting will attribute the death to the wrong origin.  I'd like to see steps-to-reproduce for both of these, but this one in particular.  Fireballs are not usually a source of damage.  It's possible that this is actually a bug of mismapping object IDs, so a remote player was killed and this player blamed the wrong object for the player's death.  While not likely to destabilize, that would be particularly important to fix, as otherwise you could get silly results like one person saying a pre-placed mine was at fault and another saying a robot was at fault.

**Comment by Johnsondr80** [comment] 2019-07-26 13:06
Could be coincidental, and I'll do further testing to be sure.
First multiplayer game that night was to check for fix on the error mismatched level file, (verified fixed, for us anyway) highlighted here https://forum.dxx-rebirth.com/showthread.php?tid=1098&pid=12645#pid12645

These game logs did not show the [bug] reported here.

After that we played again, only this time with guidebot included. As reported for several levels.

Again I assert, no difference in play between the two sessions except including guidebot into multiplayer session.

As far as reproducing, I will on next session try to tie down exactly the in-game action that triggers the event, and report back. 

According to your assessment I can assume it is death related. So I'll try to figure who's death and watch logs carefully and try to demo the action.

Not sure what else to try. Ideas welcome.

**Comment by vLKp** [comment] 2019-07-27 00:57
Player deaths usually leave a note in the log when they happen.  The death that provoked this message should be logged right next to the `BUG` message.  You probably trimmed it out of the version posted here, but if you still have the full log, it would probably be there.  For the fireball case, I think it is probably related to the guidebot.  The fragment linked above tests for three things, in this order, with short-circuiting:

- Is the weapon a valid object?
- Is the defender a guidebot (`.companion`)?
- Does the weapon have a flash missile effect (multiple weapons do this, not just the flash missile that players can fire)?

Assuming short-circuiting worked correctly, we would not have tested whether the weapon was a flash missile until we knew the defender was a guidebot.

Tracing the code to try to give you a hint, I think I found it.  This path looks bad:

- https://github.com/dxx-rebirth/dxx-rebirth/blob/7bd861e3749369a8acc405b25f24ab80cfac1521/similar/main/fireball.cpp#L378-L380
  - https://github.com/dxx-rebirth/dxx-rebirth/blob/7bd861e3749369a8acc405b25f24ab80cfac1521/similar/main/fireball.cpp#L366-L368
    - https://github.com/dxx-rebirth/dxx-rebirth/blob/7bd861e3749369a8acc405b25f24ab80cfac1521/similar/main/fireball.cpp#L329-L333
      - https://github.com/dxx-rebirth/dxx-rebirth/blob/7bd861e3749369a8acc405b25f24ab80cfac1521/similar/main/fireball.cpp#L128
      - https://github.com/dxx-rebirth/dxx-rebirth/blob/7bd861e3749369a8acc405b25f24ab80cfac1521/similar/main/fireball.cpp#L232

I don't know if it's the only bad path, but it is a bad path.  The fix is easy enough.  Now that we know that non-weapons can be passed to `object_create_explosion_sub`, we know that the type of the passed object must be checked instead of assuming it is always a weapon.  I can fix this one without further logs from you.  Thanks for reporting it.

The one in `multi.cpp` is still not explained though.

**Comment by Johnsondr80** [comment] 2019-07-27 05:08
[gamelogD-guidebot-multi-072519.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/3437812/gamelogD-guidebot-multi-072519.txt)
[gamelogD-MultiGuideBot-072619.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/3437813/gamelogD-MultiGuideBot-072619.txt)
[gamelogD-Multi-No-GuideBot-072619.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/3437814/gamelogD-Multi-No-GuideBot-072619.txt)
[gamelogG-guidebot-multi-072519.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/3437868/gamelogG-guidebot-multi-072519.txt)

Hopefully these will help, there is one multi.cpp right after sheilds boosted to 52
and all the laser.cpp is the boss battle at the end of lvl 24 (probably same issue as the fireball.cpp so it may automatically be repaired with that fix)

**Comment by vLKp** [comment] 2019-07-27 17:51
Thank you.  I will check those soon.  In the meantime, I pushed a fix for the fireball.cpp:232 report.  I believe it was triggered by a player experiencing an explosive death while the guidebot was close enough that the explosion could damage the guidebot.

**Comment by vLKp** [comment] 2019-08-21 02:58
- [gamelogD-guidebot-multi-072519.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/3437812/gamelogD-guidebot-multi-072519.txt): three `BUG` entries:
  - fireball.cpp:232, fixed in my commit above
  - fireball.cpp:257, fixed in my commit above
  - Escort (guidebot) goal unexpectedly `UNSPECIFIED`.  This is weird, but the game should recover.  If I knew how it happened, I would try to fix it.
- [gamelogD-MultiGuideBot-072619.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/3437813/gamelogD-MultiGuideBot-072619.txt): `d2x::exists_in_mine` was called with `Buddy_objnum` set to `object_none` (no guidebot).  This function should only be called when a guidebot exists, but somehow it was called with no guidebot.  A stack backtrace showing which caller was responsible might be useful.
- [gamelogD-Multi-No-GuideBot-072619.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/3437814/gamelogD-Multi-No-GuideBot-072619.txt):
  - similar/main/multi.cpp:743: killed by an object of type OBJ_NONE, the type for objects that are not in use.  This is definitely a bug, but I need more information about the game state to understand it.  Unfortunately, the game doesn't log that information anywhere, so you can't collect what I need.  Fortunately, the bug is purely cosmetic, assuming the same object mismatch isn't occurring anywhere else.  A commit today tightens the check, but doesn't fix the bug.
  - fireball.cpp:257, fixed in my commit above
  - similar/main/laser.cpp:1573: a player was dead while his guided missile was in flight, even if the missile had degraded to autonomous homing mode.  Fixed today.
- [gamelogG-guidebot-multi-072519.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/3437868/gamelogG-guidebot-multi-072519.txt): two `BUG` entries, same as problems 1 and 3 in [gamelogD-guidebot-multi-072519.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/3437812/gamelogD-guidebot-multi-072519.txt).

**Comment by vLKp** [comment] 2019-09-01 00:48
I think all the problems reported here have been addressed.  If I missed some, please reopen and identify what is still incorrect.

**Closed by vLKp** 2019-09-01 00:48 UTC
Labels: bug
