### ISSUE TITLE
D1X - using fusion cannon after loading a savegame has some issues

### ISSUE THREAD

**Issue by pgkos** [dxx-rebirth/dxx-rebirth#323] opened 2017-02-15 15:50 UTC
When loading a saved game in D1X Rebirth v0.59.100 with fusion cannon selected, two things can happen:
- When trying to fire it, sometimes it will instantly drain all shield.
- Sometimes the purple haze will not show and it is possible to charge the fusion indefinitely without taking any damage.

If I change the primary weapon to some other weapon, and then reload the fusion, the bug disappears.

**Comment by vLKp** [comment] 2017-02-16 03:33
I cannot reproduce this on 0.59.100 or tip when starting **Descent: First Strike** level 1, adding a Fusion Cannon via cheat, setting the Fusion Cannon as the active weapon, saving the game, reloading, and firing.

**Comment by Mako88** [comment] 2017-02-18 15:39
Could this be when using a savegame from 0.58.1 that is loaded in 0.59.100? (I'll be doing some testing tomorrow, and will test this).

**Comment by pgkos** [comment] 2017-02-18 20:18
Maybe, but I have saved the game in v0.59.100 and loaded it after a minute, and the bug occurred. At that time D1X Rebirth was already running for around 20 minutes.

At first it caused instant draining of all shield in a fraction of a second (like from 200 to 0 in no time, at the beginning of a fusion charge).

After testing it a few times the behavior changed and I was able to charge the fusion indefinitely without taking any damage (and there was no purple or yellow haze).

**Comment by vLKp** [comment] 2017-02-18 22:36
@pgkos: this sounds like it *might* be related to a bug I fixed a few weeks ago, but since I cannot reproduce it with the steps given even on 0.59.100, I cannot be sure.  If you provide detailed steps to reproduce, starting from scratch, I will try again.  Document every choice you make from when the program starts to when the bug is observed.  On what levels you play, how you load the game, etc.  You can skip over the details of how you acquire a fusion cannon in your chosen level.

**Comment by pgkos** [comment] 2017-02-19 09:49
Okay, so there is a chance that I have found a way to reproduce it with high probability (the bug happened again today at the same place as a few days ago).

Go to level 22, and then go to behind the yellow door (you can use cheats). Then, before the red hulks (close, just so they don't see you yet) change the weapon to the fusion cannon. Don't fire it, just save the game. Then, load the game. Try to fire the fusion.

**Comment by pgkos** [comment] 2017-02-19 10:06
I cannot reproduce it reliably... at the first time it failed, now after restarting D1 and repeating the same steps the bug does not occur.

**Comment by pgkos** [comment] 2017-02-19 10:12
Okay, so now I think I really have a 100% way to reproduce it:
- repeat the steps in level 23 (from my previous post)
- save the game and load it
- exit to the main menu
- start a new game on any level
- load the saved game

**Comment by vLKp** [comment] 2017-02-19 22:08
Starting one level, then loading a game saved on a different level, had a bug in 0.59.100.  Some player data was loaded into the player's old-level object slot, but it should have been loaded into the new-level object slot.  Fusion data was among the variables affected, which could account for the reported problems.  As a workaround, loading the game a second time (so that you are already on the saved level when you choose Load Game) will avoid the issue, since that will cause your old-level object and new-level object to be the same object, so the data goes into the right place (for the wrong reason).  This was fixed after beta 1 was released, but no new beta has been posted with the fix.

**Comment by vLKp** [comment] 2017-07-09 20:05
@pgkos: @Mako88 has resumed posting snapshot builds on the [DXX-Rebirth download page](http://www.dxx-rebirth.com/download-dxx-rebirth/).  Please retest on a current snapshot build and report whether the problem still occurs.  If it is the problem I described in February, then it will be fixed now and loading in a current build will work correctly for all savegames, regardless of whether they were saved by a bad version.  (Saving in a current build and loading in a bad build will still be affected, since the bug was purely in the loader.)

**Comment by vLKp** [comment] 2017-07-22 17:45
The reported problem was likely fixed in late January or early February.  Reporter has not indicated any further issues.  Closing.

@pgkos: if you still see this problem in a current snapshot, please reopen.

**Closed by vLKp** 2017-07-22 17:45 UTC
