### ISSUE TITLE
No music in D2X-Rebirth

### ISSUE THREAD

**Issue by norbert79** [dxx-rebirth/dxx-rebirth#634] opened 2022-04-23 10:11 UTC
Updated the game (D2X) with the latest update (commit: 81dd23b, date: 2022/04/20), it seems no music is being played at all. None of the built-in music is being played, nor any of the add-ons work. It's totally mute.
D1X works perfectly fine.

**Comment by parkerlreed** [comment] 2022-04-23 11:12
What system?

**Comment by vLKp** [comment] 2022-04-23 17:02
Did this work in a prior commit?  If yes, which one?  Is D1X drawn from the same commit as D2X?  How is music configured in each of them?

**Comment by AlumiuN** [comment] 2022-04-23 23:03
I can confirm that both D1X and D2X's music (both built-in and jukebox) are broken for me as of 87cc4c79c84401888bd51683d1e0d3b39c5a0742 on Windows 10. I'll do some regression testing later today to narrow it down.

**Comment by AlumiuN** [comment] 2022-04-24 05:47
Looks like commit 3b5b69cb97fd9752a5388a35b66f3fc74a3242cb broke the built-in music; the jukebox has a separate issue that I haven't tracked down but it looks like the paths are either having the game's working directory appended to the front of the path (so an absolute path ends up being reported as, in my case, "D:\Games\DXX-Rebirth\D1X-Rebirth\F:\Music\(etc.)") or just failing in some other way that the gamelog message is not specific about when I tried a relative path ("Music music\test.flac could not be loaded: Failed loading libFLAC-8.dll: %1 is not a valid Win32 application.").

**Comment by vLKp** [comment] 2022-04-24 17:40
I cannot reproduce this on x86_64-pc-linux-gnu with gcc-10.3.1 and libSDL1.

Per the comment from @AlumiuN, I ran `git checkout 3b5b69cb97fd9752a5388a35b66f3fc74a3242cb^` to get the commit before the commit described as first-bad.  I built a non-developer build of Descent 2, started the game, and chose Music Type: `Built-in/Addon Music`.  Music began playing, as expected.  I then ran `git checkout 3b5b69cb97fd9752a5388a35b66f3fc74a3242cb` to get the commit described as first-bad.  I built again, started the game, made the same choice, and music again began playing - which was not expected.  This commit should have been silent.

I then ran `git checkout 81dd23b15133bbf5022b6a9a73626b91d1831e3c` to get the commit described as bad by @norbert79.  I built, made the same choices, and music began playing - again, not as expected.  This commit also should have been silent.

---

I reviewed the code change in the commit cited by @AlumiuN.  I don't see a reason for the behavior to vary between D1 and D2.  If the failure is in `hmp2mid`, there should be a message printed about the failure.  If the failure was in `digi_win32_play_midi_song`, no message would be emitted - this function has always been silent about errors, both before and after the cited commit.

**Comment by AlumiuN** [comment] 2022-04-27 04:00
After a little debugging, it appears the problem is the change in "digi_win32_play_midi_song". I haven't used that syntax to get multiple results from a function myself to be entirely sure of its intended behaviour, but it appears that attempting to use a temporary instead of cur_hmp and then std::move-ing that temporary to cur_hmp fixes the problem, i.e.
`	if (auto &&[temphmp, hoe, pec] = hmp_open(filename); temphmp)
	{
		(void)hoe;
		(void)pec;
		cur_hmp = std::move(temphmp);`

**Comment by vLKp** [comment] 2022-04-28 01:26
As a piece of common code, that bug ought to affect D1 as well as D2, although only on Windows, which is why I could not reproduce it.  @norbert79 did not specify to test on Windows, so I did not.  @norbert79 also wrote that D1X is unaffected, which seems inconsistent with the finding above.  That said, @AlumiuN's finding looks like a real bug, and I can explain it.

---

Yes, moving to a temporary likely does fix it.  `cur_hmp` is a global (though its name would not suggest that).  The bad version of the code declares a local _also_ named `cur_hmp`, binds it to part of the result of `hmp_open`, and uses it for the duration of the `if` block.  When the `if` block ends, that local is destroyed, and the underlying object is freed.  One of the steps of freeing it is to run `hmp_file::~hmp_file`, which on Windows, but not other platforms, will call `hmp_stop(this)`.  This has the result that music is stopped within a few dozen instructions after it starts, so the user will never notice that it played.  In the good version of the code, no local is declared, and the result of `hmp_open` is written directly into the global, then read back as needed later.  As a global, the value is not destroyed at the end of the `if` block, so the destructor is not run and the music is not instantly stopped.

**Comment by vLKp** [comment] 2022-04-28 02:25
The above commit reverts this call site to the older behavior, which should be similar to the change that @AlumiuN proposed.  Please test and report back.

**Closed by vLKp** 2022-04-28 02:25 UTC

**Comment by vLKp** [comment] 2022-05-14 17:18
The current build posted on the website is dated 2022/04/20, 3 days before this report was filed, and 8 days before I made the commit that corrects this issue, so I think the answer is that no, there is no prebuilt Windows binary available with this fix.  Based on recent build history, it looks like snapshot builds are made about once per month.  If so, I would expect the next build to be posted sometime in the next 7-12 days, depending on @zicodxx's schedule and availability.

**Comment by norbert79** [comment] 2022-05-25 07:49
Hey, sorry for not mentioning the OS name. The OS was Windows 10 Pro, 21H2 - 19044.1706. Just tested the latest builds, released on the 22nd of May, 2022, and these new binaries are capable of playing the built-in music (MIDI) again. They seem to be working without issues. I consider from my side the problem solved.
Thank you for your help.

**Comment by lowpursuit** [comment] 2022-06-13 05:55
Hey there. Just trying DX1 out for the first time on Win10. The default midi plays fine, but I can't get the jukebox to work. Getting late, I'll have to play around with it tomorrow. Take care
