### ISSUE TITLE
Runtime bug: lag and music problem in main menu

### ISSUE THREAD

**Issue by Q3BFG10K** [dxx-rebirth/dxx-rebirth#549] opened 2020-10-31 05:46 UTC
Hi there, I'm using **D2X** on **Win10-64-2004** downloaded from:
https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20201029-win.zip

This version **1053-GD7999C9FADE0** has a noticeable 1-2 second lag delay when selecting menu items (new game, load game, options, etc).

The previous build **709-GF0A47C358BA6** doesn't have this problem.

Also both versions have an issue when playing background menu music. It cuts out before finishing and starts looping again too early. I don't recall what version this problem started in.

Thank you.

**Comment by vLKp** [comment] 2020-10-31 23:09
I do not see the delay when selecting menu items.  Can you [bisect](https://git-scm.com/docs/git-bisect) to determine in which commit this began?

**Comment by AtifArshad1995** [comment] 2020-11-16 12:57
I am also seeing the same issue that @Q3BFG10K is facing. In the 29th October build, there is a delay of like 1-ish second when selecting menu options in D2X-Rebirth. This does not happen in D1X-Rebirth.

The previous build I used that didn't have this issue is from 29th August.

**Comment by Q3BFG10K** [comment] 2020-11-17 11:28
> 
> 
> I do not see the delay when selecting menu items. Can you [bisect](https://git-scm.com/docs/git-bisect) to determine in which commit this began?

I don't know what that means sorry.

Is there a downloadable archive of nightly Windows builds I can test? The problem is in that month between those two builds.

**Comment by vLKp** [comment] 2020-11-18 04:07
@AtifArshad1995 wrote:
> Thus the menu issue was introduced somewhere between 30th Sep and 29th Oct.

Interesting.  Thank you.  That suggests the bad commit is somewhere in the range <d7560843b03c128b519976e33ccc1b418dee8142..6af0595cfe463e2ce2aa5646a6aa36f41663b80f>.  This covers an 84 commit span, so it should be bisectable in ~7 steps.

@Q3BFG10K wrote:
> @vLKp wrote:
> > I do not see the delay when selecting menu items.
> What about the issue with menu background music?

I do not normally play background music.  As I could not reproduce the easier problem you reported, I have not yet attempted to reproduce the more subtle one.

@Q3BFG10K wrote:
> @vLKp wrote:
> > Can you bisect to determine in which commit this began?
> I don't know what that means sorry.

[git bisect](https://git-scm.com/docs/git-bisect) is a way to find a specific bad commit without the need to visit every commit individually.  It requires having the ability to build the commits suggested by git, and test the resulting build.  It works by telling `git` a known-good commit and a known-bad commit.  `git` then suggests a commit roughly halfway between them, and has you test it.  Based on whether you call that commit good or bad, it picks a commit halfway through the resulting sub-range.  You test that, and report it to git.  This repeats until the halving process takes you to a single commit.  This process lets you test roughly log2(N) commits for a range that is N commits long.

> Is there a downloadable archive of nightly Windows builds I can test?  The problem is in that month between those two builds.

I am not aware of such an archive.  I do not provide Windows builds on any time scale.

**Comment by Q3BFG10K** [comment] 2020-11-18 09:04
> [git bisect](https://git-scm.com/docs/git-bisect) is a way to find a specific bad commit without the need to visit every commit individually. It requires having the ability to build the commits suggested by git, and test the resulting build. It works by telling `git` a known-good commit and a known-bad commit. `git` then suggests a commit roughly halfway between them, and has you test it. Based on whether you call that commit good or bad, it picks a commit halfway through the resulting sub-range. You test that, and report it to git. This repeats until the halving process takes you to a single commit. This process lets you test roughly log2(N) commits for a range that is N commits long.

I'm not seeing how anything linked on that page is going to produce downloadable Windows builds for me to test?

Also I have no intention of installing Git on my Windows machine. Sorry.

**Comment by AtifArshad1995** [comment] 2020-11-18 10:21
I can give it a try to bisect and find the bad commit. But note that I am total noob when it comes to these things, so I would need guidance about how to compile builds.

**Comment by vLKp** [comment] 2020-11-19 03:45
@Q3BFG10K wrote:

> I can't see anything on that page that produces downloadable Windows builds for me to test?

Correct.  That page describes what git bisect is, and how to use it, in more detail than I included.

> Also I have no intention of installing Git on my Windows machine. Sorry.

That's fine.  Rebirth can be cross-compiled from Linux to Windows.  That is how I check that the Windows build still works.

@AtifArshad1995 wrote:

> But note that I am total noob when it comes to these things, so I would need guidance about how to compile builds.

The build process is documented in [INSTALL.markdown](https://github.com/dxx-rebirth/dxx-rebirth/blob/caa29824b98c3afaf455e0af477c30e0d6e9e603/INSTALL.markdown).  If you need further help, please file a separate issue and describe what is unclear or what failed for you.

**Comment by cbrt64** [comment] 2020-12-19 21:32
So, I built d1x/d2x(sdl2) before/after 3114874713fb8f9fa8ca1ae966a7a5825950437a, and before/after 017c4ce9335110ecc61beeeacdf99cf96d77a9da, with current msys2/mingw64 libraries.
Testing these four builds (as well as a few others in between) confirmed the cause of breakage as well as @arbruijn's solution from #555.

The menu delay affected d1x as well, though it was not nearly as noticeable as in d2x. I don't know why interim Windows builds would work; it could be something to do with the different libraries used, otherwise it seems like a red herring.

I wasn't able to reproduce the music issue, sorry.

**Comment by vLKp** [comment] 2020-12-27 05:27
The menu slowness is now resolved.  I was not able to reproduce the music issue, and the report so far does not indicate even a range in which the music issue may have appeared, so I cannot work on it through code inspection.  Closing.

@Q3BFG10K: if you still see the music issue in the latest code, and can provide steps to reproduce or an indication of when it first appeared, please reopen.  Otherwise, there is nothing further I can do here.

**Closed by vLKp** 2020-12-27 05:27 UTC
Labels: bug
