### ISSUE TITLE
Multiplayer save game: players cannot move after loading

### ISSUE THREAD

**Issue by Sottises** [dxx-rebirth/dxx-rebirth#347] opened 2017-10-01 10:23 UTC
After starting a co-op game, playing for a few seconds to get out of the starting position and kill a few bots, and save. When the host reloads both players are stuck in place and can only fire their weapons, open the automap or menus/quit. On some instances, the scores could be wrong as well. Possible desync?

Using commit 783bd90

**Comment by vLKp** [comment] 2017-10-03 01:32
I can reproduce the failure-to-move bug and bisected it to [Additional safeguard for bug #306](/dxx-rebirth/dxx-rebirth/commit/b1b5de4297df44735697bec09dde7e84db9ee701) by @kreatordxx.  @kreatordxx: your commit message says that omitting `PF_USES_THRUST` was safe.  Omitting it seems to cause this problem since reverting your commit eliminated the issue in testing.  I suspect this is due to some difference in new game setup versus saved game reload.  Do you see any harm to including `PF_USES_THRUST` in the flag list?

@Sottises: I published an initial fix as [Enable PF_USES_THRUST when reseting multiplayer flags](/dxx-rebirth/dxx-rebirth/commit/c3434e61d3e503ae6f8f3002328ff04d948afb99).  Since this is a load-time bug, not a save-time bug, your existing saves can be salvaged if started in a build with the fix.  This may need to be revisited if @kreatordxx knows of a reason I missed for why this is not correct.

Your description of the scores problem is too vague for me to pursue at this point.  Please open a new ticket for that problem and describe in detail what happens and, as best you can, how to cause it to happen.

**Comment by vLKp** [comment] 2017-10-04 01:06
I changed the title of this issue to reflect that this is not a corruption bug.  The save file is fine, and works as desired in builds that predate the bad commit and builds that include the fix published yesterday.  The bug was in the savegame loading code.

**Comment by vLKp** [comment] 2017-10-12 01:30
Issue was reproduced locally and fix pushed.  No feedback from reporter after one week.  Closing.

Please reopen if this is still a problem in the latest code.

**Closed by vLKp** 2017-10-12 01:30 UTC

**Comment by kreatordxx** [comment] 2017-10-20 10:49
Hi vLKp, I don't see any issue with adding `PF_USES_THRUST`.
