### ISSUE TITLE
Re-typing "porgys" cheat disables, but gives weapons

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#195] opened 2016-05-16 16:05 UTC
When using the porgys cheat, if you type it in once it grants all weapons (plus extra secondaries) and allows you to shoot crazy fast. If you type it in again it gives all the weapons again, but disables shooting really fast. Typing it a third time re-enables fast weapons (while giving them again).

Original behavior was to simply re-give everything when you type it in again. I can understand wanting to make typing it in twice disable it, but if so, it should reset the secondary caps and not give you anything when you type it in a second time.

**Comment by vLKp** [comment] 2016-05-17 03:43
You mention original behavior.  Is the current behavior a regression relative to 0.58.1 or only relative to retail Descent?

**Comment by Mako88** [comment] 2016-05-17 03:48
Only relative to retail (0.58.1 works the same way as this). In the original you couldn't disable cheats. Typing it in again simply gives you all weapons back and keeps you with fast weapons.

**Comment by zicodxx** [comment] 2016-06-13 11:02
I think the initial approach I had back then was to allow disabling all cheats if that would be possible by simply toggling the cheat flags on and off. Of course you'd still be marked as a cheater but there was still this "opt-out" method. I think that was my motivation back then. The fact that the cheat still gives you new weapons on disable is odd but I'll check it out. Of course it would be quite the hassle to take away the weapons you were given as the game doesn't track your previous inventory nor whatever you legitimately picked up but since it's "just a cheat" I think that's fine. I'll see that I solve it one way or another - either by restoring the original behavior or letting you disable the fast firing and not giving any new weapons (which I think would be the preferred way).

**Comment by zicodxx** [comment] 2016-06-13 11:27
Pushed 64f77636a7e6e916abb4e352f31c398e9f6ee633 which will not give new weapons when Rapidfire is disabled. Also this adds a HUD message similar to Descent 2 indicating the state of rapidfire (on/off).

**Closed by zicodxx** 2016-06-13 11:27 UTC
