### ISSUE TITLE
D1 Spreadfire cannon consumes too much energy.

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#322] opened 2017-02-13 10:29 UTC
As reported here: http://www.dxx-rebirth.com/frm/index.php/topic,2155.0.html

I can verify this: In 0.58.1, the D1 Spreadfire consumed one unit of energy upon two shots while in current master it consumes one unit per shot. I have yet to bisect it. If someone would like to chime in, great. If not, I'll see to this on the weekend. :)

**Comment by vLKp** [comment] 2017-02-14 03:28
This is probably caused by the very strange way that D1 defined and used `SPREADFIRE_ID`.

```
0.58.1-d1x:main/laser.h:29: XSPREADFIRE_ID = 12,  //  NOTE: This MUST correspond to the ID generated at bitmaps.tbl read time.
0.58.1-d1x:main/laser.h:38: SPREADFIRE_ID = 20,
0.58.1-d1x:main/weapon.c:35:const ubyte Primary_weapon_to_weapon_info[MAX_PRIMARY_WEAPONS] = {0, VULCAN_ID, 12, PLASMA_ID, FUSION_ID};
github/master:common/main/weapon_id.h-40-#if defined(DXX_BUILD_DESCENT_I)
github/master:common/main/weapon_id.h:41: SPREADFIRE_ID = 20,
github/master:common/main/weapon_id.h-42-#endif
github/master:similar/main/weapon.cpp:71:const array<weapon_id_type, MAX_PRIMARY_WEAPONS> Primary_weapon_to_weapon_info{{
github/master:similar/main/weapon.cpp-72- weapon_id_type::LASER_ID, weapon_id_type::VULCAN_ID, weapon_id_type::SPREADFIRE_ID, weapon_id_type::PLASMA_ID, weapon_id_type::FUSION_ID
github/master:similar/main/weapon.cpp-73-}};
```

In short, D1 set SPREADFIRE_ID to 20, but then used 12 in Primary_weapon_to_weapon_info.  In tip, this has been corrected, so that 20 is used in both places.  According to debugging output, this would account for the increased energy consumption:

```
p d1x::Weapon_info._M_elems[12].energy_usage 
$1 = 32768
p d1x::Weapon_info._M_elems[20].energy_usage 
$2 = 65536
```

It would be nice if there was a comment in the original source explaining why `12`, but absent that, this looks like a fix for an original defect caused by using magic numbers where they should have used symbolic values.

**Comment by kreatordxx** [comment] 2017-02-19 04:02
I replaced `20` with `12` for `SPREADFIRE_ID` for Descent 1 and it works fine, for both Mac and PC full version and demo version data (all four combinations).

**Comment by kreatordxx** [comment] 2017-02-19 04:58
Aha, I just found a subtle difference - with projectile speed. By printing all combinations of weapon `12` and `20` for Mac and PC data, demo and full version the only differences are in energy usage (as discovered above) and weapon speed. Interestingly, the speed varies between demo and full version data, but (as one would expect) not between Mac and PC.

More interestingly, for the full version `20` is faster than `12`; while for the demo version `12` is faster than `20`.

**Comment by vLKp** [comment] 2017-02-25 17:42
Based on kreator's research, I reverted to the split identifier approach used in past releases.  [Reduce D1 spreadfire cost](/dxx-rebirth/dxx-rebirth/commit/dc090958d16caa55a1445abde7cb3cdd296ddbd9) should resolve this issue.

**Comment by vLKp** [comment] 2017-03-23 02:47
Fixed about a month ago.  No further adverse reports.  Closing.

**Closed by vLKp** 2017-03-23 02:47 UTC
