### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by TheDemonicSurfer** [dxx-rebirth/dxx-rebirth#593] opened 2021-06-12 14:57 UTC
Trying to build on Manjaro XFCE 21.0.6

> scons: Reading SConscript files ...
> ===== D1X-Rebirth v0.61.0 0.60.0-beta2-1338-g201199ebf8ab* 201199ebf8ab769acb8ad3700bc0d084a9a66f5b =====
> ===== D2X-Rebirth v0.61.0 0.60.0-beta2-1338-g201199ebf8ab* 201199ebf8ab769acb8ad3700bc0d084a9a66f5b =====
> DXX-Archive.3: compiling on 'linux'/'x86_64' for 'linux' into .
> DXX-Archive.3: checking version of C++ compiler 'g++' ... 'g++ (GCC) 11.1.0'
> DXX-Archive.3: checking path to assembler ... b'as'
> DXX-Archive.3: checking version of assembler b'as' ... 'GNU assembler (GNU Binutils) 2.36.1'
> DXX-Archive.3: checking path to linker ... b'ld'
> DXX-Archive.3: checking version of linker b'ld' ... 'GNU ld (GNU Binutils) 2.36.1'
> DXX-Archive.3:	CHOST: None
> DXX-Archive.3:	CXX: 'g++'
> DXX-Archive.3:	CPPDEFINES: [('PHYSFS_DEPRECATED', '')]
> DXX-Archive.3:	CPPPATH: ['common/include', 'common/main', '.']
> DXX-Archive.3:	CPPFLAGS: ['-Wno-sign-compare']
> DXX-Archive.3:	CXXFLAGS: ['-g', '-O2', '-ftabstop=4', '-Wall', '-Werror=extra', '-Werror=format=2', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=vla', '-pthread', '-funsigned-char']
> DXX-Archive.3:	LIBS: None
> DXX-Archive.3:	LINKFLAGS: []
> DXX-Archive.3:	$CCACHE_PREFIX: None
> DXX-Archive.3:	$DISTCC_HOSTS: None
> DXX-Archive.3: checking whether C++ compiler and linker work...(cached) yes
> DXX-Archive.3: checking whether C++ compiler accepts -std=gnu++17...(cached) yes
> DXX-Archive.3: checking endian to use...little
> DXX-Archive.3: checking whether to enable word alignment fixups...no
> DXX-Archive.3: building with OpenGL
> DXX-Archive.3: checking whether to enable release options...yes
> DXX-Archive.3: checking whether to enable memory allocation tracking...no
> DXX-Archive.3: checking whether to enable level editor...no
> DXX-Archive.3: checking whether to enable IPv6 support...no
> DXX-Archive.3: checking whether to enable multiplayer over UDP...yes
> DXX-Archive.3: checking whether to enable UDP game tracker...yes
> DXX-Archive.3: checking how to handle ADL MIDI...disabled
> DXX-Archive.3: checking how to format screenshots...png
> DXX-Archive.3: checking libpng pkg-config libpng
> DXX-Archive.3: using pkg-config at discovered path /usr/bin/pkg-config
> DXX-Archive.3: reading libpng version from ('/usr/bin/pkg-config', '--modversion', 'libpng')
> DXX-Archive.3: libpng version: b'1.6.37'
> DXX-Archive.3: reading libpng settings from ('/usr/bin/pkg-config', '--cflags', '--libs', 'libpng')
> DXX-Archive.3: libpng settings: {'CPPPATH': ['/usr/include/libpng16'], 'LIBS': ['png16', 'z']}
> DXX-Archive.3: checking for usable library png...(cached) yes
> DXX-Archive.3: checking physfs pkg-config physfs
> DXX-Archive.3: reading physfs version from ('/usr/bin/pkg-config', '--modversion', 'physfs')
> DXX-Archive.3: physfs version: b'3.0.2'
> DXX-Archive.3: reading physfs settings from ('/usr/bin/pkg-config', '--cflags', '--libs', 'physfs')
> DXX-Archive.3: physfs settings: {'LIBS': ['physfs']}
> DXX-Archive.3: checking for usable library physfs...(cached) yes
> DXX-Archive.3: checking for usable library ['GL', 'GLU']...(cached) yes
> DXX-Archive.3: checking SDL pkg-config sdl
> DXX-Archive.3: reading sdl version from ('/usr/bin/pkg-config', '--modversion', 'sdl')
> DXX-Archive.3: SDL version: b'1.2.15'
> DXX-Archive.3: reading SDL settings from ('/usr/bin/pkg-config', '--cflags', '--libs', 'sdl')
> DXX-Archive.3: SDL settings: {'CPPDEFINES': [['_GNU_SOURCE', '1'], '_REENTRANT'], 'CPPPATH': ['/usr/include/SDL'], 'LIBS': ['SDL', 'pthread']}
> DXX-Archive.3: checking whether to enable joystick support...yes
> DXX-Archive.3: checking for usable library SDL with OpenGL...(cached) yes
> DXX-Archive.3: checking whether to use SDL_image...yes
> DXX-Archive.3: checking SDL_image pkg-config SDL_image
> DXX-Archive.3: reading SDL_image version from ('/usr/bin/pkg-config', '--modversion', 'SDL_image')
> DXX-Archive.3: SDL_image version: b'1.2.12'
> DXX-Archive.3: reading SDL_image settings from ('/usr/bin/pkg-config', '--cflags', '--libs', 'SDL_image')
> DXX-Archive.3: SDL_image settings: {'CPPDEFINES': [['_GNU_SOURCE', '1'], '_REENTRANT'], 'CPPPATH': ['/usr/include/SDL'], 'LIBS': ['SDL_image', 'SDL', 'pthread']}
> DXX-Archive.3: checking for usable library SDL_image...(cached) yes
> DXX-Archive.3: checking whether to use SDL_mixer...yes
> DXX-Archive.3: checking SDL_mixer pkg-config SDL_mixer
> DXX-Archive.3: reading SDL_mixer version from ('/usr/bin/pkg-config', '--modversion', 'SDL_mixer')
> DXX-Archive.3: SDL_mixer version: b'1.2.12'
> DXX-Archive.3: reading SDL_mixer settings from ('/usr/bin/pkg-config', '--cflags', '--libs', 'SDL_mixer')
> DXX-Archive.3: SDL_mixer settings: {'CPPDEFINES': [['_GNU_SOURCE', '1'], '_REENTRANT'], 'CPPPATH': ['/usr/include/SDL'], 'LIBS': ['SDL_mixer', 'SDL', 'pthread']}
> DXX-Archive.3: checking for usable library SDL_mixer...(cached) yes
> DXX-Archive.3: checking whether C++ compiler accepts {} initialization...(cached) yes
> DXX-Archive.3: checking whether compiler optimizes function __attribute__((__error__))...(cached) yes
> DXX-Archive.3: checking whether compiler implements __builtin_bswap{16,32,64} functions...(cached) yes
> DXX-Archive.3: checking whether compiler optimizes __builtin_constant_p...(cached) yes
> DXX-Archive.3: checking whether compiler accepts __builtin_expect...(cached) yes
> DXX-Archive.3: checking whether compiler accepts __builtin_FILE, __builtin_LINE...(cached) yes
> DXX-Archive.3: checking whether compiler optimizes __builtin_object_size...(cached) yes
> DXX-Archive.3: checking whether compiler understands embedded compound statements...(cached) yes
> DXX-Archive.3: checking whether compiler allows dead calls to undefined functions in the anonymous namespace...(cached) no
> DXX-Archive.3: checking for function __attribute__((always_inline))...(cached) yes
> DXX-Archive.3: checking for function __attribute__((alloc_size))...(cached) yes
> DXX-Archive.3: checking for function __attribute__((cold))...(cached) yes
> DXX-Archive.3: checking for function __attribute__((format_arg))...(cached) yes
> DXX-Archive.3: checking for function __attribute__((format(printf)))...(cached) yes
> DXX-Archive.3: checking for function __attribute__((malloc))...(cached) yes
> DXX-Archive.3: checking for function __attribute__((nonnull))...(cached) yes
> DXX-Archive.3: checking for function __attribute__((noreturn))...(cached) yes
> DXX-Archive.3: checking for function __attribute__((used))...(cached) yes
> DXX-Archive.3: checking for function __attribute__((unused))...(cached) yes
> DXX-Archive.3: checking for function __attribute__((warn_unused_result))...(cached) yes
> DXX-Archive.3: checking whether compiler optimizes function __attribute__((__warning__))...(cached) yes
> DXX-Archive.3: checking for C++11 intrinsic static_assert when true...(cached) yes
> DXX-Archive.3: checking for C++11 intrinsic static_assert when false...(cached) yes
> DXX-Archive.3: checking whether compiler handles classes from "using namespace"...(cached) yes
> DXX-Archive.3: checking for required C++11, C++14, C++17 standard features...(cached) yes
> DXX-Archive.3: checking when to pre-compile own headers...never
> DXX-Archive.3: checking when to pre-compile system headers...never
> DXX-Archive.3: checking for explicitly deleted functions with named parameters...(cached) yes
> DXX-Archive.3: checking for C++11 inherited constructors with good unique_ptr<T[]> support...(cached) yes
> DXX-Archive.3: checking whether compiler handles 20-element tuples...(cached) yes
> DXX-Archive.3: checking whether to use overwrite poisoning...(cached) no
> DXX-Archive.3: checking whether to use Valgrind poisoning...(cached) no
> DXX-Archive.3: checking whether to format std::size_t with "%zu"...(cached) yes
> DXX-Archive.3: checking whether compiler argument -Wuseless-cast works with SDL and with constructor inheritance...(cached) yes
> DXX-Archive.3: checking whether to cast operator-(T*,T*) to int...(cached) yes
> DXX-Archive.3: checking for strcasecmp...(cached) yes
> DXX-Archive.3: checking for getaddrinfo...(cached) yes
> DXX-Archive.3: checking for struct timespec...(cached) yes
> DXX-Archive.3: checking for Boost.Config...(cached) no
> DXX-Archive.3: checking for -Wno-implicit-fallthrough...(cached) yes
> DXX-Archive.3: checking whether compiler allows lambda capture of local references...(cached) yes
> DXX-Archive.3: checking whether compiler accepts string literal operator templates...(cached) yes
> DXX-Archive.3: checking whether compiler accepts preferred options...(cached) yes
> DXX-Archive.3: checking whether to build runtime tests...no
> DXX-Archive.3: CHOST: None
> DXX-Archive.3: CXX: 'g++'
> DXX-Archive.3: CPPDEFINES: [('PHYSFS_DEPRECATED', ''), ('NDEBUG',), ('RELEASE',), '_REENTRANT']
> DXX-Archive.3: CPPPATH: ['common/include', 'common/main', '.', '/usr/include/libpng16', '/usr/include/SDL']
> DXX-Archive.3: CPPFLAGS: ['-Wno-sign-compare']
> DXX-Archive.3: CXXFLAGS: ['-g', '-O2', '-ftabstop=4', '-Wall', '-Werror=extra', '-Werror=format=2', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=vla', '-pthread', '-funsigned-char', ('-fvisibility=hidden', '-Wduplicated-branches', '-Wduplicated-cond', '-Wsuggest-attribute=noreturn', '-Wlogical-op', '-Wold-style-cast', '-Wredundant-decls'), '-std=gnu++17', '-Werror=unused', '-Werror=useless-cast', '-Wno-implicit-fallthrough', '-fvisibility=hidden', '-Wduplicated-branches', '-Wduplicated-cond', '-Wsuggest-attribute=noreturn', '-Wlogical-op', '-Wold-style-cast', '-Wredundant-decls']
> DXX-Archive.3: LIBS: ['z', 'png16', 'physfs', 'SDL_image', 'SDL_mixer', 'SDL', 'pthread']
> DXX-Archive.3: LINKFLAGS: []
> DXX-Archive.3: $CCACHE_PREFIX: None
> DXX-Archive.3: $DISTCC_HOSTS: None
> D1X-Rebirth.1: compiling on 'linux'/'x86_64' for 'linux' into . with prefix list ('d1x', '')
> D1X-Rebirth.1: default sharepath is '/usr/local/share/games/d1x-rebirth/'
> D1X-Rebirth.1: CHOST: None
> D1X-Rebirth.1: CXX: 'g++'
> D1X-Rebirth.1: CPPDEFINES: [('PHYSFS_DEPRECATED', ''), ('NDEBUG',), ('RELEASE',), '_REENTRANT', ('DXX_BUILD_DESCENT_I',), ('__STDC_FORMAT_MACROS',), ('DXX_USE_SHAREPATH', 1)]
> D1X-Rebirth.1: CPPPATH: ['common/include', 'common/main', '.', '/usr/include/libpng16', '/usr/include/SDL', 'd1x-rebirth/main']
> D1X-Rebirth.1: CPPFLAGS: ['-Wno-sign-compare']
> D1X-Rebirth.1: CXXFLAGS: ['-g', '-O2', '-ftabstop=4', '-Wall', '-Werror=extra', '-Werror=format=2', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=vla', '-pthread', '-funsigned-char', '-std=gnu++17', '-Werror=unused', '-Werror=useless-cast', '-Wno-implicit-fallthrough', '-fvisibility=hidden', '-Wduplicated-branches', '-Wduplicated-cond', '-Wsuggest-attribute=noreturn', '-Wlogical-op', '-Wold-style-cast', '-Wredundant-decls']
> D1X-Rebirth.1: LIBS: ['z', 'png16', 'physfs', 'SDL_image', 'SDL_mixer', 'SDL', 'pthread', 'm', 'GL', 'GLU']
> D1X-Rebirth.1: LINKFLAGS: []
> D1X-Rebirth.1: $CCACHE_PREFIX: None
> D1X-Rebirth.1: $DISTCC_HOSTS: None
> D2X-Rebirth.2: compiling on 'linux'/'x86_64' for 'linux' into . with prefix list ('d2x', '')
> D2X-Rebirth.2: default sharepath is '/usr/local/share/games/d2x-rebirth/'
> D2X-Rebirth.2: CHOST: None
> D2X-Rebirth.2: CXX: 'g++'
> D2X-Rebirth.2: CPPDEFINES: [('PHYSFS_DEPRECATED', ''), ('NDEBUG',), ('RELEASE',), '_REENTRANT', ('DXX_BUILD_DESCENT_II',), ('__STDC_FORMAT_MACROS',), ('DXX_USE_SHAREPATH', 1)]
> D2X-Rebirth.2: CPPPATH: ['common/include', 'common/main', '.', '/usr/include/libpng16', '/usr/include/SDL', 'd2x-rebirth/main']
> D2X-Rebirth.2: CPPFLAGS: ['-Wno-sign-compare']
> D2X-Rebirth.2: CXXFLAGS: ['-g', '-O2', '-ftabstop=4', '-Wall', '-Werror=extra', '-Werror=format=2', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=vla', '-pthread', '-funsigned-char', '-std=gnu++17', '-Werror=unused', '-Werror=useless-cast', '-Wno-implicit-fallthrough', '-fvisibility=hidden', '-Wduplicated-branches', '-Wduplicated-cond', '-Wsuggest-attribute=noreturn', '-Wlogical-op', '-Wold-style-cast', '-Wredundant-decls']
> D2X-Rebirth.2: LIBS: ['SDL_mixer', 'SDL_image', 'pthread', 'SDL', 'physfs', 'png16', 'z', 'm', 'GL', 'GLU']
> D2X-Rebirth.2: LINKFLAGS: []
> D2X-Rebirth.2: $CCACHE_PREFIX: None
> D2X-Rebirth.2: $DISTCC_HOSTS: None
> scons: done reading SConscript files.
> scons: Building targets ...
> scons: Configure: creating dxxsconf.h
> CXX dxx . common/2d/2dsline.cpp
> CXX dxx . common/2d/bitblt.cpp
> CXX dxx . common/2d/bitmap.cpp
> CXX dxx . common/2d/box.cpp
> CXX dxx . common/2d/canvas.cpp
> In function ‘void dcx::gr_init_canvas(grs_canvas&, unsigned char*, bm_mode, uint16_t, uint16_t)’,
>     inlined from ‘dcx::grs_canvas_ptr dcx::gr_create_canvas(uint16_t, uint16_t)’ at common/2d/canvas.cpp:40:16:
> common/2d/canvas.cpp:59:19: error: ‘<unknown>’ may be used uninitialized [-Werror=maybe-uninitialized]
>    59 |     gr_init_bitmap(canv.cv_bitmap, pixtype, 0, 0, w, h, wreal, pixdata);
>       |     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from common/include/gr.h:29,
>                  from common/2d/canvas.cpp:24:
> common/include/fwd-gr.h: In function ‘dcx::grs_canvas_ptr dcx::gr_create_canvas(uint16_t, uint16_t)’:
> common/include/fwd-gr.h:157:6: note: by argument 8 of type ‘const uint8_t*’ {aka ‘const unsigned char*’} to ‘void dcx::gr_init_bitmap(grs_bitmap&, bm_mode, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, const uint8_t*)’ declared here
>   157 | void gr_init_bitmap(grs_bitmap &bm, bm_mode mode, uint16_t x, uint16_t y, uint16_t w, uint16_t h, uint16_t bytesperline, const uint8_t *data) noexcept;
>       |      ^~~~~~~~~~~~~~
> cc1plus: some warnings being treated as errors
> scons: *** [common/2d/canvas.o] Error 1
> scons: building terminated because of errors.
> Failed target count: total=1; targets with enable_build_failure_summary=1: 1
> Failed node list:
> 	common/2d/canvas.o
> Failed command list:
>  g++ -c -g -O2 -ftabstop=4 -Wall -Werror=extra -Werror=format=2 -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -pthread -funsigned-char -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wsuggest-attribute=noreturn -Wlogical-op -Wold-style-cast -Wredundant-decls -std=gnu++17 -Werror=unused -Werror=useless-cast -Wno-implicit-fallthrough -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wsuggest-attribute=noreturn -Wlogical-op -Wold-style-cast -Wredundant-decls -Wno-sign-compare -DPHYSFS_DEPRECATED= -DNDEBUG -DRELEASE -D_REENTRANT -Icommon/include -Icommon/main -I. -I/usr/include/libpng16 -I/usr/include/SDL "common/2d/canvas.cpp" -o "common/2d/canvas.o"`

**Comment by vLKp** [comment] 2021-06-12 21:08
Please use triple-backtick code blocks for pasting build logs, so that Github does not try to interpret their contents.

> common/2d/canvas.cpp:59:19: error: ‘’ may be used uninitialized [-Werror=maybe-uninitialized]

This is not particularly helpful (omitting the name of the uninitialized object).  However, I can reproduce the issue locally.  By the other message, this appears to be a complaint about `pixdata`.  After exploring a few variations, it seems to be triggered by passing `const uint8_t *pixdata` without first writing any data through the pointer.  Removing the `const` qualifier on `gr_init_bitmap` silences this, presumably because that convinces gcc that the buffer will be initialized externally before being read.

The above commit resolves the error for me.  Please test and report back.

**Comment by TheDemonicSurfer** [comment] 2021-06-13 12:18
Sure enough, the above commit worked fine.

Guess that's that, then.

**Comment by vLKp** [comment] 2021-06-13 16:59
Confirmed fixed by original reporter.  Closing.

**Closed by vLKp** 2021-06-13 16:59 UTC
Labels: build-failure
